### ISSUE TITLE
兑换时间差了一个星期 这个是什么原因呢

### ISSUE THREAD

**Issue by arbitraryGate** [Ljzd-PRO/nonebot-plugin-mystool#104]
![6{SS%K$ HPPN@ER3~@ZK` B](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/31301114/971c7215-77bd-42be-80c0-2a9118e502a8)

**Comment by Ljzd-PRO** [comment]
米游社的商品确实没处理好，兑换时间是错的
~~暂时可以通过修改数据文件里对应的时间戳纠正~~
https://github.com/Ljzd-PRO/Mys_Goods_Tool/commit/d98f397b9e09d10edcc118a650656ecac1eee0c0

**Comment by arbitraryGate** [comment]
ok

**Comment by Kiana1314** [comment]
佬  我是nb商店版的  请问应该怎么改啊？

**Comment by Ljzd-PRO** [comment]
之前弄错了，是我另外一个小工具的数据模型才能修改，目前这个插件改不了，因为兑换计划是只保存商品ID的，每次启动机器人的时候才获取兑换时间。这几天我改一改
https://github.com/Ljzd-PRO/Mys_Goods_Tool
