### ISSUE TITLE
关于绕过人机验证

### ISSUE THREAD

**Issue by ayakasuki** [Ljzd-PRO/nonebot-plugin-mystool#106]
大大，能不能2captcha的接口绕验证码呀，可以config哪里自己添加自己的2captcha的接口来选择是否付费绕过验证码
米哈游的验证码接口据我所知是geetest（极验）

**Comment by Ljzd-PRO** [comment]
原本是可以类似
https://github.com/Ljzd-PRO/Mys_Goods_Tool
的短信验证码登录这样把验证码转移到网页上，可以搭建一个网站，类似go-cqhttp那样点击一个链接进去完成验证。
如果是破解验证操作的话也可以，因为知道对应的`gt`参数和`challenge`参数（极验第三代）。
但是最近米哈游改用极验第四代了，看[极验文档](https://docs.geetest.com/gt4/deploy/client/web/)也还是可以像第三代那样做，但是完成验证后的验证结果米哈游不认，可以参考 https://github.com/Ljzd-PRO/Mys_Goods_Tool/issues/105#issuecomment-1552727784
你也可以研究一下为什么会返回这个

**Comment by Ljzd-PRO** [comment]
获取验证任务：
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/213d0821b434ad000a832dfbef108b89a2164fdd/mys_goods_tool/api.py#L661-L707

用验证结果发送短信验证码：
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/213d0821b434ad000a832dfbef108b89a2164fdd/mys_goods_tool/api.py#L710-L774

**Comment by ayakasuki** [comment]
好的好的 我研究一下

**Comment by Ljzd-PRO** [comment]
已解决 https://github.com/Ljzd-PRO/Mys_Goods_Tool/pull/126
