### ISSUE TITLE
体力验证码

### ISSUE THREAD

**Issue by story-x** [Ljzd-PRO/nonebot-plugin-mystool#109]
大佬，体力（dailyNote）返回1034后能否直接再调用小组件的api查询体力（没有周本和参量质变仪等参数）？

**Comment by Ljzd-PRO** [comment]
是可以改进

**Comment by Night-stars-1** [comment]
> 

小组件的api：https://api-takumi-record.mihoyo.com/game_record/genshin/aapi/widget/v2?game_id=2
ds为旧的，也就是中间的随机数为字母
