### ISSUE TITLE
不清楚为什么发送更新会导致后台无限重启

### ISSUE THREAD

**Issue by PROBEFISH** [Ljzd-PRO/nonebot-plugin-mystool#114]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/108982252/8ffc4403-5047-4cfc-838f-a97fb74ab8f8)

**Comment by Ljzd-PRO** [comment]
是在Linux还是Windows还是macOS上运行的

**Comment by Ljzd-PRO** [comment]
目前Windows和macOS的图片生成可能有点问题，0.2.8没有这个问题，可以看 #108

**Comment by PROBEFISH** [comment]
windows上，而且只运行这个插件的话虽然还是会重启但不会直接崩溃报错
06-12 07:22:41 [SUCCESS] nonebot | OneBot V11 3300918022 | [message.private.friend]: Message -16108 from 12113 '更新'
06-12 07:22:41 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.exchange)       
06-12 07:22:41 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.exchange) running complete
06-12 07:22:41 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:41 [INFO] nonebot | Current Env: prod
06-12 07:22:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:43 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [INFO] nonebot06-12 07:22:43 [ | Current INFOEnv: prod] nonebot
 | Current Env: prod
06-12 07:22:43 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [06-12 07:22:43 [SUCCESSSUCCESS] ] nonebot | NoneBot is initializing...
nonebot | NoneBot is initializing...
06-12 07:22:43 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [INFO] 06-12 07:22:43nonebot [ | Current SUCCESSEnv: prod] nonebot
 | NoneBot is initializing...
06-12 07:22:4306-12 07:22:43 [ [06-12 07:22:43SUCCESSSUCCESS [] ] nonebot06-12 07:22:43nonebot [ | NoneBot is initializing...
 | NoneBot is initializing...
SUCCESSINFO06-12 07:22:43] nonebot | Current ]  [Env: prodnonebotSUCCESS
]  | NoneBot is initializing...
06-12 07:22:43nonebot [ | NoneBot is initializing...
SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [INFO] nonebot06-12 07:22:43 [INFO | Current ] nonebotEnv: prod | Current Env: prod

06-12 07:22:43 [INFO06-12 07:22:4306-12 07:22:43 [] SUCCESS [nonebot] INFO]  | Current nonebotEnv: prodnonebot | Current 
Env: prod | NoneBot is initializing...

06-12 07:22:43 [INFO] nonebot | Current Env: prod06-12 07:22:43
 [INFO] nonebot | Current Env: prod
06-12 07:22:43 [INFO] nonebot | Current Env: prod
06-12 07:22:4306-12 07:22:43 [ [INFOINFO] ] nonebotnonebot | Current  | Current Env: prodEnv: prod
06-12 07:22:43 [INFO] nonebot | Current Env: prod

06-12 07:22:43 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [INFO] nonebot | Current Env: prod
06-12 07:22:43 [SUCCESS] nonebot | NoneBot is initializing...
06-12 07:22:43 [INFO] nonebot | Current Env: prod
06-12 07:22:45 [SUCCESS] nonebot06-12 07:22:45 [ | Succeeded to load plugin "SUCCESSnonebot_plugin_mystool] 06-12 07:22:45"
nonebot [ | Succeeded to load plugin "SUCCESSnonebot_plugin_mystool] "
nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [INFO] nonebot_plugin_mystool | bh2分区暂时没有可兑换的限时商品，跳过该分区的商品图片生成
06-12 07:22:45 [INFO] nonebot_plugin_mystool | 正在生成 bh3 分区的商品列表图片
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:4506-12 07:22:45 [ [INFO] SUCCESS] nonebot_plugin_mystoolnonebot | Succeeded to load plugin "nonebot_plugin_mystool"
 | 正在生成 hk4e 分区的商品列表图片
06-12 07:22:45 [SUCCESS06-12 07:22:45 [] INFOnonebot] nonebot_plugin_mystool | 正在生成 hkrpg 分区的商品列表图片
 | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:46 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:46 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-12 07:22:46 [INFO] nonebot_plugin_mystool | 正在生成 bbs 分区的商品列表图片
06-12 07:22:46 [INFO] nonebot_plugin_mystool | 正在生成 nxx 分区的商品列表图片
06-12 07:22:48 [INFO] nonebot_plugin_mystool | 已完成 bbs 分区的商品列表图片生成
06-12 07:22:49 [INFO] nonebot_plugin_mystool | 已完成 bh3 分区的商品列表图片生成
06-12 07:22:49 [INFO] nonebot_plugin_mystool | 已完成 hkrpg 分区的商品列表图片生成
06-12 07:22:50 [INFO] nonebot_plugin_mystool | 已完成 hk4e 分区的商品列表图片生成
06-12 07:22:50 [INFO] nonebot_plugin_mystool | 已完成 nxx 分区的商品列表图片生成
Cancelling an overlapped future failed
future: <_OverlappedFuture pending overlapped=<pending, 0x20766a01cf0> cb=[_ProactorReadPipeTransport._loop_reading()]>
Traceback (most recent call last):
  File "C:\Users\shi20\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 71, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] 句柄无效。
06-12 07:22:50 [INFO] nonebot_plugin_mystool | 已完成所有分区的商品列表图片生成

**Comment by Ljzd-PRO** [comment]
与 #108 情况相同

**Comment by Ljzd-PRO** [comment]
已修复：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.0.0

**Comment by PROBEFISH** [comment]
我更新了下还是会重启
06-23 14:34:37 [SUCCESS] nonebot | OneBot V11 3300918022 | [message.private.friend]: Message - from '更新'
06-23 14:34:37 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.exchange)
06-23 14:34:37 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.exchange) running complete
06-23 14:34:37 [SUCCESS] nonebot | NoneBot is initializing...
06-23 14:34:37 [INFO] nonebot | Current Env: prod
06-23 14:34:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:39 [06-23 14:34:39 [SUCCESS] nonebot | NoneBot is initializing...
SUCCESS06-23 14:34:39 [] SUCCESSnonebot] nonebot | NoneBot is initializing...
 | NoneBot is initializing...
06-23 14:34:39 [SUCCESS] nonebot | NoneBot is initializing...
06-23 14:34:3906-23 14:34:39 [ [SUCCESSSUCCESS] ] nonebotnonebot | NoneBot is initializing...
 | NoneBot is initializing...
06-23 14:34:39 [INFO] nonebot | Current Env: prod
06-23 14:34:39 [INFO] nonebot | Current Env: prod
06-23 14:34:39 [INFO] nonebot | Current Env: prod
06-23 14:34:39 [SUCCESS] nonebot | NoneBot is initializing...
06-23 14:34:39 [INFO] nonebot | Current Env: prod06-23 14:34:39 [06-23 14:34:39
06-23 14:34:39 [06-23 14:34:39 [SUCCESSSUCCESSSUCCESS [] ] ] SUCCESSnonebot] nonebotnonebot | NoneBot is initializing...
nonebot | NoneBot is initializing...
 | NoneBot is initializing...
 | NoneBot is initializing...
06-23 14:34:39 [INFO] nonebot06-23 14:34:39 | Current  [06-23 14:34:39Env: prod [
SUCCESS] SUCCESSnonebot] 06-23 14:34:3906-23 14:34:3906-23 14:34:39nonebot [ | NoneBot is initializing...
 [ [INFO | NoneBot is initializing...
SUCCESS] ] nonebotSUCCESSnonebot]  | Current nonebot | NoneBot is initializing...
Env: prod | NoneBot is initializing...

06-23 14:34:39 [SUCCESS] nonebot | NoneBot is initializing...
06-23 14:34:39 [INFO] nonebot | Current Env: prod06-23 14:34:39 [
06-23 14:34:3906-23 14:34:3906-23 14:34:3906-23 14:34:39 [INFO] nonebot [ [ | Current INFOEnv: prodINFO06-23 14:34:39 [06-23 14:34:39INFO] 
]  [INFOnonebotINFOnonebot [] INFO] nonebot]  | Current ]  | Current Env: prodnonebotnonebot | Current  | Current  | Current 
nonebotEnv: prodEnv: prodEnv: prodEnv: prod | Current 



Env: prod06-23 14:34:39
 [INFO] nonebot | Current Env: prod
06-23 14:34:39 [INFO] nonebot | Current Env: prod
06-23 14:34:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:41 [SUCCESS] nonebot06-23 14:34:42 | Succeeded to load plugin " [nonebot_plugin_mystoolSUCCESS"
] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:42 [INFO] nonebot_plugin_mystool | 正在生成 hk4e 分区的商品列表图片
06-23 14:34:42 [SUCCESS] 06-23 14:34:42nonebot [ | Succeeded to load plugin "SUCCESSnonebot_plugin_mystool] "
06-23 14:34:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebotnonebot_plugin_mystool"
 | Succeeded to load plugin "nonebot_plugin_mystool"
06-23 14:34:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
