### ISSUE TITLE
这个工具与Mys_Goods_Tool的区别是什么？

### ISSUE THREAD

**Issue by fanlu** [Ljzd-PRO/nonebot-plugin-mystool#115]
https://github.com/Ljzd-PRO/Mys_Goods_Tool

**Comment by Ljzd-PRO** [comment]
Mys_Goods_Tool 是专门兑换的工具软件，这个是NoneBot机器人插件，还有一些别的功能。

**Comment by fanlu** [comment]
这个工具安装好该怎么使用呢？有操作界面吗？发送命令的时候该选择QQ用户里面的谁？

**Comment by fanlu** [comment]
<img width="1298" alt="image" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/1620875/c6badcde-dde0-4b5a-979d-37259ea1c101">
这样就代表安装成功了吧？

**Comment by Ljzd-PRO** [comment]
> <img alt="image" width="1298" src="https://user-images.githubusercontent.com/1620875/245346840-c6badcde-dde0-4b5a-979d-37259ea1c101.png"> 这样就代表安装成功了吧？

是的，可以QQ给这个机器人发送 /帮助 查看帮助信息
