### ISSUE TITLE
原神便笺: 用户 *** DS 校验失败

### ISSUE THREAD

**Issue by story-x** [Ljzd-PRO/nonebot-plugin-mystool#117]
版本：1.0.0b1

便笺无法获取体力信息（下面是log）
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/45375162/427fa657-455e-40b5-89e4-6f04a41fe4b1)

我用机器人直接请求接口可以正常获取数据
![bf540b498c92a7e41a8b042f38ae1c20](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/45375162/29b253f9-b9e5-4c68-b7fc-146356ac389c)

**Comment by story-x** [comment]
米游币任务也一样：DS 校验失败

**Comment by fanlu** [comment]
你去用米游社的客户端点一下，然后再来看看，好像被米游社检测到了

**Comment by story-x** [comment]
> 你去用米游社的客户端点一下，然后再来看看，好像被米游社检测到了

点了也是这个，我已经过了1034

**Comment by Ljzd-PRO** [comment]
1.0.0 之前的似乎也不行 #112，应该是API变动了

**Comment by fanlu** [comment]
我看安装文档是用的pip安装的指定版本0.2.8或者0.2.9，如何通过源代码使用1.0.0 b1？在pyproject.toml里面进行本地文件夹配置？

**Comment by Night-stars-1** [comment]
> 1.0.0 之前的似乎也不行 #112，应该是API变动了

并不是，在获取ds时

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/ed7dbc6cc1599c4890c96e2041c6f116270260f6/src/nonebot_plugin_mystool/utils.py#L205
salt != _conf.salt_config.SALT_PROD:
会返回真导致获取到了不正确的ds，实际上or后面也应该返回假

**Comment by Ljzd-PRO** [comment]
> > 1.0.0 之前的似乎也不行 #112，应该是API变动了
> 
> 并不是，在获取ds时
> 
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/ed7dbc6cc1599c4890c96e2041c6f116270260f6/src/nonebot_plugin_mystool/utils.py#L205
> 
> 
> salt != _conf.salt_config.SALT_PROD:
> 会返回真导致获取到了不正确的ds，实际上or后面也应该返回假

返回
```json
{"data":null,"message":"","retcode":1034}
```

不过还不确定是不是确实Cookies过期了，7月初有空了我再看看。

**Comment by Ljzd-PRO** [comment]
修改以后，似乎讨论区签到成功的概率变高了，原来签到失败的现在可以签到成功。

**Comment by Night-stars-1** [comment]
> > > 1.0.0 之前的似乎也不行 #112，应该是API变动了
> > 
> > 
> > 并不是，在获取ds时
> > https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/ed7dbc6cc1599c4890c96e2041c6f116270260f6/src/nonebot_plugin_mystool/utils.py#L205
> > 
> > salt != _conf.salt_config.SALT_PROD:
> > 会返回真导致获取到了不正确的ds，实际上or后面也应该返回假
> 
> 返回
> 
> ```json
> {"data":null,"message":"","retcode":1034}
> ```
> 
> 不过还不确定是不是确实Cookies过期了，7月初有空了我再看看。

1034是触发了验证码

**Comment by Night-stars-1** [comment]
> 修改以后，似乎讨论区签到成功的概率变高了，原来签到失败的现在可以签到成功。

之前评论区签到出现ds错误也是因为这里
