### ISSUE TITLE
geetest_url 这个怎么弄啊。（看不懂不会操作）

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#122]

**Comment by Ljzd-PRO** [comment]
配置这个需要有一个那种可以帮你进行人机验证的打码平台，一般都是付费的。通常这些平台会有个API可以用，把那个API URL填入就可以。

**Comment by beiji-O-o** [comment]
> 配置这个需要有一个那种可以帮你进行人机验证的打码平台，一般都是付费的。通常这些平台会有个API可以用，把那个API URL填入就可以。

极验 注册有点麻烦 ，有什么其他推荐的平台吗

**Comment by beiji-O-o** [comment]
> > 配置这个需要有一个那种可以帮你进行人机验证的打码平台，一般都是付费的。通常这些平台会有个API可以用，把那个API URL填入就可以。
> 
> 极验 注册有点麻烦 ，有什么其他推荐的平台吗

极验客服告诉我他们是防止验证码被识别的不是绕过的。

**Comment by Ljzd-PRO** [comment]
极验是给米哈游提供人机验证服务的平台，你要找那种能绕过极验人机验证的平台

**Comment by beiji-O-o** [comment]
> 极验是给米哈游提供人机验证服务的平台，你要找那种能绕过极验人机验证的平台

有推荐的吗

**Comment by Ljzd-PRO** [comment]
我也还没用过，可以问一下 @Night-stars-1

**Comment by Ljzd-PRO** [comment]
> 我也还没用过，可以问一下 @Night-stars-1

#119

**Comment by beiji-O-o** [comment]
> > 我也还没用过，可以问一下 @Night-stars-1
> 
> #119

好的。

**Comment by beiji-O-o** [comment]
> 极验是给米哈游提供人机验证服务的平台，你要找那种能绕过极验人机验证的平台

![895de0ac49f2e10c6cd5d959ec17af2](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/16cb3542-dbd0-4fce-a401-054f4cf9aa2a)
这个要怎么弄啊
跟说明里面要gt和challenge

**Comment by Ljzd-PRO** [comment]
> > 极验是给米哈游提供人机验证服务的平台，你要找那种能绕过极验人机验证的平台
> 
> ![895de0ac49f2e10c6cd5d959ec17af2](https://user-images.githubusercontent.com/100279019/248595745-16cb3542-dbd0-4fce-a401-054f4cf9aa2a.jpg) 这个要怎么弄啊 跟说明里面要gt和challenge

应当只需要gt和challenge才对的，因为人机验证要进行交互，不是简单的识别一下图片
