### ISSUE TITLE
原神实时便签缺少参量质变仪数据，不断提醒

### ISSUE THREAD

**Issue by Unreal-Null** [Ljzd-PRO/nonebot-plugin-mystool#123]
现在每小时提示一次，没找到在哪里调整时间，
![9a984140a3632406eb0f2cf39abfb49c](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/63513356/07c65e67-6635-4330-a7f2-a1964c8eb129)

**Comment by Unreal-Null** [comment]
现在都是先关闭这个功能
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/63513356/be387b38-b7a6-4036-bed3-64c101d8de9c)

**Comment by story-x** [comment]
可能是参量质变仪没有获取到数据，一直在提醒
