### ISSUE TITLE
我更新了下还是会重启

### ISSUE THREAD

**Issue by PROBEFISH** [Ljzd-PRO/nonebot-plugin-mystool#127]
06-25 22:21:22 [SUCCESS] nonebot | OneBot V11 3300918022 | [message.private.friend]: Message - from  '更新'
06-25 22:21:22 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.exchange)
06-25 22:21:22 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.exchange) running complete
06-25 22:21:22 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:22 [INFO] nonebot | Current Env: prod
06-25 22:21:23 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-25 22:21:24 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24 [INFO] nonebot | Current Env: prod
06-25 22:21:24 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24 [06-25 22:21:24 [SUCCESSINFO] ] nonebotnonebot | NoneBot is initializing...
 | Current 06-25 22:21:24 [Env: prodSUCCESS] 
06-25 22:21:24nonebot06-25 22:21:24 [ [ | NoneBot is initializing...
SUCCESSINFO] ] nonebotnonebot06-25 22:21:24 [ | NoneBot is initializing...
SUCCESS]  | Current nonebot06-25 22:21:24 [ | NoneBot is initializing...
SUCCESSEnv: prod06-25 22:21:24] nonebot
 [ | NoneBot is initializing...
SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24 [INFO] nonebot | Current Env: prod
06-25 22:21:2406-25 22:21:2406-25 22:21:24 [ [ [INFOINFO] INFO] nonebot] nonebot | Current  | Current Env: prodnonebotEnv: prod | Current Env: prod

06-25 22:21:24 [INFO] nonebot | Current Env: prod
06-25 22:21:2406-25 22:21:2406-25 22:21:24 [ [SUCCESS [INFO] ] INFOnonebotnonebot]  | NoneBot is initializing...
 | Current nonebotEnv: prod06-25 22:21:24 | Current 
 [Env: prodSUCCESS]
nonebot | NoneBot is initializing...
06-25 22:21:24 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24 [06-25 22:21:24 [SUCCESS] nonebot | NoneBot is initializing...
06-25 22:21:24SUCCESS06-25 22:21:2406-25 22:21:24 []  [nonebotINFO [INFO]  | NoneBot is initializing...
INFO] nonebot] nonebotnonebot | Current  | Current  | Current Env: prodEnv: prodEnv: prod

06-25 22:21:24 [INFO] nonebot | Current Env: prod
06-25 22:21:24 [INFO] nonebot | Current Env: prod
06-25 22:21:24 [INFO] nonebot | Current Env: prod
06-25 22:21:26 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-25 22:21:26 [INFO] nonebot_plugin_mystool | bh3分区暂时没有可兑换的限时商品，跳过该分区的商品图片生成
06-25 22:21:27 [06-25 22:21:27SUCCESS [] nonebotSUCCESS]  | Succeeded to load plugin "nonebotnonebot_plugin_mystool"
 | Succeeded to load plugin "nonebot_plugin_mystool"
06-25 22:21:2706-25 22:21:27 [06-25 22:21:27 [SUCCESS06-25 22:21:2706-25 22:21:27SUCCESS]  [ [] SUCCESSnonebotSUCCESSnonebot] ]  | Succeeded to load plugin "nonebot | Succeeded to load plugin "nonebot | Succeeded to load plugin "nonebot_plugin_mystoolnonebot_plugin_mystool"
 | Succeeded to load plugin "nonebot_plugin_mystool"
nonebot_plugin_mystool"
"
06-25 22:21:2706-25 22:21:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
 [ [SUCCESSSUCCESS] ] nonebotnonebot | Succeeded to load plugin " | Succeeded to load plugin "nonebot_plugin_mystoolnonebot_plugin_mystool"
"
06-25 22:21:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-25 22:21:27 [SUCCESS06-25 22:21:2706-25 22:21:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
]  [nonebotSUCCESS | Succeeded to load plugin "] nonebot_plugin_mystoolnonebot"
 | Succeeded to load plugin "nonebot_plugin_mystool"
06-25 22:21:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-25 22:21:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-25 22:21:27 [INFO] nonebot_plugin_mystool | 正在生成 hk4e 分区的商品列表图片
06-25 22:21:27 [INFO] nonebot_plugin_mystool06-25 22:21:27 [ | 正在生成 hkrpg 分区的商品列表图片
INFO] nonebot_plugin_mystool | nxx分区暂时没有可兑换的限时商品，跳过该分区的商品图片生成
06-25 22:21:27 [INFO] nonebot_plugin_mystool | bh2分区暂时没有可兑换的限时商品，跳过该分区的商品图片生成
06-25 22:21:27 [INFO] nonebot_plugin_mystool | bbs分区暂时没有可兑换的限时商品，跳过该分区的商品图片生成
06-25 22:21:29 [INFO] nonebot_plugin_mystool | 已完成 hkrpg 分区的商品列表图片生成
06-25 22:21:30 [INFO] nonebot_plugin_mystool | 已完成 hk4e 分区的商品列表图片生成
06-25 22:21:30 [INFO] nonebot_plugin_mystool | 已完成所有分区的商品列表图片生成

**Comment by Ljzd-PRO** [comment]
应该只是数次重复初始化？有没有报错

**Comment by PROBEFISH** [comment]
没有报错，只开这一个插件触发更新后自己重启几次就正常了，但多开些插件就会不停的重启然后直接崩溃

**Comment by Ljzd-PRO** [comment]
增加了是否使用多进程生成商品图片的配置项 `good_list_image_config`.`MULTI_PROCESS`，如果遇到生成图片失败可以尝试关闭该项
