### ISSUE TITLE
希望可以适配qq频道

### ISSUE THREAD

**Issue by ShaoNian-end** [Ljzd-PRO/nonebot-plugin-mystool#128]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/60726341/182b385a-f06c-474d-84b7-d34b5064c531)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/60726341/e84e35b1-32df-4b04-8d83-6a8d59ea156e)

**Comment by beiji-O-o** [comment]
+1 qq一下就给我风控了 我现在直接给通知都关了

**Comment by Night-stars-1** [comment]
qq频道没办法发链接，这是大问题

**Comment by ShaoNian-end** [comment]
> qq频道没办法发链接，这是大问题

如果只是登录的话，其实可以让用户自己去浏览器或者米游社

**Comment by Ljzd-PRO** [comment]
二维码可以吗

**Comment by ShaoNian-end** [comment]
> 二维码可以吗

![Screenshot_2023-06-30-14-07-36-877_com.tencent.mobileqq.png](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/60726341/78e56d4b-694e-4e4a-8927-1bc463acd506)

好像可以

**Comment by Ljzd-PRO** [comment]
看了一下应该是可以发链接的，和频道管理里的设置有关

**Comment by Ljzd-PRO** [comment]
已经基本完成，但还需要测试。目前QQ频道的主动私信次数限制带来了一些问题，如果发送了三条私信消息给机器人，机器人还没有回复，就不能继续发送。尝试机器人主动发送私信，目前也是无法发送成功。

**Comment by Ljzd-PRO** [comment]
已发布beta1版本：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.2.0-beta.1
