### ISSUE TITLE
签到问题

### ISSUE THREAD

**Issue by admimare** [Ljzd-PRO/nonebot-plugin-mystool#130]
如题 报错信息如下
![IMG_0993](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/74863664/d2a5d285-e241-49cf-8dab-24796880ff16)

**Comment by admimare** [comment]
是不是没有适配yunzai

**Comment by admimare** [comment]
是不是没有适配yunzai 导致功能不可以

**Comment by admimare** [comment]
是不是没有适配yunzai 导致功能不可用

**Comment by Ljzd-PRO** [comment]
看上去不是，不过这是之前的版本了，可以更新一下插件，新版本修复了许多Bug

**Comment by Ljzd-PRO** [comment]
然后，1.0.0 新版本插件数据文件与之前的版本不兼容

**Comment by admimare** [comment]
> 然后，1.0.0 新版本插件数据文件与之前的版本不兼容

好的 我试试更新插件

**Comment by Ljzd-PRO** [comment]
是崩坏三签到吗？
我这里也提示了错误，原因是崩坏三签到目前在维护中：
```
07-02 12:05:51 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","
```

**Comment by admimare** [comment]
我是直接不能用 可能消息不支持yunzai在 2023年7月2日，12:07，Ljzd PRO ***@***.***> 写道：﻿
是崩坏三签到吗？
我这里也提示了错误，原因是崩坏三签到目前在维护中：
07-02 12:05:51 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","

**Comment by Ljzd-PRO** [comment]
新版本也不能用吗？如果是报错在执行签到的那个网络请求上，就应该不是机器人的兼容问题

**Comment by Ljzd-PRO** [comment]
#139
