### ISSUE TITLE
签到报错

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#131]
![1688255987761](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/4f3f9ce1-9cee-449f-87f6-b9bd851aef20)
这个是为什么

**Comment by Ljzd-PRO** [comment]
获取游戏签到记录失败，有可能是遇到了人机验证什么的

**Comment by Ljzd-PRO** [comment]
这个账号下有任何米哈游的游戏账号吗？就是有用它玩过任何的游戏吗？

**Comment by beiji-O-o** [comment]
> 这个账号下有任何米哈游的游戏账号吗？就是有用它玩过任何的游戏吗？

有的

**Comment by Ljzd-PRO** [comment]
把DEBUG级别日志记录开启，应该可以看到这样的报错详情：
```
07-02 12:05:51 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","
```
目前崩坏三签到米哈游还在维护中

**Comment by SerPolar** [comment]
> 

我签的是大别野
我这里有2个号都是大别野 就这号签会报错

**Comment by beiji-O-o** [comment]
> 把DEBUG级别日志记录开启，应该可以看到这样的报错详情：
> 
> ```
> 07-02 12:05:51 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","
> ```
> 
> 目前崩坏三签到米哈游还在维护中

我签的是大别野

**Comment by Ljzd-PRO** [comment]
> > 把DEBUG级别日志记录开启，应该可以看到这样的报错详情：
> > ```
> > 07-02 12:05:51 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 目前崩坏三签到米哈游还在维护中
> 
> 我签的是大别野

这里报错的是游戏签到，不是讨论区签到。

**Comment by SerPolar** [comment]
> > > 把DEBUG级别日志记录开启，应该可以看到这样的报错详情：
> > > ```
> > > 07-02 12:05:51 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 目前崩坏三签到米哈游还在维护中
> > 
> > 
> > 我签的是大别野
> 
> 这里报错的是游戏签到，不是讨论区签到。

![45592029956b01348edec3e69600390](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/7cd86b7a-dbca-48a7-a20d-98dd63c800e4)
这是机器人的提示 游戏签到我没打开，打码平台不会弄。

**Comment by beiji-O-o** [comment]
> > > 把DEBUG级别日志记录开启，应该可以看到这样的报错详情：
> > > ```
> > > 07-02 12:05:51 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 目前崩坏三签到米哈游还在维护中
> > 
> > 
> > 我签的是大别野
> 
> 这里报错的是游戏签到，不是讨论区签到。

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/49955173-2206-47ae-a5e4-0264c8ae1e5e)
这是机器人的提示 游戏签到我没打开，打码平台不会弄。

**Comment by Ljzd-PRO** [comment]
这里签到指的就是游戏签到，我也签到失败了，也是获取记录失败，原因是米游社在维护中。游戏签到关闭没效果的话，可能是1.0.0版本需要更新到1.0.1

**Comment by beiji-O-o** [comment]
> 这里签到指的就是游戏签到，我也签到失败了，也是获取记录失败，原因是米游社在维护中。游戏签到关闭没效果的话，可能是1.0.0版本需要更新到1.0.1

我是1.0.1

**Comment by beiji-O-o** [comment]
> 这里签到指的就是游戏签到，我也签到失败了，也是获取记录失败，原因是米游社在维护中。游戏签到关闭没效果的话，可能是1.0.0版本需要更新到1.0.1

![2E1C34FA-9711-46B6-A4A3-5D69F8863EBF](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/308d3039-17f1-4e19-a273-f1735390e882)

**Comment by Ljzd-PRO** [comment]
可以把日志记录级别设置为DEBUG，可以看到网络请求的完整返回体。
这个讨论区签到失败，一般就是遇到了人机验证，比较正常，可能手动去App签到一下可以降低概率。另外点赞、转发、阅读，一般是不会遇到人机验证。

**Comment by Ljzd-PRO** [comment]
之后可能会做一个网页，手动发送命令执行签到的时候如果遇到验证码，可以在网页上手动完成一下，减少之后自动签到遇到验证码度概率

**Comment by beiji-O-o** [comment]
> 之后可能会做一个网页，手动发送命令执行签到的时候如果遇到验证码，可以在网页上手动完成一下，减少之后自动签到遇到验证码度概率

可以啊（顺便问问什么时候加个userkey）

**Comment by SerPolar** [comment]
> 可以把日志记录级别设置为DEBUG，可以看到网络请求的完整返回体。
> 这个讨论区签到失败，一般就是遇到了人机验证，比较正常，可能手动去App签到一下可以降低概率。另外点赞、转发、阅读，一般是不会遇到人机验证。

这个在哪里改 我好像没找到

**Comment by Ljzd-PRO** [comment]
#139
