### ISSUE TITLE
geetest_url加个userkey参数

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#133]

**Comment by taskmgr818** [comment]
这个还是自己加吧，不同平台的参数名不一样，有token/appkey/userkey，或者提前预留多个平台的接口

**Comment by beiji-O-o** [comment]
> 这个还是自己加吧，不同平台的参数名不一样，有token/appkey/userkey，或者提前预留多个平台的接口

就是因为我不会加😂

**Comment by taskmgr818** [comment]
在utils.py里content变量中加一句 "userkey":"你的token" 应该就行

**Comment by taskmgr818** [comment]
不过我之前找了一圈打码平台，价格低且稳定的好像只有rrocr，而且不同平台参数好像都不太一样，返回值格式也有点区别，感觉只做一个平台的API应该就行

**Comment by beiji-O-o** [comment]
> 在utils.py里content变量中加一句 "userkey":"你的token" 应该就行

这个我试用了 加完运行就报错了

**Comment by Ljzd-PRO** [comment]
content里是json数据，如果是url参数的话，简单点可以直接在配置平台url的时候，加在后面。
比如：
```
https://xxx.com/?userkey=ABCdefg
```

**Comment by beiji-O-o** [comment]
> content里是json数据，如果是url参数的话，简单点可以直接在配置平台url的时候，加在后面。 比如：
> 
> ```
> https://xxx.com/?userkey=ABCdefg
> ```
这个userkey是需要写在json里的
