### ISSUE TITLE
原神签到失败

### ISSUE THREAD

**Issue by MarSeventh** [Ljzd-PRO/nonebot-plugin-mystool#134]
想问下原神签到一直失败，但是手动在米游社签完后再执行`/签到`又可以正常获取签到信息是什么原因。报错如下：
07-04 00:30:13 [INFO] nonebot_plugin_mystool | 开始执行每日自动任务
07-04 00:32:54 [INFO] nonebot_plugin_mystool | 游戏签到 - 用户  DS 校验失败
07-04 00:32:54 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-04 00:32:59 [INFO] nonebot_plugin_mystool | 每日自动任务执行完成
07-04 00:40:13 [INFO] nonebot_plugin_mystool | 游戏签到 - 用户  DS 校验失败
07-04 00:40:13 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-04 00:52:19 [INFO] nonebot_plugin_mystool | 游戏签到 - 用户  DS 校验失败

**Comment by MarSeventh** [comment]
补充一下：其他游戏的自动签到都正常完成，只有原神不行。并且米游社自动任务的点赞也无法正常完成。

**Comment by beiji-O-o** [comment]
前几天我旧发现原神签不全，我试了大别野可以我就没反馈了。最近会有一个新的问题就是漏任务，有时候点赞没点完、有时候又是没分享

**Comment by Ljzd-PRO** [comment]
#136 也是一样的情况。可以试一下用插件的账号设置把设备改为iOS

**Comment by Ljzd-PRO** [comment]
> 想问下原神签到一直失败，但是手动在米游社签完后再执行`/签到`又可以正常获取签到信息是什么原因。

如果已经签到过了，实际上会跳过发送签到的请求

**Comment by Ljzd-PRO** [comment]
可能是App版本号需要更新了，就是插件偏好设置里的X-RPC-APP_VERSION

**Comment by MarSeventh** [comment]
> #136 也是一样的情况。可以试一下用插件的账号设置把设备改为iOS

改了之后确实可以签到了😀

**Comment by beiji-O-o** [comment]
> #136 也是一样的情况。可以试一下用插件的账号设置把设备改为iOS

有时候任务做不全是为什么

**Comment by Ljzd-PRO** [comment]
> > #136 也是一样的情况。可以试一下用插件的账号设置把设备改为iOS
> 
> 有时候任务做不全是为什么

可以检查一下日志，错过的话可以看日志文件，在机器人目录下的`data/nonebot-plugin-mystool`里

**Comment by beiji-O-o** [comment]
> > > #136 也是一样的情况。可以试一下用插件的账号设置把设备改为iOS
> > 
> > 
> > 有时候任务做不全是为什么
> 
> 可以检查一下日志，错过的话可以看日志文件，在机器人目录下的`data/nonebot-plugin-mystool`里

![9136AF96-5FB2-420D-BC69-A1AF95F91E9B](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/cdef3bec-d72e-4ba2-9f9e-9441a274b1a9)

好像没有任务做不全的报错

**Comment by Joseandluue** [comment]
> 

开头就是“报错”了，服务器没有正确返回，去尝试重新登录获取ck等数据

**Comment by dontdot** [comment]
> > > > #136 也是一样的情况。可以试一下用插件的账号设置把设备改为iOS
> > > 
> > > 
> > > 有时候任务做不全是为什么
> > 
> > 
> > 可以检查一下日志，错过的话可以看日志文件，在机器人目录下的`data/nonebot-plugin-mystool`里
> 
> ![9136AF96-5FB2-420D-BC69-A1AF95F91E9B](https://user-images.githubusercontent.com/100279019/251618088-cdef3bec-d72e-4ba2-9f9e-9441a274b1a9.png)
> 
> 好像没有任务做不全的报错

服务器没有正确返回，去尝试重新登录获取ck等数据再/任务看看

**Comment by beiji-O-o** [comment]
> > > > > #136 也是一样的情况。可以试一下用插件的账号设置把设备改为iOS
> > > > 
> > > > 
> > > > 有时候任务做不全是为什么
> > > 
> > > 
> > > 可以检查一下日志，错过的话可以看日志文件，在机器人目录下的`data/nonebot-plugin-mystool`里
> > 
> > 
> > ![9136AF96-5FB2-420D-BC69-A1AF95F91E9B](https://user-images.githubusercontent.com/100279019/251618088-cdef3bec-d72e-4ba2-9f9e-9441a274b1a9.png)
> > 好像没有任务做不全的报错
> 
> 服务器没有正确返回，去尝试重新登录获取ck等数据再/任务看看

还是这样
