### ISSUE TITLE
机器人每隔一小时发一次便笺

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#135]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/756f421e-b384-4978-9b9c-70e1863c0b1c)
安装了最新版本的机器人 会每隔一小时发一遍便笺 是设置有问题还是bug?

**Comment by Ljzd-PRO** [comment]
和 #123 一样，是Bug，v1.0.1 应该是修复了，看来还是不行
