### ISSUE TITLE
变量的读取在写入之前

### ISSUE THREAD

**Issue by Night-stars-1** [Ljzd-PRO/nonebot-plugin-mystool#137]
部分变量的读取在写入之前，使得更改不生效
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/27af8e38-4293-4d2f-8b33-c2dfcde1ad4f)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/2c54f6a9-e704-49f0-8acf-f07c997ba6cc)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/cc973ee9-45bf-4488-b0fb-0622d8112643)
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/27abfa7c5cfa9468f5d1717c812a76e02181fe1c/src/nonebot_plugin_mystool/plugin_data.py#L227-L260

**Comment by Ljzd-PRO** [comment]
是哪些变量呢？只要尽量不在导入阶段使用 `PluginDataManager.plugin_data_obj` 就可以

**Comment by Night-stars-1** [comment]
> 是哪些变量呢？只要尽量不在导入阶段使用 `PluginDataManager.plugin_data_obj` 就可以

所有请求的header

**Comment by Night-stars-1** [comment]
> 是哪些变量呢？只要尽量不在导入阶段使用 `PluginDataManager.plugin_data_obj` 就可以

所有请求的header

**Comment by Night-stars-1** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/commit/7768d3c056378dcdf6e4397d2a8a9e894bcd2d06
该更改无效
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/2636dfb9-80a8-40e6-bcd8-2707c70b6ee8)
<img width="209" alt="image" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/66fcf3e1-9e1c-4bf8-9021-9f4e85d01c4c">

**Comment by Night-stars-1** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/commit/63820cc71f850994b43a92fe850f84c031933a97
还是在写入之前读取
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/74a0dabe-38d3-4386-9e36-1ebe86fb2113)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/b6eff6dc-88b2-4e3e-bc84-69cf68e30fe7)
<img width="364" alt="image" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/143e9e40-b8a8-4836-bbcf-accd62d3068e">
