### ISSUE TITLE
游戏签到返回“签到功能维护中...”

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#139]
<img width="980" alt="屏幕截图 2023-07-14 121754" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/5fd84f95-25ac-4151-9d47-9385397aa8bf">

**Comment by Ljzd-PRO** [comment]
现在还会这样吗

**Comment by beiji-O-o** [comment]
> 现在还会这样吗

还会

**Comment by beiji-O-o** [comment]
![2BD7C958-FADA-487B-8DA0-E970060EC0EF](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/ed0a8e49-c7a6-4005-a015-f5291ce4d860)

**Comment by Ljzd-PRO** [comment]
已修复
