### ISSUE TITLE
第一次启动插件，卡在“正在检查好友列表”

### ISSUE THREAD

**Issue by black-zero358** [Ljzd-PRO/nonebot-plugin-mystool#149]
![)BL_PLSS4Z293)_TVQY`)L3](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/53086059/b3466895-5b38-4952-b4cd-b483b95d9988)
如果在短时间内强行结束，不会出现报错
在等待一段时间后，强行结束会出现报错。

**Comment by Ljzd-PRO** [comment]
检查好友列表的日志弹出之后，可以正常用插件吗？因为只会有开始检查的日志，不会有检查完成的日志

**Comment by black-zero358** [comment]
> 友列表的日志弹出之后，可以正常用插件吗？因为只会有开始

可以正常使用
