### ISSUE TITLE
游戏签到失败 DS 校验失败

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#150]
游戏签到提示签到失败，但是我手动去签到并没有遇到人机验证。
（另外有人已经用了打码吗？）

**Comment by Ljzd-PRO** [comment]
是 #139 的情况吗？目前还没有修复，可能是要更新`x-rpc-app_version`

**Comment by beiji-O-o** [comment]
> 是#139的情况吗？目前还没有修复，可能是要更新`x-rpc-app_version`

不是，#139是有崩坏3，这个是原神和星穹

**Comment by dontdot** [comment]
> 是 #139 的情况吗？目前还没有修复，可能是要更新`x-rpc-app_version`

应该是headers，ds或者salt这其中的问题。
上版本我用你的主体，签到部分我换成@Night-stars-1的def sign和get_validate，没问题（目前我把整个版本换回来也没问题）
在新版本，我同样换成@Night-stars-1的def sign和get_validate，崩铁签到成功，但是原神出现问题：
```
07-26 03:11:14 [INFO] nonebot_plugin_mystool | 原神签到开始
07-26 03:11:14 [INFO] nonebot_plugin_mystool | GeetestResult(validate='', seccode='')
07-26 03:11:14 [INFO] nonebot_plugin_mystool | 原神签到验证码:
07-26 03:11:14 [INFO] nonebot_plugin_mystool | {'data': None, 'message': 'invalid request', 'retcode': -10001}
07-26 03:11:14 [INFO] nonebot_plugin_mystool | 游戏签到 - 用户 76454149 DS 校验失败
07-26 03:11:14 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-26 03:11:14 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
```

**Comment by beiji-O-o** [comment]
> > 是 #139 的情况吗？目前还没有修复，可能是要更新`x-rpc-app_version`
> 
> 应该是headers，ds或者salt这其中的问题。 上版本我用你的主体，签到部分我换成@Night-stars-1的def sign和get_validate，没问题（目前我把整个版本换回来也没问题） 在新版本，我同样换成@Night-stars-1的def sign和get_validate，崩铁签到成功，但是原神出现问题：
> 
> ```
> 07-26 03:11:14 [INFO] nonebot_plugin_mystool | 原神签到开始
> 07-26 03:11:14 [INFO] nonebot_plugin_mystool | GeetestResult(validate='', seccode='')
> 07-26 03:11:14 [INFO] nonebot_plugin_mystool | 原神签到验证码:
> 07-26 03:11:14 [INFO] nonebot_plugin_mystool | {'data': None, 'message': 'invalid request', 'retcode': -10001}
> 07-26 03:11:14 [INFO] nonebot_plugin_mystool | 游戏签到 - 用户 76454149 DS 校验失败
> 07-26 03:11:14 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
> 07-26 03:11:14 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> ```

yes就是这样

**Comment by Ljzd-PRO** [comment]
已修复

**Comment by beiji-O-o** [comment]
> 已修复
![code](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/5e718455-3555-4ff0-9219-7b52d80fea9e)

**Comment by beiji-O-o** [comment]
<img width="988" alt="屏幕截图 2023-07-28 192310" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/37e484c0-30a8-41a9-8763-e1c8ed7bd56f">

还有个问题这是打码生效了吗？

**Comment by dontdot** [comment]
> <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> 还有个问题这是打码生效了吗？

没有，你有设置geetest_url吗

**Comment by beiji-O-o** [comment]
> > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > 还有个问题这是打码生效了吗？
> 
> 没有，你有设置geetest_url吗

设置了
<img width="398" alt="屏幕截图 2023-07-28 193601" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/fc18e8af-a36f-4efb-80aa-d0834cf4706e">

**Comment by SerPolar** [comment]
> > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > 还有个问题这是打码生效了吗？
> > 
> > 
> > 没有，你有设置geetest_url吗
<img width="398" alt="屏幕截图 2023-07-28 193601" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/156b2b3e-0f6f-46c2-a9af-f715476a1642">

> 
> 设置了

**Comment by dontdot** [comment]
> > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > 还有个问题这是打码生效了吗？
> > 
> > 
> > 没有，你有设置geetest_url吗
> 
> 设置了 <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256811400-fc18e8af-a36f-4efb-80aa-d0834cf4706e.png">

你去utils加上244行这个看看返回什么数据回来

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/ed17f919-b437-4a9e-81d5-8894899cd211)

**Comment by SerPolar** [comment]
> > > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > > 还有个问题这是打码生效了吗？
> > > 
> > > 
> > > 没有，你有设置geetest_url吗
> > 
> > 
> > 设置了 <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256811400-fc18e8af-a36f-4efb-80aa-d0834cf4706e.png">
> 
> 你去utils加上244行这个看看返回什么数据回来
> 
> ![image](https://user-images.githubusercontent.com/55482264/256811792-ed17f919-b437-4a9e-81d5-8894899cd211.png)

utils在哪里啊？

**Comment by beiji-O-o** [comment]
> > > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > > 还有个问题这是打码生效了吗？
> > > 
> > > 
> > > 没有，你有设置geetest_url吗
> > 
> > 
> > 设置了 <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256811400-fc18e8af-a36f-4efb-80aa-d0834cf4706e.png">
> 
> 你去utils加上244行这个看看返回什么数据回来
> 
> ![image](https://user-images.githubusercontent.com/55482264/256811792-ed17f919-b437-4a9e-81d5-8894899cd211.png)

<img width="1030" alt="屏幕截图 2023-07-28 195228" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/0074101e-c3c3-4d78-b595-45d5c149a65f">

**Comment by dontdot** [comment]
> > > > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > > > 还有个问题这是打码生效了吗？
> > > > 
> > > > 
> > > > 没有，你有设置geetest_url吗
> > > 
> > > 
> > > 设置了 <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256811400-fc18e8af-a36f-4efb-80aa-d0834cf4706e.png">
> > 
> > 
> > 你去utils加上244行这个看看返回什么数据回来
> > ![image](https://user-images.githubusercontent.com/55482264/256811792-ed17f919-b437-4a9e-81d5-8894899cd211.png)
> 
> <img alt="屏幕截图 2023-07-28 195228" width="1030" src="https://user-images.githubusercontent.com/100279019/256814365-0074101e-c3c3-4d78-b595-45d5c149a65f.png">

你这没有返回打码后的响应结果，不太清楚你这个平台还要什么步骤，你最好去看看他们的官方文档

**Comment by beiji-O-o** [comment]
> > > > > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > > > > 还有个问题这是打码生效了吗？
> > > > > 
> > > > > 
> > > > > 没有，你有设置geetest_url吗
> > > > 
> > > > 
> > > > 设置了 <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256811400-fc18e8af-a36f-4efb-80aa-d0834cf4706e.png">
> > > 
> > > 
> > > 你去utils加上244行这个看看返回什么数据回来
> > > ![image](https://user-images.githubusercontent.com/55482264/256811792-ed17f919-b437-4a9e-81d5-8894899cd211.png)
> > 
> > 
> > <img alt="屏幕截图 2023-07-28 195228" width="1030" src="https://user-images.githubusercontent.com/100279019/256814365-0074101e-c3c3-4d78-b595-45d5c149a65f.png">
> 
> 你这没有返回打码后的响应结果，不太清楚你这个平台还要什么步骤，你最好去看看他们的官方文档

那你用的啥平台，我试试呗😂

**Comment by Joseandluue** [comment]
> 

rrocr

**Comment by dontdot** [comment]
> > > > > > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > > > > > 还有个问题这是打码生效了吗？
> > > > > > 
> > > > > > 
> > > > > > 没有，你有设置geetest_url吗
> > > > > 
> > > > > 
> > > > > 设置了 <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256811400-fc18e8af-a36f-4efb-80aa-d0834cf4706e.png">
> > > > 
> > > > 
> > > > 你去utils加上244行这个看看返回什么数据回来
> > > > ![image](https://user-images.githubusercontent.com/55482264/256811792-ed17f919-b437-4a9e-81d5-8894899cd211.png)
> > > 
> > > 
> > > <img alt="屏幕截图 2023-07-28 195228" width="1030" src="https://user-images.githubusercontent.com/100279019/256814365-0074101e-c3c3-4d78-b595-45d5c149a65f.png">
> > 
> > 
> > 你这没有返回打码后的响应结果，不太清楚你这个平台还要什么步骤，你最好去看看他们的官方文档
> 
> 那你用的啥平台，我试试呗😂

rrocr

**Comment by beiji-O-o** [comment]
> rrocr

谢谢
还有就是 能看看你的json吗？😂

**Comment by dontdot** [comment]
> > rrocr
> 
> 谢谢 还有就是 能看看你的json吗？😂



> > rrocr
> 
> 谢谢 还有就是 能看看你的json吗？😂

我没动json,还是你要看返回后的json内容？

**Comment by beiji-O-o** [comment]
> > > rrocr
> > 
> > 
> > 谢谢 还有就是 能看看你的json吗？😂
> 
> > > rrocr
> > 
> > 
> > 谢谢 还有就是 能看看你的json吗？😂
> 
> 我没动json,还是你要看返回后的json内容？

<img width="398" alt="屏幕截图 2023-07-28 193601" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/4c0cb9aa-3bcb-4186-af45-39777ee55411">
就是这个的内容

**Comment by dontdot** [comment]
> > > > rrocr
> > > 
> > > 
> > > 谢谢 还有就是 能看看你的json吗？😂
> > 
> > 
> > > > rrocr
> > > 
> > > 
> > > 谢谢 还有就是 能看看你的json吗？😂
> > 
> > 
> > 我没动json,还是你要看返回后的json内容？
> 
> <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png"> 就是这个的内容

这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分

**Comment by beiji-O-o** [comment]
> > > > > rrocr
> > > > 
> > > > 
> > > > 谢谢 还有就是 能看看你的json吗？😂
> > > 
> > > 
> > > > > rrocr
> > > > 
> > > > 
> > > > 谢谢 还有就是 能看看你的json吗？😂
> > > 
> > > 
> > > 我没动json,还是你要看返回后的json内容？
> > 
> > 
> > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png"> 就是这个的内容
> 
> 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分

好的谢谢！

**Comment by beiji-O-o** [comment]
> > > > > 罗克
> > > > 
> > > > 
> > > > 谢谢还有能看看你的json吗？😂
> > > 
> > > 
> > > > > 罗克
> > > > 
> > > > 
> > > > 谢谢还有能看看你的json吗？😂
> > > 
> > > 
> > > 我没动json，还是你忽略返回后面的json内容？
> > 
> > 
> > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> 
> 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/ab245ef8-c449-4291-ab37-b79602fbd3f9)
这个填啥啊？

**Comment by dontdot** [comment]
> > > > > > 罗克
> > > > > 
> > > > > 
> > > > > 谢谢还有能看看你的json吗？😂
> > > > 
> > > > 
> > > > > > 罗克
> > > > > 
> > > > > 
> > > > > 谢谢还有能看看你的json吗？😂
> > > > 
> > > > 
> > > > 我没动json，还是你忽略返回后面的json内容？
> > > 
> > > 
> > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > 
> > 
> > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> 
> ![image](https://user-images.githubusercontent.com/100279019/256821423-ab245ef8-c449-4291-ab37-b79602fbd3f9.png) 这个填啥啊？

https://webstatic.mihoyo.com/

**Comment by beiji-O-o** [comment]
> > > > > 罗克
> > > > 
> > > > 
> > > > 谢谢还能看看你的json吗？😂
> > > 
> > > 
> > > > > 罗克
> > > > 
> > > > 
> > > > 谢谢还能看看你的json吗？😂
> > > 
> > > 
> > > 我没动json，还是忽略了后面的json内容？
> > 
> > 
> > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> 
> 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/346cf37c-9498-4356-b033-83763aca993b)
我写了appkey还是这样。

**Comment by dontdot** [comment]
> > > > > > 罗克
> > > > > 
> > > > > 
> > > > > 谢谢还能看看你的json吗？😂
> > > > 
> > > > 
> > > > > > 罗克
> > > > > 
> > > > > 
> > > > > 谢谢还能看看你的json吗？😂
> > > > 
> > > > 
> > > > 我没动json，还是忽略了后面的json内容？
> > > 
> > > 
> > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > 
> > 
> > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> 
> ![image](https://user-images.githubusercontent.com/100279019/256821903-346cf37c-9498-4356-b033-83763aca993b.png) 我写了appkey还是这样。

appkey跟url一起，不用另外放

**Comment by dontdot** [comment]
> > > > > > > 罗克
> > > > > > 
> > > > > > 
> > > > > > 谢谢还能看看你的json吗？😂
> > > > > 
> > > > > 
> > > > > > > 罗克
> > > > > > 
> > > > > > 
> > > > > > 谢谢还能看看你的json吗？😂
> > > > > 
> > > > > 
> > > > > 我没动json，还是忽略了后面的json内容？
> > > > 
> > > > 
> > > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > > 
> > > 
> > > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/100279019/256821903-346cf37c-9498-4356-b033-83763aca993b.png) 我写了appkey还是这样。
> 
> appkey跟url一起，不用另外放

我晚点截图给你看看data文件，我现在不在电脑前

**Comment by beiji-O-o** [comment]
> https://webstatic.mihoyo.com/

好的 ，谢谢

**Comment by beiji-O-o** [comment]
> > > > > > > 罗克
> > > > > > 
> > > > > > 
> > > > > > 谢谢还能看看你的json吗？😂
> > > > > 
> > > > > 
> > > > > > > 罗克
> > > > > > 
> > > > > > 
> > > > > > 谢谢还能看看你的json吗？😂
> > > > > 
> > > > > 
> > > > > 我没动json，还是忽略了后面的json内容？
> > > > 
> > > > 
> > > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > > 
> > > 
> > > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/100279019/256821903-346cf37c-9498-4356-b033-83763aca993b.png)我写了appkey还是这样。
> 
> appkey跟url一起，不用另外放

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/c401deab-9783-426a-9b53-1bb18a62624e)

**Comment by dontdot** [comment]
> > > > > > > > 罗克
> > > > > > > 
> > > > > > > 
> > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > 
> > > > > > 
> > > > > > > > 罗克
> > > > > > > 
> > > > > > > 
> > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > 
> > > > > > 
> > > > > > 我没动json，还是忽略了后面的json内容？
> > > > > 
> > > > > 
> > > > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > > > 
> > > > 
> > > > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/100279019/256821903-346cf37c-9498-4356-b033-83763aca993b.png)我写了appkey还是这样。
> > 
> > 
> > appkey跟url一起，不用另外放
> 
> ![image](https://user-images.githubusercontent.com/100279019/256826990-c401deab-9783-426a-9b53-1bb18a62624e.png)

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/ecdbbd94-300a-4713-9607-c7e231bcf5de)
你是这么填的吗

**Comment by beiji-O-o** [comment]
> > > > > > > > > 罗克
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > > 
> > > > > > > 
> > > > > > > > > 罗克
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > > 
> > > > > > > 
> > > > > > > 我没动json，还是忽略了后面的json内容？
> > > > > > 
> > > > > > 
> > > > > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > > > > 
> > > > > 
> > > > > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> > > > 
> > > > 
> > > > ![图像](https://user-images.githubusercontent.com/100279019/256821903-346cf37c-9498-4356-b033-83763aca993b.png)我写了appkey还是这样。
> > > 
> > > 
> > > appkey跟url一起，不用另外放
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/100279019/256826990-c401deab-9783-426a-9b53-1bb18a62624e.png)
> 
> ![图像](https://user-images.githubusercontent.com/55482264/256828165-ecdbbd94-300a-4713-9607-c7e231bcf5de.png) 你是这样的吗

<img width="680" alt="屏幕截图 2023-07-28 210501" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/0fb3e555-9802-47e5-8929-e3b7a0aa4f00">

**Comment by dontdot** [comment]
> > > > > > > > > > 罗克
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > > > 
> > > > > > > > 
> > > > > > > > > > 罗克
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我没动json，还是忽略了后面的json内容？
> > > > > > > 
> > > > > > > 
> > > > > > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > > > > > 
> > > > > > 
> > > > > > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> > > > > 
> > > > > 
> > > > > ![图像](https://user-images.githubusercontent.com/100279019/256821903-346cf37c-9498-4356-b033-83763aca993b.png)我写了appkey还是这样。
> > > > 
> > > > 
> > > > appkey跟url一起，不用另外放
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/100279019/256826990-c401deab-9783-426a-9b53-1bb18a62624e.png)
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/55482264/256828165-ecdbbd94-300a-4713-9607-c7e231bcf5de.png) 你是这样的吗
> 
> <img alt="屏幕截图 2023-07-28 210501" width="680" src="https://user-images.githubusercontent.com/100279019/256828914-0fb3e555-9802-47e5-8929-e3b7a0aa4f00.png">

你试下这个：json不要填，初始就好,然后把get_validate换成这个
```
async def get_validate(gt: str = None, challenge: str = None, retry: bool = True):
    """
    使用打码平台获取人机验证validate

    :param gt: 验证码gt
    :param challenge: challenge
    :param retry: 是否允许重试
    :return: 如果配置了平台URL，且 gt, challenge 不为空，返回 GeetestResult
    """
    content = {
        "gt": gt,
        "challenge": challenge
    }

    if gt and challenge and _conf.preference.geetest_url:
        try:
            url_with_geetest_url = f"{_conf.preference.geetest_url}&referer=https://webstatic.mihoyo.com/&gt={gt}&challenge={challenge}"
            async for attempt in get_async_retry(retry):
                with attempt:
                    async with httpx.AsyncClient() as client:
                        res = await client.post(
                            url_with_geetest_url,
                            timeout=60,
                            json=content)
                    geetest_data = res.json()
                    logger.info(f"打码:{geetest_data}")
                    validate=geetest_data['data']['validate']
                    return GeetestResult(validate=validate, seccode="")
        except tenacity.RetryError:
            logger.exception(f"{_conf.preference.log_head}获取人机验证validate失败")
    else:
        return GeetestResult("", "")

```

**Comment by beiji-O-o** [comment]
> > > > > > > > > > > 罗克
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > > > 罗克
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 谢谢还能看看你的json吗？😂
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我没动json，还是忽略了后面的json内容？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256818768-4c0cb9aa-3bcb-4186-af45-39777ee55411.png">就是这个内容
> > > > > > > 
> > > > > > > 
> > > > > > > 这个我没动过，你可以去我fork的仓库里v1.4分支的utils中看下关于get_validate部分
> > > > > > 
> > > > > > 
> > > > > > ![图像](https://user-images.githubusercontent.com/100279019/256821903-346cf37c-9498-4356-b033-83763aca993b.png)我写了appkey还是这样。
> > > > > 
> > > > > 
> > > > > appkey跟url一起，不用另外放
> > > > 
> > > > 
> > > > ![图像](https://user-images.githubusercontent.com/100279019/256826990-c401deab-9783-426a-9b53-1bb18a62624e.png)
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/55482264/256828165-ecdbbd94-300a-4713-9607-c7e231bcf5de.png)你是这样的吗
> > 
> > 
> > <img alt="屏幕截图 2023-07-28 210501" width="680" src="https://user-images.githubusercontent.com/100279019/256828914-0fb3e555-9802-47e5-8929-e3b7a0aa4f00.png">
> 
> 你试下这个：json不要填，基本上就好了，然后把get_validate换成这个
> 
> ```
> async def get_validate(gt: str = None, challenge: str = None, retry: bool = True):
>     """
>     使用打码平台获取人机验证validate
> 
>     :param gt: 验证码gt
>     :param challenge: challenge
>     :param retry: 是否允许重试
>     :return: 如果配置了平台URL，且 gt, challenge 不为空，返回 GeetestResult
>     """
>     content = {
>         "gt": gt,
>         "challenge": challenge
>     }
> 
>     if gt and challenge and _conf.preference.geetest_url:
>         try:
>             url_with_geetest_url = f"{_conf.preference.geetest_url}&referer=https://webstatic.mihoyo.com/&gt={gt}&challenge={challenge}"
>             async for attempt in get_async_retry(retry):
>                 with attempt:
>                     async with httpx.AsyncClient() as client:
>                         res = await client.post(
>                             url_with_geetest_url,
>                             timeout=60,
>                             json=content)
>                     geetest_data = res.json()
>                     logger.info(f"打码:{geetest_data}")
>                     validate=geetest_data['data']['validate']
>                     return GeetestResult(validate=validate, seccode="")
>         except tenacity.RetryError:
>             logger.exception(f"{_conf.preference.log_head}获取人机验证validate失败")
>     else:
>         return GeetestResult("", "")
> ```

好了，可以打码了！谢谢
但是还是有报错签到不了

**Comment by Ljzd-PRO** [comment]
> 

用dev分支里的，可以参考https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Installation#%E6%96%B9%E6%B3%95%E4%B8%89%E4%B8%8B%E8%BD%BD%E6%BA%90%E4%BB%A3%E7%A0%81%E6%94%BE%E5%85%A5%E6%8C%87%E5%AE%9A%E7%9B%AE%E5%BD%95

**Comment by Ljzd-PRO** [comment]
修复后的代码还没有发新版本

**Comment by dontdot** [comment]
> 修复后的代码还没有发新版本

dev分支，我选择不装nonebot-adapter-qqguild没办法成功运行机器人，如果全部安装，我该怎么去选择用v11呢

**Comment by Ljzd-PRO** [comment]
> > 修复后的代码还没有发新版本
> 
> dev分支，我选择不装nonebot-adapter-qqguild没办法成功运行机器人，如果全部安装，我该怎么去选择用v11呢

qqguild不去配置就可以了。反过来如果只想用qqguild也是一样。

**Comment by Ljzd-PRO** [comment]
> > > 修复后的代码还没有发新版本
> > 
> > 
> > dev分支，我选择不装nonebot-adapter-qqguild没办法成功运行机器人，如果全部安装，我该怎么去选择用v11呢
> 
> qqguild不去配置就可以了。反过来如果只想用qqguild也是一样。

或者用nb-cli安装以后，再把nonebot目录下 `pyproject.toml` 里的适配器列表 删掉qqguild。

**Comment by dontdot** [comment]
> > > > 修复后的代码还没有发新版本
> > > 
> > > 
> > > dev分支，我选择不装nonebot-adapter-qqguild没办法成功运行机器人，如果全部安装，我该怎么去选择用v11呢
> > 
> > 
> > qqguild不去配置就可以了。反过来如果只想用qqguild也是一样。
> 
> 或者用nb-cli安装以后，再把nonebot目录下 `pyproject.toml` 里的适配器列表 删掉qqguild。

确实这样可以，装了qqguild，再从`pyproject.toml` 里删除，不然会出现
`ModuleNotFoundError: No module named 'nonebot.adapters.qqguild'`的

另外我两次删除data.json，再运行都会提示`device_config`不存在
```
07-28 21:57:22 [INFO] nonebot_plugin_mystool | 插件数据文件 C:\Users\Administrator\qbpwe\mhy\data\nonebot-plugin-mystool\plugin_data.json 不存在，已创建默认插件数据文件。
07-28 21:57:24 [ERROR] nonebot | Failed to import "nonebot_plugin_mystool"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\plugin\manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot_plugin_mystool\__init__.py", line 46, in <module>
    __import__(file, globals(), level=1)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot_plugin_mystool\address.py", line 12, in <module>
    from .simple_api import get_address
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot_plugin_mystool\simple_api.py", line 23, in <module>
    device_config = PluginDataManager.device_config
AttributeError: type object 'PluginDataManager' has no attribute 'device_config'
```

**Comment by beiji-O-o** [comment]
> > > > > > > > <img alt="屏幕截图 2023-07-28 192310" width="988" src="https://user-images.githubusercontent.com/100279019/256808870-37e484c0-30a8-41a9-8763-e1c8ed7bd56f.png">
> > > > > > > > 还有个问题这是打码生效了吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 没有，你有设置geetest_url吗
> > > > > > 
> > > > > > 
> > > > > > 设置了 <img alt="屏幕截图 2023-07-28 193601" width="398" src="https://user-images.githubusercontent.com/100279019/256811400-fc18e8af-a36f-4efb-80aa-d0834cf4706e.png">
> > > > > 
> > > > > 
> > > > > 你去utils加上244行这个看看返回什么数据回来
> > > > > ![image](https://user-images.githubusercontent.com/55482264/256811792-ed17f919-b437-4a9e-81d5-8894899cd211.png)
> > > > 
> > > > 
> > > > <img alt="屏幕截图 2023-07-28 195228" width="1030" src="https://user-images.githubusercontent.com/100279019/256814365-0074101e-c3c3-4d78-b595-45d5c149a65f.png">
> > > 
> > > 
> > > 你这没有返回打码后的响应结果，不太清楚你这个平台还要什么步骤，你最好去看看他们的官方文档
> > 
> > 
> > 那你用的啥平台，我试试呗😂
> 
> rrocr

大佬，rrocr好像停运了😂，还有其他打码平台推荐吗

**Comment by dontdot** [comment]
#299
