### ISSUE TITLE
可以接受到请求，但QQ频道没有反应

### ISSUE THREAD

**Issue by novolandist** [Ljzd-PRO/nonebot-plugin-mystool#153]
(venv) PS C:\Users\81599\Downloads\PythonCode\pythonProject3\miyoTest> nb run                                                                                                           
使用 Python: C:\Users\81599\Downloads\PythonCode\pythonProject3\miyoTest\.venv\Scripts\python.exe
08-02 09:27:24 [SUCCESS] nonebot | NoneBot is initializing...
08-02 09:27:24 [INFO] nonebot | Current Env: prod
08-02 09:27:24 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
08-02 09:27:26 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
08-02 09:27:26 [SUCCESS] nonebot | Running NoneBot...
08-02 09:27:26 [INFO] nonebot_plugin_apscheduler | Scheduler Started
08-02 09:27:26 [INFO] nonebot | Application startup completed.
08-02 09:27:27 [INFO] nonebot | QQ Guild | Bot 102059245 connected
08-02 09:27:27 [SUCCESS] nonebot | QQ Guild 102059245 | [EventType.READY]: {'version': 1, 'session_id': 'xxx', 'user': {'id': xxx, 'username': 'Novo的机器人测试中', 'avatar': None, 'bot': True, 'union_openid': None, 'union_user_account': None}, 'shard': (0, 1)}
08-02 09:27:57 [SUCCESS] nonebot | QQ Guild 102059245 | [EventType.MESSAGE_CREATE]: Message 088acb8b85c7b286b540109996e99d023809489ee2a6a606 from xxx@[Guild:4641550491294295434/599411481] Roles:[4, 11]: /帮助
08-02 09:27:57 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.help)
08-02 09:27:57 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.help) running complete

**Comment by Ljzd-PRO** [comment]
插件版本是多少呢？还是是dev分支的

**Comment by novolandist** [comment]
> 插件版本是多少呢？还是是dev分支的

是使用脚手架进行安装的。不知道怎么查看版本号。
Lib文件夹下有一个nonebot_plugin_mystool-1.1.0.dist-info的文件
nb plugin install nonebot-plugin-mystool

**Comment by Ljzd-PRO** [comment]
目前要1.2.0b1才支持QQ频道，或者直接用dev分支的代码，dev相比发布的beta又修复了一些bug：
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Installation#%E6%96%B9%E6%B3%95%E4%B8%89%E4%B8%8B%E8%BD%BD%E6%BA%90%E4%BB%A3%E7%A0%81%E6%94%BE%E5%85%A5%E6%8C%87%E5%AE%9A%E7%9B%AE%E5%BD%95

**Comment by novolandist** [comment]
> 目前要1.2.0b1才支持QQ频道，或者直接用dev分支的代码，dev相比发布的beta又修复了一些bug： https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Installation#%E6%96%B9%E6%B3%95%E4%B8%89%E4%B8%8B%E8%BD%BD%E6%BA%90%E4%BB%A3%E7%A0%81%E6%94%BE%E5%85%A5%E6%8C%87%E5%AE%9A%E7%9B%AE%E5%BD%95

我使用PyPI安装后并修改机器人目录的 pyproject.toml 文件后，会提示ModuleNotFoundError: No module named 'nonebot_plugin_mystool'
将源代码目录放入机器人工作目录下的 src/plugins 目录并修改配置文件后，运行会显示"xxx\miyoTest\src\plugins\nonebot_plugin_mystool\__init__.py", line 34, in <module>
    from .utils import CommandBegin
  File "xxx\miyoTest\src\plugins\nonebot_plugin_mystool\utils.py", line 30, in <module>
    from qrcode import QRCode
ModuleNotFoundError: No module named 'qrcode'

**Comment by Ljzd-PRO** [comment]
dev的增加了依赖，需要补装依赖。

- 如果创建nonebot机器人项目的时候有选择创建venv虚拟环境，先进入虚拟环境（参考：https://docs.python.org/zh-cn/3/library/venv.html#how-venvs-work ）
- 可以把插件项目下的`requirements.txt`依赖列表复制到机器人项目目录下，然后安装里面的依赖：`pip install -r requirements.txt`
- 输入 `deactivate` 退出项目虚拟环境

**Comment by Ljzd-PRO** [comment]
如果机器人项目有使用虚拟环境，用PyPI安装也需要进入虚拟环境再安装
相当于是机器人项目和外界是隔离开的，外界就只有nb-cli脚手架，机器人的插件还有插件依赖是安装在机器人项目的虚拟环境里。

**Comment by Ljzd-PRO** [comment]
nonebot的虚拟环境目录是`.venv`

**Comment by Ljzd-PRO** [comment]
另外直接用nb-cli脚手架就可以安装beta版了。
可以看：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.2.0-beta.1
下面的命令

**Comment by novolandist** [comment]
> 另外直接用nb-cli脚手架就可以安装beta版了。 可以看：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.2.0-beta.1 下面的命令

使用脚手架安装会显示
包 nonebot-plugin-mystool==1.2.0b1 未找到.

**Comment by novolandist** [comment]
> * requirements.txt

我没有找到requirements.txt文件

**Comment by novolandist** [comment]
切换到目录进入虚拟环境后安装qrcode后能正常运行了！
非常感谢您的帮助!

**Comment by novolandist** [comment]
点击登录输入手机号后会报错
08-03 10:53:36 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_mystool.login) running complete
08-03 10:53:36 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_mystool.login) failed.
Traceback (most recent call last):
``````
nonebot.adapters.qqguild.exception.ActionFailed: <ActionFailed: 403, code=304003, message=url not allowed, data=None>
我在文档里看到这个错误码是
304003 | URL_NOT_ALLOWED url 未报备

**Comment by Ljzd-PRO** [comment]
> 点击登录输入手机号后会报错 08-03 10:53:36 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_mystool.login) running complete 08-03 10:53:36 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_mystool.login) failed. Traceback (most recent call last):
> 
> ```
> nonebot.adapters.qqguild.exception.ActionFailed: <ActionFailed: 403, code=304003, message=url not allowed, data=None>
> 我在文档里看到这个错误码是
> 304003 | URL_NOT_ALLOWED url 未报备
> ```

能登录成功吗？发送URL失败是因为QQ频道机器人有限制，需要在QQ开放平台那边登录，添加URL到白名单里，就是报备URL。
然后似乎半夜的时候图片也无法发送。私聊无法发送二维码。

**Comment by novolandist** [comment]
> > 点击登录输入手机号后会报错 08-03 10:53:36 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_mystool.login) running complete 08-03 10:53:36 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_mystool.login) failed. Traceback (most recent call last):
> > ```
> > nonebot.adapters.qqguild.exception.ActionFailed: <ActionFailed: 403, code=304003, message=url not allowed, data=None>
> > 我在文档里看到这个错误码是
> > 304003 | URL_NOT_ALLOWED url 未报备
> > ```
> 
> 能登录成功吗？发送URL失败是因为QQ频道机器人有限制，需要在QQ开放平台那边登录，添加URL到白名单里，就是报备URL。 然后似乎半夜的时候图片也无法发送。私聊无法发送二维码。

已经设置好了。再次感谢！
