### ISSUE TITLE
插件加载失败 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by A7424** [Ljzd-PRO/nonebot-plugin-mystool#154]
![4L8IK~J5WQO{QTHF}{@G(ZC](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/103619507/d6935468-16a6-4374-9c8b-f695cad664e3)
已更新nonebot_plugin_apscheduler至0.2.0

**Comment by Ljzd-PRO** [comment]
需要python3.9以及以上

**Comment by A7424** [comment]
> 需要python3.9以及以上

好的

**Comment by A7424** [comment]
> 需要python3.9以及以上

![} F%E2B@D KWX{`48)0 NYV](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/103619507/68319ae2-4f82-4fd7-8127-2e65493188cd)
依旧报错，python已切换至3.10.10，还是说必须得3.9

**Comment by Ljzd-PRO** [comment]
如果机器人项目创建的时候选择了创建虚拟环境，更换python版本以后可能要重新创建，因为虚拟环境包含了python解释器，仍然是3.8的。之前的数据文件可以直接迁移过来。

**Comment by A7424** [comment]
> 如果机器人项目创建的时候选择了创建虚拟环境，更换python版本以后可能要重新创建，因为虚拟环境包含了python解释器，仍然是3.8的。之前的数据文件可以直接迁移过来。

该如何重新创建呢，我尝试安装pyenv切换py版本，pyenv install 3.9.10/3.10.5安装成功后，pyenv global 3.9.10切换版本，但没有切换成功
![)@ 1N)HOQYJT{DZK3X$E{NH](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/103619507/0567b999-fc41-4901-bbb3-f2b2cee86d9d)
