### ISSUE TITLE
米游社任务完成不全

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#157]
<img width="981" alt="微信截图_20230805210256" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/55e7bfee-3e89-4188-a2b6-988c35d0cf82">

还有一个问题是星穹铁道自动签到不了

**Comment by Ljzd-PRO** [comment]
应该是遇到了人机验证。这个是讨论区签到，不是游戏签到。手动去App签到会遇到人机验证吗？

**Comment by beiji-O-o** [comment]
> 应该是遇到了人机验证。这个是讨论区签到，不是游戏签到。手动去App签到会遇到人机验证吗？

这个报错截图是米游社讨论区的报错，我手动去讨论区没有人机验证。
星穹的游戏签到，是有人机验证，我已经设置好了打码平台，其他地方都可以打，星穹这里好像不行。

**Comment by dontdot** [comment]
```
08-14 07:05:15 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
08-14 07:05:19 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
08-14 07:05:22 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
08-14 07:05:25 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
08-14 07:05:25 [ERROR] nonebot_plugin_mystool | 米游币任务 - 讨论区签到: 服务器没有正确返回
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\myb_missions_api.py", line 153, in sign
    return api_result.data["points"]
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 529, in daily_schedule
    await perform_bbs_sign(user_id=qq)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 294, in perform_bbs_sign
    await mission_obj.sign()
> File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\myb_missions_api.py", line 128, in sign
    async for attempt in get_async_retry(retry):
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x25f1afeacd0 state=finished raised TypeError>]
08-14 07:58:23 [SUCCESS] nonebot | OneBot V11 123456 | [message.private.friend]: Message -1410418478 from 12 '/任务'
08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 1...
08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 2...
08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 4...
08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 5...
08-14 07:58:23 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.plan)
08-14 07:58:23 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.plan)
08-14 07:58:23 [DEBUG] nonebot | Running handler Dependent(call=_)
08-14 07:58:23 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
08-14 07:58:28 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
08-14 07:58:31 [INFO] nonebot_plugin_mystool | myb:content={'retcode': 0, 'message': 'OK', 'data': {'points': 40}} data={'points': 40} message='OK' retcode=None
08-14 07:58:35 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
08-14 07:58:39 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
08-14 07:58:43 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
08-14 07:58:43 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.plan) running complete
``` 
一样，自动签会不行，自己输入/任务触发没问题

**Comment by beiji-O-o** [comment]
> ```
> 08-14 07:05:15 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:19 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:22 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:25 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:25 [ERROR] nonebot_plugin_mystool | 米游币任务 - 讨论区签到: 服务器没有正确返回
> Traceback (most recent call last):
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\myb_missions_api.py", line 153, in sign
>     return api_result.data["points"]
> TypeError: 'NoneType' object is not subscriptable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 19, in <module>
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\__init__.py", line 309, in run
>     get_driver().run(*args, **kwargs)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
>     uvicorn.run(
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\main.py", line 578, in run
>     server.run()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\server.py", line 61, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 640, in run_until_complete
>     self.run_forever()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 607, in run_forever
>     self._run_once()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 1922, in _run_once
>     handle._run()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
>     retval = await job.func(*job.args, **job.kwargs)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 529, in daily_schedule
>     await perform_bbs_sign(user_id=qq)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 294, in perform_bbs_sign
>     await mission_obj.sign()
> > File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\myb_missions_api.py", line 128, in sign
>     async for attempt in get_async_retry(retry):
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\_asyncio.py", line 71, in __anext__
>     do = self.iter(retry_state=self._retry_state)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\__init__.py", line 326, in iter
>     raise retry_exc from fut.exception()
> tenacity.RetryError: RetryError[<Future at 0x25f1afeacd0 state=finished raised TypeError>]
> 08-14 07:58:23 [SUCCESS] nonebot | OneBot V11 123456 | [message.private.friend]: Message -1410418478 from 12 '/任务'
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 1...
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 2...
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 4...
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 5...
> 08-14 07:58:23 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.plan)
> 08-14 07:58:23 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.plan)
> 08-14 07:58:23 [DEBUG] nonebot | Running handler Dependent(call=_)
> 08-14 07:58:23 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:28 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:31 [INFO] nonebot_plugin_mystool | myb:content={'retcode': 0, 'message': 'OK', 'data': {'points': 40}} data={'points': 40} message='OK' retcode=None
> 08-14 07:58:35 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:39 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:43 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:43 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.plan) running complete
> ```
> 
> 
>     
>  
>   
> 
> 一样，自动签会不行，自己输入/任务触发没问题



> ```
> 08-14 07:05:15 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:19 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:22 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:25 [INFO] nonebot_plugin_mystool | myb:content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
> 08-14 07:05:25 [ERROR] nonebot_plugin_mystool | 米游币任务 - 讨论区签到: 服务器没有正确返回
> Traceback (most recent call last):
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\myb_missions_api.py", line 153, in sign
>     return api_result.data["points"]
> TypeError: 'NoneType' object is not subscriptable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 19, in <module>
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\__init__.py", line 309, in run
>     get_driver().run(*args, **kwargs)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
>     uvicorn.run(
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\main.py", line 578, in run
>     server.run()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\server.py", line 61, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 640, in run_until_complete
>     self.run_forever()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 607, in run_forever
>     self._run_once()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 1922, in _run_once
>     handle._run()
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
>     retval = await job.func(*job.args, **job.kwargs)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 529, in daily_schedule
>     await perform_bbs_sign(user_id=qq)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 294, in perform_bbs_sign
>     await mission_obj.sign()
> > File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\myb_missions_api.py", line 128, in sign
>     async for attempt in get_async_retry(retry):
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\_asyncio.py", line 71, in __anext__
>     do = self.iter(retry_state=self._retry_state)
>   File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\__init__.py", line 326, in iter
>     raise retry_exc from fut.exception()
> tenacity.RetryError: RetryError[<Future at 0x25f1afeacd0 state=finished raised TypeError>]
> 08-14 07:58:23 [SUCCESS] nonebot | OneBot V11 123456 | [message.private.friend]: Message -1410418478 from 12 '/任务'
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 1...
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 2...
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 4...
> 08-14 07:58:23 [DEBUG] nonebot | Checking for matchers in priority 5...
> 08-14 07:58:23 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.plan)
> 08-14 07:58:23 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.plan)
> 08-14 07:58:23 [DEBUG] nonebot | Running handler Dependent(call=_)
> 08-14 07:58:23 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:28 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:31 [INFO] nonebot_plugin_mystool | myb:content={'retcode': 0, 'message': 'OK', 'data': {'points': 40}} data={'points': 40} message='OK' retcode=None
> 08-14 07:58:35 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:39 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:43 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 08-14 07:58:43 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.plan) running complete
> ```
> 
> 
>      
>   
> 
> 一样，自动签会不行，自己输入/任务触发没问题

我这个手动/任务都做不完

**Comment by dontdot** [comment]
> 

尝试过更新ck吗，又或者更换/增加社区

**Comment by beiji-O-o** [comment]
> 尝试过更新ck吗，又或者更换/增加社区

更新ck是啥，我把原神换成大别野就可以

**Comment by dontdot** [comment]
> > 尝试过更新ck吗，又或者更换/增加社区
> 
> 更新ck是啥，我把原神换成大别野就可以

我没表达清楚，是cookie

**Comment by beiji-O-o** [comment]
> > > 尝试过更新ck吗，又或者更换/增加社区
> > 
> > 
> > 更新ck是啥，我把原神换成大别野就可以
> 
> 我没表达清楚，是cookie

重新绑定米游社也不行

**Comment by beiji-O-o** [comment]
> > > 尝试过更新ck吗，又或者更换/增加社区
> > 
> > 
> > 更新ck是啥，我把原神换成大别野就可以
> 
> 我没表达清楚，是cookie

怎么更新cookie

> > > 尝试过更新ck吗，又或者更换/增加社区
> > 
> > 
> > 更新ck是啥，我把原神换成大别野就可以
> 
> 我没表达清楚，是cookie

怎么更新

**Comment by Ljzd-PRO** [comment]
目前米游币任务里的“讨论区签到”，暂时没有人机验证功能。

**Comment by Ljzd-PRO** [comment]
> 目前米游币任务里的“讨论区签到”，暂时没有人机验证功能。

过段时间应该会加上

**Comment by dontdot** [comment]
> > 目前米游币任务里的“讨论区签到”，暂时没有人机验证功能。
> 
> 过段时间应该会加上

自动检查米游币任务会`米游币任务 - 讨论区签到: 服务器没有正确返回`，而手动命令触发任务却没问题，有头绪吗

**Comment by Ljzd-PRO** [comment]
> > > 目前米游币任务里的“讨论区签到”，暂时没有人机验证功能。
> > 
> > 
> > 过段时间应该会加上
> 
> 自动检查米游币任务会`米游币任务 - 讨论区签到: 服务器没有正确返回`，而手动命令触发任务却没问题，有头绪吗

不太确定，米游币任务是存在Bug的，应该手动和自动都无法完成。上一个版本显示的任务结果是米游币任务完成情况，从米游社获取的，不是本次执行情况，可能其实是自己已经在App签到过了

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/9df01717442f716765be81c00d0baadff887ef04/src/nonebot_plugin_mystool/myb_missions_api.py#L152

**Comment by Ljzd-PRO** [comment]
> > > > 目前米游币任务里的“讨论区签到”，暂时没有人机验证功能。
> > > 
> > > 
> > > 过段时间应该会加上
> > 
> > 
> > 自动检查米游币任务会`米游币任务 - 讨论区签到: 服务器没有正确返回`，而手动命令触发任务却没问题，有头绪吗
> 
> 不太确定，米游币任务是存在Bug的，应该手动和自动都无法完成。上一个版本显示的任务结果是米游币任务完成情况，从米游社获取的，不是本次执行情况，可能其实是自己已经在App签到过了
> 
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/9df01717442f716765be81c00d0baadff887ef04/src/nonebot_plugin_mystool/myb_missions_api.py#L152

这个就是 #173 的情况

**Comment by Ljzd-PRO** [comment]
其实在之前的版本就已经存在Bug，应当返回

```python
return MissionStatus(success=True), api_result.data["points"]
```

只是在新版本之前，机器人相关代码那边刚好也有Bug，刚好只解析了一项，没有把元组拆包，所以没遇到问题。

**Comment by dontdot** [comment]
> > > > 目前米游币任务里的“讨论区签到”，暂时没有人机验证功能。
> > > 
> > > 
> > > 过段时间应该会加上
> > 
> > 
> > 自动检查米游币任务会`米游币任务 - 讨论区签到: 服务器没有正确返回`，而手动命令触发任务却没问题，有头绪吗
> 
> 不太确定，米游币任务是存在Bug的，应该手动和自动都无法完成。上一个版本显示的任务结果是米游币任务完成情况，从米游社获取的，不是本次执行情况，可能其实是自己已经在App签到过了
> 
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/9df01717442f716765be81c00d0baadff887ef04/src/nonebot_plugin_mystool/myb_missions_api.py#L152

（新编辑）#173 我倒是没有他那里面这么复杂，单纯就是请求返回的内容没有`data`，所以导致失败。手动却有返回`data`。

其实如果说“自己已经在App签到过了”也很好验证才对，可以在米游币任务全部完成的情况下，手动输入`/任务`看下会不会出现`TypeError: 'NoneType' object is not subscriptable`这种情况，我有logger过在自动米游币任务下`api_result`的内容，我记得它是没有point这个键的，应该就是没有成功从米游社取得响应吧

**Comment by Ljzd-PRO** [comment]
是的，这个issue主要问题是返回码`-1034`，跟游戏签到不一样，这个讨论区签到是要通过另外两个API申请人机验证任务以及提交结果，然后再使用这个签到API

**Comment by beiji-O-o** [comment]
这个任务还是有时候会做不完，晚点我截图日志。即使手动/任务也是做不完。
