### ISSUE TITLE
打码显示成功，机器人提示签到失败

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#159]
![dd0c355c9778bc2b72caab427dcd5ae](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/ba73918c-f036-4730-b4a3-929f48353cc4)
<img width="1253" alt="屏幕截图 2023-08-09 090118" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/8f15205a-2c27-43e9-a1df-4cde561cba99">

**Comment by Ljzd-PRO** [comment]
#163
