### ISSUE TITLE
由于Cookie缺少login_ticket，无法继续，请稍后再试

### ISSUE THREAD

**Issue by IceCaitao** [Ljzd-PRO/nonebot-plugin-mystool#17]
![image](https://user-images.githubusercontent.com/112809708/188313450-92ea27ac-f104-4e9b-b101-e659b5a0b11c.png)

**Comment by Ljzd-PRO** [comment]
hmm，我刚才进行登录是没问题的，不会缺少login_ticket

**Comment by Ljzd-PRO** [comment]
验证码有在网页上使用了吗？获取到的验证码不能使用掉，不然再发给机器人，机器人得到的已经是失效的验证码了。
