### ISSUE TITLE
原神便笺小组件相关

### ISSUE THREAD

**Issue by dontdot** [Ljzd-PRO/nonebot-plugin-mystool#171]
```
08-18 09:26:02 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 09:26:02 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 09:26:04 [DEBUG] nonebot_plugin_mystool | 原神小组件:content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 86, 'max_resin': 160, 'resin_recovery_time': '35141', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5, 'expeditions': [{'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/ace0cba93ee5853ead588abeccf38728.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/a6d9337223cae80e51a5d82f89b99d54.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/5d22921656abadde828ffaf1b2253796.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/8b1f1a23ade6093374ce2fdaedecf9ec.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/41bf4a8d22074fddb2b40a41715ce059.png', 'status': 'Ongoing'}], 'current_home_coin': 2400, 'max_home_coin': 2400, 'has_signed': True, 'sign_url': 'https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501&utm_source=bbs&utm_medium=mys&utm_campaign=widget', 'home_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&mhypresentationstyle=fullscreen&bbs_auth_required=true&gid=2', 'note_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&bbs_auth_required=true#/ys/daily'}} data={'current_resin': 86, 'max_resin': 160, 'resin_recovery_time': '35141', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5, 'expeditions': [{'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/ace0cba93ee5853ead588abeccf38728.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/a6d9337223cae80e51a5d82f89b99d54.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/5d22921656abadde828ffaf1b2253796.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/8b1f1a23ade6093374ce2fdaedecf9ec.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/41bf4a8d22074fddb2b40a41715ce059.png', 'status': 'Ongoing'}], 'current_home_coin': 2400, 'max_home_coin': 2400, 'has_signed': True, 'sign_url': 'https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501&utm_source=bbs&utm_medium=mys&utm_campaign=widget', 'home_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&mhypresentationstyle=fullscreen&bbs_auth_required=true&gid=2', 'note_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&bbs_auth_required=true#/ys/daily'} message='OK' retcode=None
08-18 09:26:04 [INFO] nonebot_plugin_mystool | 原神实时便笺：账户 76454149 树脂:86,未满足推送条件
08-18 09:26:08 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:119,未满足推送条件
08-18 09:30:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 09:35:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 09:40:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 09:45:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 09:50:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 09:55:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 10:00:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 10:05:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 10:10:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 10:15:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 10:20:59 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 10:26:00 [DEBUG] nonebot_plugin_mys_api | Device id & fp refreshed
08-18 10:26:02 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 10:26:02 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 10:26:04 [DEBUG] nonebot_plugin_mystool | 原神小组件:content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 94, 'max_resin': 160, 'resin_recovery_time': '31541', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5, 'expeditions': [{'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/ace0cba93ee5853ead588abeccf38728.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/a6d9337223cae80e51a5d82f89b99d54.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/5d22921656abadde828ffaf1b2253796.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/8b1f1a23ade6093374ce2fdaedecf9ec.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/41bf4a8d22074fddb2b40a41715ce059.png', 'status': 'Ongoing'}], 'current_home_coin': 2400, 'max_home_coin': 2400, 'has_signed': True, 'sign_url': 'https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501&utm_source=bbs&utm_medium=mys&utm_campaign=widget', 'home_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&mhypresentationstyle=fullscreen&bbs_auth_required=true&gid=2', 'note_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&bbs_auth_required=true#/ys/daily'}} data={'current_resin': 94, 'max_resin': 160, 'resin_recovery_time': '31541', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5, 'expeditions': [{'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/ace0cba93ee5853ead588abeccf38728.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/a6d9337223cae80e51a5d82f89b99d54.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/5d22921656abadde828ffaf1b2253796.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/8b1f1a23ade6093374ce2fdaedecf9ec.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/41bf4a8d22074fddb2b40a41715ce059.png', 'status': 'Ongoing'}], 'current_home_coin': 2400, 'max_home_coin': 2400, 'has_signed': True, 'sign_url': 'https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501&utm_source=bbs&utm_medium=mys&utm_campaign=widget', 'home_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&mhypresentationstyle=fullscreen&bbs_auth_required=true&gid=2', 'note_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&bbs_auth_required=true#/ys/daily'} message='OK' retcode=None
08-18 10:26:09 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:129,未满足推送条件
```

```
if account.enable_resin or matcher:
            genshin_board_status, board = await genshin_board(account)
```
是不是board没获取到小组件的返回的conent导致10：26分那次原神便笺自动检查没有把下面的代码打印出来，9：26分是成功的
`logger.info(f"原神实时便笺：账户 {account.bbs_uid} 树脂:{board.current_resin},未满足推送条件")`

就是提问一下，没什么逻辑问题的话，我就关闭这个issue吧

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/9df01717442f716765be81c00d0baadff887ef04/src/nonebot_plugin_mystool/plan.py#L442-L448

有收到机器人的推送消息吗？如果有的话说明这里正常进行了判断，应该是提醒阈值设置的问题？
另外 `genshin_board(account)` 执行的时候如果服务器返回的结果为空，无法对 `class GenshinBoard(BaseMode ` 完成实例化也会报错，会提示服务器返回不正确。

**Comment by dontdot** [comment]
> 

没有收到机器人推送，因为我阈值设置的140
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/8b3c90160323fd57598a44f2e4d92731360da576/src/nonebot_plugin_mystool/plan.py#L380-L382
我另外在381行后面添加了`logger.info(f'原神便笺board：{board})`
下面是日志，可以看到board是有返回信息的，且树脂并没有超过设定阈值，但是却没有执行
`logger.info(f"原神实时便笺：账户 {account.bbs_uid} 树脂:{board.current_resin},未满足推送条件") `这个代码
```
08-18 13:55:56 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 13:55:56 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 13:55:58 [DEBUG] nonebot_plugin_mystool | 原神小组件:content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 120, 'max_resin': 160, 'resin_recovery_time': '18947', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5, 'expeditions': [{'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/ace0cba93ee5853ead588abeccf38728.png', 'status': 'Finished'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/a6d9337223cae80e51a5d82f89b99d54.png', 'status': 'Finished'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/5d22921656abadde828ffaf1b2253796.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/8b1f1a23ade6093374ce2fdaedecf9ec.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/41bf4a8d22074fddb2b40a41715ce059.png', 'status': 'Ongoing'}], 'current_home_coin': 2400, 'max_home_coin': 2400, 'has_signed': True, 'sign_url': 'https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501&utm_source=bbs&utm_medium=mys&utm_campaign=widget', 'home_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&mhypresentationstyle=fullscreen&bbs_auth_required=true&gid=2', 'note_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&bbs_auth_required=true#/ys/daily'}} data={'current_resin': 120, 'max_resin': 160, 'resin_recovery_time': '18947', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5, 'expeditions': [{'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/ace0cba93ee5853ead588abeccf38728.png', 'status': 'Finished'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/a6d9337223cae80e51a5d82f89b99d54.png', 'status': 'Finished'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/5d22921656abadde828ffaf1b2253796.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/8b1f1a23ade6093374ce2fdaedecf9ec.png', 'status': 'Ongoing'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u1490e/41bf4a8d22074fddb2b40a41715ce059.png', 'status': 'Ongoing'}], 'current_home_coin': 2400, 'max_home_coin': 2400, 'has_signed': True, 'sign_url': 'https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501&utm_source=bbs&utm_medium=mys&utm_campaign=widget', 'home_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&mhypresentationstyle=fullscreen&bbs_auth_required=true&gid=2', 'note_url': 'https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen&bbs_auth_required=true#/ys/daily'} message='OK' retcode=None
08-18 13:55:58 [INFO] nonebot_plugin_mystool | 原神便笺board：current_resin=120 finished_task_num=0 current_expedition_num=5 max_expedition_num=5 current_home_coin=2400 max_home_coin=2400 transformer=None resin_recovery_time=18947
```

**Comment by dontdot** [comment]
这里是比较全的日志内容，我按每次检查间隔隔断了，并对数据删减了一部分以容易观看，并且对
`logger.info(f"原神实时便笺：账户 {account.bbs_uid} 树脂:{board.current_resin},未满足推送条件") `成功执行部分进行加粗显示。
从下午开始可以看出来尽管board有返回内容，但是logger的执行并不是每次都成功
<details><summary>Details</summary>
<p>

08-18 07:16:49 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:97,未满足推送条件

08-18 08:14:47 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 08:14:47 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 08:16:47 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 08:16:47 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 08:16:53 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:107,未满足推送条件

08-18 09:26:02 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 09:26:02 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 09:26:04 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 86, 'max_resin': 160, 'resin_recovery_time': '35141', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None`
**08-18 09:26:04 [INFO] nonebot_plugin_mystool | 原神实时便笺：账户 76454149 树脂:86,未满足推送条件**
08-18 09:26:08 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:119,未满足推送条件

08-18 10:26:02 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 10:26:02 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 10:26:04 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 94, 'max_resin': 160, 'resin_recovery_time': '31541', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5,}  message='OK' retcode=None`
08-18 10:26:09 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:129,未满足推送条件


08-18 11:26:02 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 11:26:02 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 11:26:03 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 101, 'max_resin': 160, 'resin_recovery_time': '27942', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5} }message='OK' retcode=None`
08-18 11:26:08 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:139,未满足推送条件
08-18 13:26:06 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 116, 'max_resin': 160, 'resin_recovery_time': '20739', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None`

08-18 13:50:56 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 13:50:56 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 13:50:57 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 119, 'max_resin': 160, 'resin_recovery_time': '19248', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None`
08-18 13:50:57 [INFO] nonebot_plugin_mystool | 原神便笺board：`current_resin=119 finished_task_num=0 current_expedition_num=5 max_expedition_num=5 current_home_coin=2400 max_home_coin=2400 transformer=None resin_recovery_time=19248`
**08-18 13:50:57 [INFO] nonebot_plugin_mystool | 原神实时便笺：账户 76454149 树脂:119,未满足推送条件**

08-18 13:55:56 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 13:55:56 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 13:55:58 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 120, 'max_resin': 160, 'resin_recovery_time': '18947', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None`
08-18 13:55:58 [INFO] nonebot_plugin_mystool | 原神便笺board：`current_resin=120 finished_task_num=0 current_expedition_num=5 max_expedition_num=5 current_home_coin=2400 max_home_coin=2400 transformer=None resin_recovery_time=18947`

08-18 14:00:56 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 14:00:56 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 14:00:58 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 121, 'max_resin': 160, 'resin_recovery_time': '18647', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None`
08-18 14:00:58 [INFO] nonebot_plugin_mystool | 原神便笺board：`current_resin=121 finished_task_num=0 current_expedition_num=5 max_expedition_num=5 current_home_coin=2400 max_home_coin=2400 transformer=None resin_recovery_time=18647`

08-18 14:05:57 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-18 14:05:57 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-18 14:05:59 [DEBUG] nonebot_plugin_mystool | 原神小组件:`content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 121, 'max_resin': 160, 'resin_recovery_time': '18346', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5} }message='OK' retcode=None
08-18 14:05:59 [INFO] nonebot_plugin_mystool | 原神便笺board：current_resin=121 finished_task_num=0 current_expedition_num=5 max_expedition_num=5 current_home_coin=2400 max_home_coin=2400 transformer=None resin_recovery_time=18346`


</p>
</details>

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/9df01717442f716765be81c00d0baadff887ef04/src/nonebot_plugin_mystool/plan.py#L399-L448

可能是自动查询时，有其他项被标记为已经通知过了，所以函数直接返回了，下面的判断是否达到阈值什么的也就没有执行

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/173#issuecomment-1684602599

这里也提到一个问题，可能和 `has_checked` 有关

**Comment by dontdot** [comment]
`has_checked`在我这应该是没问题的，我有设置另一个`has_checked_sr`给崩铁使用，#173那种情况我测试过，大概是原神跟崩铁某个键交替了，原神便笺读取了崩铁的键类似的这中情况。
另外你刚刚提出的“有其他项被标记为已经通知过了”这个可能性我也不太确定，下面是我在8/19的一部分日志，可以看到基本又不会出现那种情况了（可能性：我有重新`nb run`过)
（感觉这个问题有点玄学，我想大概可以关闭这个issue了）
<details><summary>Details</summary>
<p>

08-19 01:12:34 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-19 01:12:34 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-19 01:12:36 [DEBUG] nonebot_plugin_mystool | 原神小组件:content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 19, 'max_resin': 160, 'resin_recovery_time': '67203', 'finished_task_num': 4, 'total_task_num': 4, 'is_extra_task_reward_received': True, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None
08-19 01:12:36 [INFO] nonebot_plugin_mystool | 📒原神数据：current_resin=19 finished_task_num=4 current_expedition_num=5 max_expedition_num=5 current_home_coin=30 max_home_coin=2400 transformer=None resin_recovery_time=67203
**08-19 01:12:36 [INFO] nonebot_plugin_mystool | 原神实时便笺：账户 76454149 树脂:19,未满足推送条件**


08-19 02:12:34 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-19 02:12:34 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-19 02:12:36 [DEBUG] nonebot_plugin_mystool | 原神小组件:content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 27, 'max_resin': 160, 'resin_recovery_time': '63603', 'finished_task_num': 4, 'total_task_num': 4, 'is_extra_task_reward_received': True, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None
08-19 02:12:36 [INFO] nonebot_plugin_mystool | 📒原神数据：current_resin=27 finished_task_num=4 current_expedition_num=5 max_expedition_num=5 current_home_coin=60 max_home_coin=2400 transformer=None resin_recovery_time=63603
**08-19 02:12:36 [INFO] nonebot_plugin_mystool | 原神实时便笺：账户 76454149 树脂:27,未满足推送条件**


08-19 03:12:35 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-19 03:12:35 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-19 03:12:37 [DEBUG] nonebot_plugin_mystool | 原神小组件:content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 34, 'max_resin': 160, 'resin_recovery_time': '60002', 'finished_task_num': 4, 'total_task_num': 4, 'is_extra_task_reward_received': True, 'current_expedition_num': 5, 'max_expedition_num': 5}} message='OK' retcode=None
08-19 03:12:37 [INFO] nonebot_plugin_mystool | 📒原神数据：current_resin=34 finished_task_num=4 current_expedition_num=5 max_expedition_num=5 current_home_coin=90 max_home_coin=2400 transformer=None resin_recovery_time=60002
**08-19 03:12:37 [INFO] nonebot_plugin_mystool | 原神实时便笺：账户 76454149 树脂:34,未满足推送条件**


08-19 04:12:34 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76454149 可能被验证码阻拦
08-19 04:12:34 [DEBUG] nonebot_plugin_mystool | 原神便笺，网络请求返回: {"data":null,"message":"","retcode":1034}
08-19 04:12:35 [DEBUG] nonebot_plugin_mystool | 原神小组件:content={'retcode': 0, 'message': 'OK', 'data': {'current_resin': 42, 'max_resin': 160, 'resin_recovery_time': '56404', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'current_expedition_num': 5, 'max_expedition_num': 5}}
08-19 04:12:36 [INFO] nonebot_plugin_mystool | 📒原神数据：current_resin=42 finished_task_num=0 current_expedition_num=5 max_expedition_num=5 current_home_coin=120 max_home_coin=2400 transformer=None resin_recovery_time=56404
**08-19 04:12:36 [INFO] nonebot_plugin_mystool | 原神实时便笺：账户 76454149 树脂:42,未满足推送条件**
08-19 04:12:42 [INFO] nonebot_plugin_mystool | 崩铁实时便笺：账户 76454149 开拓力:67,未满足推送条件

</p>
</details>
