### ISSUE TITLE
注册了geetest，但是那个url在哪里呢

### ISSUE THREAD

**Issue by Fins03** [Ljzd-PRO/nonebot-plugin-mystool#176]
还有填写文件的位置和大概内容，抱歉，第一次用人机验证

**Comment by Ljzd-PRO** [comment]
在 `data/nonebot-plugin-mystool/plugin_data.json` 里。

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Configuration-Preference#geetest_url

**Comment by Ljzd-PRO** [comment]
不是去注册极验，是要找能接极验人机验证的那种接码平台，一般是收费的。

**Comment by Fins03** [comment]
好的，谢谢
