### ISSUE TITLE
QQ频道下希望支持每日任务结果通知

### ISSUE THREAD

**Issue by WangQueXL** [Ljzd-PRO/nonebot-plugin-mystool#179]
目前在QQ频道每日任务执行完毕后并不会主动私信或者在子频道内发送主动消息通知执行结果，频道目前的主动私信，用户能够手动调整私信推送上限为50条一天，私域机器人子频道内的主动消息则是无限量，理论上应当是可以支撑起这个消息所需的数量，唯一的限制就是0-6时tx不允许推送主动消息，所以还是希望能够支持此功能❤️

**Comment by Ljzd-PRO** [comment]
最新版 v1.3.0 应该是会私信通知的，可能是用的之前的版本创建的用户数据，用户项下的`qq_guilds`缺少用户所在频道的ID，没法主动私信。
可以执行一次 `/私信响应` ，应该就会进行记录，之后应该就会主动私信通知。或者如果是绑定了QQ聊天的用户数据，可以解绑然后再次绑定。

**Comment by WangQueXL** [comment]
> 最新版 v1.3.0 应该是会私信通知的，可能是用的之前的版本创建的用户数据，用户项下的`qq_guilds`缺少用户所在频道的ID，没法主动私信。 可以执行一次 `/私信响应` ，应该就会进行记录，之后应该就会主动私信通知。或者如果是绑定了QQ聊天的用户数据，可以解绑然后再次绑定。

感谢，确实是因为使用了老版本配置的原因，当时1.2.0支持QQ频道的时候就果断转了过去，后面除了定期更新一下插件就没有动过它了
