### ISSUE TITLE
商品兑换是否异常？

### ISSUE THREAD

**Issue by YulinZhang6** [Ljzd-PRO/nonebot-plugin-mystool#183]
商品兑换可能有异常，命令行没有报错信息，兑换失败也没有主动发送消息
但是过期的兑换确实又自行推迟一周，很奇怪
图片上传貌似出了问题，只有文字描述了

**Comment by Ljzd-PRO** [comment]
兑换结果没有日志输出吗？

**Comment by YulinZhang6** [comment]
> 志

如果是指命令行的输出，应该是没有的。data插件路径下的日志也没有。

**Comment by Ljzd-PRO** [comment]
推迟一周执行的话，可能是商品兑换时间识别错了，把兑换项目开始时间和下一次开放兑换弄混了。

**Comment by YulinZhang6** [comment]
您的代码我没细看。具体情况我在描述详细点：我设定了8月23号19点兑换商品，但是当天没有机器人反馈兑换结果，日志也是没有的。随后查阅了兑换计划，发现自动调整到8月30日19点兑换同一件商品。结果今天是没有兑换的，计划再往后推迟一周

**Comment by Ljzd-PRO** [comment]
临时的解决方法是把插件数据文件里商品兑换计划里的商品信息的 `next_time` 和 `sale_start_time` 改为正确的兑换开始时间戳，网上有在线的时间戳转换工具
