### ISSUE TITLE
米游社任务完成不了（/任务也不行）

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#184]
![BBB59AB3-CBAF-4203-BC9A-239484EA92A0](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/2da3ba73-de9c-4ff1-9c59-439e9f1850fd)

**Comment by beiji-O-o** [comment]
<img width="754" alt="屏幕截图 2023-09-02 122713" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/b3c378c8-2424-4145-8911-10497bae9210">

只有点赞、分享不行

**Comment by dontdot** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/4980931a64e5ed48cee9d6206e169101c2cb9057/src/nonebot_plugin_mystool/myb_missions_api.py#L75
一个可能性，今天我用旧版本签过了（点赞和分享），新版没试
