### ISSUE TITLE
【崩坏：星穹铁道】添加不了兑换计划

### ISSUE THREAD

**Issue by story-x** [Ljzd-PRO/nonebot-plugin-mystool#185]
商品列表
![3078fb1520c4f41ccce2465173ef6a95](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/45375162/1660ecda-ece3-45c6-b749-19795ae779e2)

命令：mt兑换.+2023082311492
提示：该商品暂时不可以兑换，请重新设置
![bec8f4c5fd0c66c10b7becb07103c219](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/45375162/85de88c0-5db4-4515-ad2f-b77384b73bec)

log
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/45375162/94e03655-f428-448e-98ab-f9d430a46de6)

**Comment by story-x** [comment]
更新完添加 
mt兑换.+2023080811323（原神）
mt兑换.+2023082311492（崩坏：星穹铁道）
都报错下面截图
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/45375162/0efa58d0-f692-4fdd-ac59-f4ec17e8e2c8)

**Comment by Sakamakiiizayoi** [comment]
1.3.2 同上报错
