### ISSUE TITLE
关于商品信息图片的时间

### ISSUE THREAD

**Issue by Yinhaoran1128** [Ljzd-PRO/nonebot-plugin-mystool#189]
版本1.3.2更新后，兑换时间由以前显示的下一次开始的时间，变为了当前这一次开始的时间。
但是大部分兑换奖励都需要卡点抢，我并不需要知道当前这一次的开始时间，更希望知道下一次可以抢是什么时候。
我认为更新前的更合理，想请问一下作者大大的思路是怎样的。

**Comment by Ljzd-PRO** [comment]
应该还是兑换时间没弄清楚什么时候使用`next_time`什么时候使用`sale_start_time`。部分商品在更新前显示的兑换时间是迟了一周。似乎快要到兑换时间的时候，商品信息会发生变化，`next_time` 将变为下次开抢时间，也就是我们需要的；而如果距离兑换时间还有比较长的时间，`next_time` 将会是上次开抢时间，而真正下次开抢的时间将会是 `sale_start_time`，就是我们需要的时间。

**Comment by Yinhaoran1128** [comment]
那是不是可以假如`next_time`大于当前时间就显示`next_time`，小于就显示`sale_start_time`

**Comment by Ljzd-PRO** [comment]
确实可以，不过 大于当前时间的 时间 的最小值，会比较好，因为有时候这两个都在当前时间之后，其中一个是真正兑换时候，一个要迟一周

**Comment by Yinhaoran1128** [comment]
明白了，谢谢大佬！
