### ISSUE TITLE
请问绕过验证码那个该怎么填写参数

### ISSUE THREAD

**Issue by Ma1nt5iner** [Ljzd-PRO/nonebot-plugin-mystool#195]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/bfb38fab-98e6-43a3-a445-12d4718701f6)

**Comment by Ma1nt5iner** [comment]
大佬有空回复我嘛

**Comment by Ljzd-PRO** [comment]
要根据你用的那个打码平台的接口说明来写

**Comment by Ma1nt5iner** [comment]
> 要根据你用的那个打码平台的接口说明来写

就是套套 是在不知道该怎么填写

**Comment by Ma1nt5iner** [comment]
那个json不用填什么是吗

**Comment by Ma1nt5iner** [comment]
我添加url和key之后运行还是报错。。

**Comment by Ljzd-PRO** [comment]
发一下打码平台的说明

**Comment by Ma1nt5iner** [comment]
> 发一下打码平台的说明

https://www.kancloud.cn/ttorc/ttorc/3119241   这个大佬

**Comment by Ma1nt5iner** [comment]
大佬看见了吗

**Comment by Ma1nt5iner** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/256a5dd0-2ec9-4970-b355-4424f00072e9)
我是这么填的

**Comment by Ljzd-PRO** [comment]
根据 https://www.kancloud.cn/ttorc/ttorc/3119239 ，`geetest_param` 还缺 `itemid`，值可以是 `388`（参考 https://www.kancloud.cn/ttorc/ttorc/3119237 ）

**Comment by Ma1nt5iner** [comment]
好的好的 我试试

**Comment by Ma1nt5iner** [comment]
还是报错大佬

**Comment by Ma1nt5iner** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/59f4a27b-5058-42bc-b46d-918dd8832132)

**Comment by Ma1nt5iner** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/21d0561a-b0e2-44ca-9dc6-3d20e72f3318)

**Comment by Ma1nt5iner** [comment]
获取不到validate

**Comment by Sakamakiiizayoi** [comment]
你这个套套图像打码接口是分两步的 提交识别后需要再次用凭证获取识别结果 不能直接用在插件上 需要自己二次封装 我待会试试

**Comment by Sakamakiiizayoi** [comment]
> 获取不到validate

你这个套套图像打码是需要分两步的 提交识别后需要使用凭证再次获取识别结果 不能直接用在插件上 需要自己二次封装一个接口 我待会试试

**Comment by Ma1nt5iner** [comment]
> > 获取不到validate
> 
> 你这个套套图像打码是需要分两步的 提交识别后需要使用凭证再次获取识别结果 不能直接用在插件上 需要自己二次封装一个接口 我待会试试

好的好的大佬~！

**Comment by Ma1nt5iner** [comment]
我研究了研究，看起来挺难的

**Comment by Sakamakiiizayoi** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/345c643e-f0f8-44e0-95dc-fa4fff363059)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/57abb4ec-8d47-4acf-8ec8-34dba647e0bb)
代码是写好了 但是有问题 不知道是打码平台的原因还是什么原因 作者大大有成功打码过吗

**Comment by Sakamakiiizayoi** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/8564e531-496b-48c3-8c2c-ed15d8354bea)
啊这 加了个referer参数就识别成功了？  不知道啥情况哈哈

**Comment by Ma1nt5iner** [comment]
厉害！！！

**Comment by Sakamakiiizayoi** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/5f79f9a1-51cb-4350-ad34-f66b774c020a)

**Comment by Ma1nt5iner** [comment]
referer就是得加 加米游社签到的地址

**Comment by Ma1nt5iner** [comment]
芜湖！！教教我大佬

**Comment by Sakamakiiizayoi** [comment]
> 芜湖！！教教我大佬

代码再改改 我待会发出来 就是个简单的nodejs写的后端

**Comment by Ma1nt5iner** [comment]
> > 芜湖！！教教我大佬
> 
> 
> 
> 代码再改改 我待会发出来 就是个简单的nodejs写的后端

好的好的！

**Comment by Sakamakiiizayoi** [comment]
https://github.com/Sakamakiiizayoi/ttorc_auto
代码我发上来了
用法大概就是
1.安装nodejs
2.下载我的源代码解压到一个目录，记得修改一下server.js里的appkey
3.使用命令行工具切换到当前目录，运行npm i 安装好依赖后npm start 运行服务
4.mystool配置修改 把geetest_url指向服务 如图 （图中的ip地址填写自己的后端服务ip 若和机器人同机则可填http://127.0.0.1:3000/ttorc）
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/096c06e7-6dfc-4880-94c0-2184df888b3c)
params可以留空 因为在后端已经有appkey了

**Comment by Ma1nt5iner** [comment]
> https://github.com/Sakamakiiizayoi/ttorc_auto 代码我发上来了 用法大概就是 1.安装nodejs 2.下载我的源代码解压到一个目录，记得修改一下server.ts里的appkey 3.使用命令行工具切换到当前目录，运行npm i 安装好依赖后npm start 运行服务 4.mystool配置修改 把geetest_url指向服务 如图 ![image](https://user-images.githubusercontent.com/67581432/268174957-096c06e7-6dfc-4880-94c0-2184df888b3c.png) params可以留空 因为在后端已经有appkey了

好的大佬 我试一下

**Comment by Ma1nt5iner** [comment]
> https://github.com/Sakamakiiizayoi/ttorc_auto 代码我发上来了 用法大概就是 1.安装nodejs 2.下载我的源代码解压到一个目录，记得修改一下server.ts里的appkey 3.使用命令行工具切换到当前目录，运行npm i 安装好依赖后npm start 运行服务 4.mystool配置修改 把geetest_url指向服务 如图 ![image](https://user-images.githubusercontent.com/67581432/268174957-096c06e7-6dfc-4880-94c0-2184df888b3c.png) params可以留空 因为在后端已经有appkey了
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/e29d7836-b057-4971-97cf-72ef2861d014)
报错了

**Comment by Ma1nt5iner** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/e443646d-12c7-4344-94fc-d2189849d1cc)

**Comment by Sakamakiiizayoi** [comment]
我改成js吧 等一下

**Comment by Ma1nt5iner** [comment]
好像是nodejs版本太低的事情，typescript@5.2.2没有装上

**Comment by Sakamakiiizayoi** [comment]
https://github.com/Sakamakiiizayoi/ttorc_auto/tree/js
js版本分支

**Comment by Ma1nt5iner** [comment]
> 我改成js吧 等一下



> https://github.com/Sakamakiiizayoi/ttorc_auto/tree/js js版本分支

好的大佬 我再试试

**Comment by Ma1nt5iner** [comment]
步骤还是一样吗大佬

**Comment by Ma1nt5iner** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/8714d06b-e0c4-41d1-af29-0b8253f7a25d)

成功啦大佬

**Comment by Ma1nt5iner** [comment]
作者大大 为什么这个gt和challenge签到之后会自动改文件，但是不自动刷新。所以第二天就不能签到。。
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76150319/2dc901e4-9ebb-4f37-ab5a-f6fd75dd5df1)

**Comment by momlucky** [comment]
> https://github.com/Sakamakiiizayoi/ttorc_auto/tree/js js版本分支

大佬，快救救我！这个报错是为啥？自己倒腾了一个上午没弄明白
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/143769639/d621e7bf-ec94-4e49-8983-9601e39d8bc4)

**Comment by Sakamakiiizayoi** [comment]
> > https://github.com/Sakamakiiizayoi/ttorc_auto/tree/js js版本分支
> 
> 大佬，快救救我！这个报错是为啥？自己倒腾了一个上午没弄明白
> ![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/143769639/d621e7bf-ec94-4e49-8983-9601e39d8bc4)
> 

从你的图看来 mystool的打码请求并没有发送到我的后端 你检查一下geetesturl参数写对了没

**Comment by momlucky** [comment]
> > > https://github.com/Sakamakiiizayoi/ttorc_auto/tree/js js版本分支
> > 
> > 
> > 大佬，快救救我！这个报错是为啥？自己倒腾了一个上午没弄明白
> > ![image](https://user-images.githubusercontent.com/143769639/268428152-d621e7bf-ec94-4e49-8983-9601e39d8bc4.png)
> 
> 从你的图看来 mystool的打码请求并没有发送到我的后端 你检查一下geetesturl参数写对了没

是这样填写的不对吗？我按着你上面给得截图手动输入的
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/143769639/e76e3104-d193-4bcc-ad23-47b4696724d6)

**Comment by Sakamakiiizayoi** [comment]
啊这 你不能写我的ip呀 你得写你自己服务的ip 如果你的机器人和我的后端在同一台机子上的话这里填http://127.0.0.1:3000/ttorc

**Comment by momlucky** [comment]
> 啊这 你不能写我的ip呀 你得写你自己服务的ip 如果你的机器人和我的后端在同一台机子上的话这里填http://127.0.0.1:3000/ttorc

终于成功了，谢谢大佬，我太小白了，啥都不懂，麻烦啦！

**Comment by Ma1nt5iner** [comment]
为什么签到一次之后第二天就会报错呀。

**Comment by Sakamakiiizayoi** [comment]
> 为什么签到一次之后第二天就会报错呀。

插件有bug gt和challenge值不会改变 我已经提交issue了 。重启机器人可以暂时解决

**Comment by Ma1nt5iner** [comment]
> > 为什么签到一次之后第二天就会报错呀。
> 
> 插件有bug gt和challenge值不会改变 我已经提交issue了 。重启机器人可以暂时解决

我觉得应该也是。。我也是得重启

**Comment by dontdot** [comment]
有没有大佬试下这一段
```
    try:
        async for attempt in get_async_retry(retry):
            with attempt:
                pz_url = 'http://api.ttocr.com/api/recognize'
                async with httpx.AsyncClient() as client:   #获取识别凭证
                    ress = await client.post(
                        pz_url,
                        params=params,
                        json=content,
                        timeout=60
                    )
                geetest_predata = ress.json()
                if geetest_predata['status'] == 1:
                    resultid = geetest_predata['resultid']
                    sec_params = {'appkey':{params.appkey},'resultid':{resultid}}
                    async with httpx.AsyncClient() as client:   #获取识别结果
                        res = await client.post(
                            _conf.preference.geetest_url,
                            params=sec_params,
                            json=content,
                            timeout=60
                        )
                    geetest_data = res.json()
                    validate = geetest_data['data']['validate']
                    seccode = geetest_data['data'].get('seccode') or f"{validate}|jordan"
                    logger.debug(f"{_conf.preference.log_head}人机验证结果：{geetest_data}")
                    return GeetestResult(validate=validate, seccode=seccode)
                else:
                    logger.exception("获取平台查询凭证失败")
    except tenacity.RetryError:
        logger.exception(f"{_conf.preference.log_head}获取人机验证validate失败")
```
