### ISSUE TITLE
关于打码接口geetest_json参数固定不变的问题

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#196]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/b6f79503-d9f9-460f-9f34-aa176637e247)
识别成功过一次以后 gt，challenge值就不变了导致打码失败， 重启机器人后gt,challenge值就变化了 打码正常， 应该是有bug

**Comment by Sakamakiiizayoi** [comment]
看了一下源码和今天的日志 感觉有可能是讨论区签到人机验证没有提交成功导致的

**Comment by Ljzd-PRO** [comment]
插件数据文件中的 `geetest_json` 有被修改为固定的 gt 和 challenge 吗？可能是平台使用了JSON内容里的 gt 和 challenge，而不是URL参数里的。而目前确实有 `geetest_json` 被修改的Bug

**Comment by Sakamakiiizayoi** [comment]
"geetest_json": {
            "gt": "{gt}",
            "challenge": "{challenge}"
        },

我这边没有 还是正常的

**Comment by Sakamakiiizayoi** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/e19d7ff9-e2ce-4768-b026-875044fce156)
今天早上的自动任务，先执行了讨论区的签到 成功的获取到了validate 但是很奇怪的是没有下一步的动作，日志里啥也没有，貌似并没有提交人机验证，感觉是simpleapi里的verify_verification函数没有执行成功。加了几个logger明天看看是不是真的提交人机验证结果失败了。
还有就是这两天发现只要先进行游戏签到，打码成功签到后，再进行讨论区的签到，好像讨论区的签到就不会遇到验证码。

**Comment by Sakamakiiizayoi** [comment]
> ![image](https://user-images.githubusercontent.com/67581432/268935858-e19d7ff9-e2ce-4768-b026-875044fce156.png) 今天早上的自动任务，先执行了讨论区的签到 成功的获取到了validate 但是很奇怪的是没有下一步的动作，日志里啥也没有，貌似并没有提交人机验证，感觉是simpleapi里的verify_verification函数没有执行成功。加了几个logger明天看看是不是真的提交人机验证结果失败了。 还有就是这两天发现只要先进行游戏签到，打码成功签到后，再进行讨论区的签到，好像讨论区的签到就不会遇到验证码。

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/afdc76d0-00a6-4a30-afe8-0b350bd84684)
verify_verification函数确实返回失败，返回的数据是这样的。额，难道是用了loggerinfo的原因吗，明天用loggerdebug再看看
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/4f9a53c4-1cfd-4a49-8b61-05f5bd8dce2e)
<del>虽然函数返回失败，但是感觉其实是提交成功了，因为后续讨论区签到就不会有验证码了，至于为什么challenge值不变还是不清楚</del>

**Comment by Sakamakiiizayoi** [comment]
challenge值不变的原因找到了，就是dict对象浅拷贝的问题
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/134c77d2-20ee-49f4-a385-21473416ab1f)
这里改一下就可以了
