### ISSUE TITLE
QQ频道机器人，私信无反应

### ISSUE THREAD

**Issue by TomIsFat** [Ljzd-PRO/nonebot-plugin-mystool#210]
以下两段代码均handle到但是不回消息，测试过/echo，机器人可以回消息
```
11-06 22:45:49 [SUCCESS] nonebot | QQ XXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXX: [Text(type='text', data={'text': '/帮助'})]
11-06 22:45:49 [DEBUG] nonebot | Checking for matchers in priority 1...
11-06 22:45:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18)
11-06 22:45:49 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18)
11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_)
11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_) skipped
11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
11-06 22:45:49 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) running complete
11-06 22:45:49 [DEBUG] nonebot | Stop event propagation
11-06 22:45:49 [DEBUG] nonebot | Checking for matchers completed
```

```
11-06 23:20:34 [SUCCESS] nonebot | QQ XXXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXXX: [Text(type='text', data={'text': '/登录'})]
11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 1...
11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 4...
11-06 23:20:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25)
11-06 23:20:34 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25)
11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=handle_first_receive)
11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=handle_first_receive) skipped
11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
11-06 23:20:34 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) running complete
11-06 23:20:34 [DEBUG] nonebot | Stop event propagation
11-06 23:20:34 [DEBUG] nonebot | Checking for matchers completed
```

**Comment by Ljzd-PRO** [comment]
不太清楚，我这边是正常的。正常来说应该是没什么问题的，这也不是主动私聊

**Comment by byebaby** [comment]
> 以下两段代码均handle到但是不回消息，测试过/echo，机器人可以回消息
> 
> ```
> 11-06 22:45:49 [SUCCESS] nonebot | QQ XXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXX: [Text(type='text', data={'text': '/帮助'})]
> 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers in priority 1...
> 11-06 22:45:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18)
> 11-06 22:45:49 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18)
> 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_)
> 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_) skipped
> 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
> 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
> 11-06 22:45:49 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) running complete
> 11-06 22:45:49 [DEBUG] nonebot | Stop event propagation
> 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers completed
> ```
> 
> ```
> 11-06 23:20:34 [SUCCESS] nonebot | QQ XXXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXXX: [Text(type='text', data={'text': '/登录'})]
> 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 1...
> 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 4...
> 11-06 23:20:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25)
> 11-06 23:20:34 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25)
> 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=handle_first_receive)
> 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=handle_first_receive) skipped
> 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
> 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
> 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
> 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
> 11-06 23:20:34 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) running complete
> 11-06 23:20:34 [DEBUG] nonebot | Stop event propagation
> 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers completed
> ```



> 以下两段代码均handle到但是不回消息，测试过/echo，机器人可以回消息
> 
> ```
> 11-06 22:45:49 [SUCCESS] nonebot | QQ XXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXX: [Text(type='text', data={'text': '/帮助'})]
> 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers in priority 1...
> 11-06 22:45:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18)
> 11-06 22:45:49 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18)
> 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_)
> 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_) skipped
> 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
> 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
> 11-06 22:45:49 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) running complete
> 11-06 22:45:49 [DEBUG] nonebot | Stop event propagation
> 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers completed
> ```
> 
> ```
> 11-06 23:20:34 [SUCCESS] nonebot | QQ XXXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXXX: [Text(type='text', data={'text': '/登录'})]
> 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 1...
> 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 4...
> 11-06 23:20:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25)
> 11-06 23:20:34 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25)
> 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=handle_first_receive)
> 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=handle_first_receive) skipped
> 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
> 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
> 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
> 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped
> 11-06 23:20:34 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) running complete
> 11-06 23:20:34 [DEBUG] nonebot | Stop event propagation
> 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers completed
> ```

我也遇到了同样的问题，您后续有解决吗?

**Comment by TomIsFat** [comment]
没解决。我猜可能是QQ频道的适配器更新1.0.0版本后更改了某些规范，mys插件没适配。若是改用QQ频道适配器的0.3.0版本，也许可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月10日(周五) 上午9:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ljzd-PRO/nonebot-plugin-mystool] QQ频道机器人，私信无反应 (Issue #210)




  
以下两段代码均handle到但是不回消息，测试过/echo，机器人可以回消息
 11-06 22:45:49 [SUCCESS] nonebot | QQ XXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXX: [Text(type='text', data={'text': '/帮助'})] 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers in priority 1... 11-06 22:45:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) 11-06 22:45:49 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_) 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_) skipped 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped 11-06 22:45:49 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) running complete 11-06 22:45:49 [DEBUG] nonebot | Stop event propagation 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers completed  11-06 23:20:34 [SUCCESS] nonebot | QQ XXXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXXX: [Text(type='text', data={'text': '/登录'})] 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 1... 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 4... 11-06 23:20:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) 11-06 23:20:34 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=handle_first_receive) 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=handle_first_receive) skipped 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped 11-06 23:20:34 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) running complete 11-06 23:20:34 [DEBUG] nonebot | Stop event propagation 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers completed    
以下两段代码均handle到但是不回消息，测试过/echo，机器人可以回消息
 11-06 22:45:49 [SUCCESS] nonebot | QQ XXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXX: [Text(type='text', data={'text': '/帮助'})] 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers in priority 1... 11-06 22:45:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) 11-06 22:45:49 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_) 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_) skipped 11-06 22:45:49 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) 11-06 22:45:49 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped 11-06 22:45:49 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.help, lineno=18) running complete 11-06 22:45:49 [DEBUG] nonebot | Stop event propagation 11-06 22:45:49 [DEBUG] nonebot | Checking for matchers completed  11-06 23:20:34 [SUCCESS] nonebot | QQ XXXXXXXXX | [DIRECT_MESSAGE_CREATE]: Message XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from XXXXXXXXXXX: [Text(type='text', data={'text': '/登录'})] 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 1... 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers in priority 4... 11-06 23:20:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) 11-06 23:20:34 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=handle_first_receive) 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=handle_first_receive) skipped 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped 11-06 23:20:34 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) 11-06 23:20:34 [DEBUG] nonebot | Handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),)) skipped 11-06 23:20:34 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25) running complete 11-06 23:20:34 [DEBUG] nonebot | Stop event propagation 11-06 23:20:34 [DEBUG] nonebot | Checking for matchers completed   
我也遇到了同样的问题，您后续有解决吗?

**Comment by Ljzd-PRO** [comment]
原因即 #211 里那样。原本的 `nonebot-adapter-qqguild` 停止维护，迁移到了新的 `nonebot-adapter-qq`，现在新版本插件的依赖和导入已经改好了，nonebot机器人的配置仍然需要手动修改

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.4.0
