### ISSUE TITLE
adapter-QQGUILD 已经改成 adapter-QQ了,全新安装不了

### ISSUE THREAD

**Issue by magian1127** [Ljzd-PRO/nonebot-plugin-mystool#211]
nb adapter install nonebot-adapter-qqguild
找不到.

用 nb adapter install nonebot-adapter-qq 装了 mystool 也不起效果

**Comment by Ljzd-PRO** [comment]
之前的版本进入内置的虚拟环境（如果有配置了的话），用 `pip install nonebot-adapter-qqguild`，nonebot 配置则按照原QQGuild适配器的说明配置就可以装上使用。
不过现在插件已经更新了，用了新的 `nonebot-adapter-qq`，机器人也要按照新的说明进行配置。
