### ISSUE TITLE
签到一直被人机验证阻拦

### ISSUE THREAD

**Issue by Avegardero** [Ljzd-PRO/nonebot-plugin-mystool#214]
![000cb13ddaf88fea4c3ac0776275a1eb](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76992712/85c44628-860e-4a43-8a86-2ee53aadc358)
![{FE7650F6-B378-40fd-80AC-3D250793365D}](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/76992712/832db788-8dfe-4526-8799-13fc1f2a44f4)

**Comment by Ljzd-PRO** [comment]
到目前为止似乎没有观察到相同的问题，issue暂时关闭。
