### ISSUE TITLE
原神签到失败，返回活动已结束

### ISSUE THREAD

**Issue by SaYa-t** [Ljzd-PRO/nonebot-plugin-mystool#222]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/16526986/9077d67f-c87f-478b-9f6b-e21528925e08)
今天新出的问题，是不是米游社改actid了

**Comment by momlucky** [comment]
应该是，我换了好几个签到用的脚本，都是这样，之前好好的，今天突然原神就签不了了，但是星铁又没事，怪怪的

**Comment by Yinhaoran1128** [comment]
抓包看了一下, 改了好几个地方

- URL_REWARD, URL_INFO, URL_SIGN三项改为和其他分区一致了
- ACT_ID="e202311201442471"
- "Origin": "https://act.mihoyo.com"
- "Referer": "https://act.mihoyo.com/"
- 新增headers["x-rpc-signgame"] = 'hk4e'

全部改完之后就可以正常签到了

**Comment by Yinhaoran1128** [comment]
老米是喜欢整活的, 不知道为什么用的好好的东西突然要改....

**Comment by Yinhaoran1128** [comment]
抓包看了一下, 改了好几个地方

- URL_REWARD, URL_INFO, URL_SIGN三项改为和其他分区一致了
- ACT_ID="e202311201442471"
- "Origin": "https://act.mihoyo.com/"
- "Referer": "https://act.mihoyo.com/"
- 新增headers["x-rpc-signgame"] = 'hk4e'

全部改完之后就可以正常签到了
老米什么逆天操作, 用的好好的东西突然改掉了, 还特意把原神做的和其他分区不一样, 纯属吃饱了撑的()

**Comment by Yinhaoran1128** [comment]
更加迷惑的是其他分区如果使用headers["x-rpc-signgame"] = 'hk4e'将会报网络错误, 而使用令其等于任意其他值都不会报错

**Comment by Ljzd-PRO** [comment]
> 更加迷惑的是其他分区如果使用headers["x-rpc-signgame"] = 'hk4e'将会报网络错误, 而使用令其等于任意其他值都不会报错

hk4e 是原神的代号，Headers好像其他频道没有改。

**Comment by Yinhaoran1128** [comment]
签到调用的好像是HEADERS_API_TAKUMI_MOBILE, 不是HEADERS_REWARD

**Comment by SaYa-t** [comment]
#224 更新覆盖了部分文件的大小写调整

**Comment by TheTychoStar** [comment]
> 抓包看了一下, 改了好几个地方
> 
> * URL_REWARD, URL_INFO, URL_SIGN三项改为和其他分区一致了
> * ACT_ID="e202311201442471"
> * "Origin": "https://act.mihoyo.com/"
> * "Referer": "https://act.mihoyo.com/"
> * 新增headers["x-rpc-signgame"] = 'hk4e'
> 
> 全部改完之后就可以正常签到了 老米什么逆天操作, 用的好好的东西突然改掉了, 还特意把原神做的和其他分区不一样, 纯属吃饱了撑的()

感谢大佬，愁了两天不知道怎么搞，这下解决了。
顺便问一下android app抓包用什么工具啊？我之前也试着抓包，用的fiddler在PC上开代理，手机通过PC代理，手机上的chrome可以抓到，但是mys的APP就显示无法连接网络。

**Comment by Yinhaoran1128** [comment]
> > 抓包看了一下, 改了好几个地方
> > 
> > * URL_REWARD, URL_INFO, URL_SIGN三项改为和其他分区一致了
> > * ACT_ID="e202311201442471"
> > * "Origin": "https://act.mihoyo.com/"
> > * "Referer": "https://act.mihoyo.com/"
> > * 新增headers["x-rpc-signgame"] = 'hk4e'
> > 
> > 全部改完之后就可以正常签到了 老米什么逆天操作, 用的好好的东西突然改掉了, 还特意把原神做的和其他分区不一样, 纯属吃饱了撑的()
> 
> 感谢大佬，愁了两天不知道怎么搞，这下解决了。 顺便问一下android app抓包用什么工具啊？我之前也试着抓包，用的fiddler在PC上开代理，手机通过PC代理，手机上的chrome可以抓到，但是mys的APP就显示无法连接网络。

不是特别了解诶, 我ios用的stream, 你可以看看安卓有没有类似的

**Comment by Ljzd-PRO** [comment]
安卓抓包主要是证书信任不好搞，HTTPS抓包需要先信任证书，似乎从某个版本开始安卓App不信任用户证书，因此一个办法是把抓包工具的证书移动至系统证书目录，不过那样需要root。但好像也有别的方法

**Comment by NOWorEVER** [comment]
> 抓包看了一下, 改了好几个地方
> 
> - URL_REWARD, URL_INFO, URL_SIGN三项改为和其他分区一致了
> - ACT_ID="e202311201442471"
> - "Origin": "https://act.mihoyo.com/"
> - "Referer": "https://act.mihoyo.com/"
> - 新增headers["x-rpc-signgame"] = 'hk4e'
> 
> 全部改完之后就可以正常签到了
> 老米什么逆天操作, 用的好好的东西突然改掉了, 还特意把原神做的和其他分区不一样, 纯属吃饱了撑的()

好像星铁也改了，大佬能看看？

**Comment by Ljzd-PRO** [comment]
> > 抓包看了一下, 改了好几个地方
> > 
> > * URL_REWARD, URL_INFO, URL_SIGN三项改为和其他分区一致了
> > * ACT_ID="e202311201442471"
> > * "Origin": "https://act.mihoyo.com/"
> > * "Referer": "https://act.mihoyo.com/"
> > * 新增headers["x-rpc-signgame"] = 'hk4e'
> > 
> > 全部改完之后就可以正常签到了
> > 老米什么逆天操作, 用的好好的东西突然改掉了, 还特意把原神做的和其他分区不一样, 纯属吃饱了撑的()
> 
> 好像星铁也改了，大佬能看看？

刚刚抓包了一下发现`act_id`还是2023的，不过我没有账号没法测试铁道能不能签。

**Comment by NOWorEVER** [comment]
> > > 抓包看了一下, 改了好几个地方
> > > 
> > > * URL_REWARD, URL_INFO, URL_SIGN三项改为和其他分区一致了
> > > * ACT_ID="e202311201442471"
> > > * "Origin": "https://act.mihoyo.com/"
> > > * "Referer": "https://act.mihoyo.com/"
> > > * 新增headers["x-rpc-signgame"] = 'hk4e'
> > > 
> > > 全部改完之后就可以正常签到了
> > > 老米什么逆天操作, 用的好好的东西突然改掉了, 还特意把原神做的和其他分区不一样, 纯属吃饱了撑的()
> > 
> > 好像星铁也改了，大佬能看看？
> 
> 刚刚抓包了一下发现`act_id`还是2023的，不过我没有账号没法测试铁道能不能签。

好的，感谢。那应该是我的问题
