### ISSUE TITLE
qq官方适配器不响应

### ISSUE THREAD

**Issue by JaniQuiz** [Ljzd-PRO/nonebot-plugin-mystool#223]
我看说适配了官方的qq机器人，但我在使用的时候发现官方机器人的消息并没有响应，看了下日志显示跳过了消息处理，了解了一下说这种情况是不支持当前适配器的消息响应，跳过了消息处理，想问下是插件的qq官方适配器还没有做好吗？
注：使用的是官方的qq频道的机器人
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/115353272/78deb36a-c6ef-44cf-af32-f7ecdad727f4)

**Comment by Ljzd-PRO** [comment]
我这边是可以正常用的

**Comment by Ljzd-PRO** [comment]
跳过我也不太清楚，得对比成功的看看

**Comment by JaniQuiz** [comment]
我在网上找了一些其他插件类似的问题，基本原因好像都是插件没有适配对应的适配器
![网页捕获_1-12-2023_152954_github com](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/115353272/58810ceb-b939-4a37-96c8-2c83f1a1d9e9)

**Comment by JaniQuiz** [comment]
还有的说是事件类型不正确
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/115353272/1e6b1201-31d0-45ed-99f3-93f445abcc69)

**Comment by JaniQuiz** [comment]
解决了，我在消息类型中添加了一个MessageEvent类型后解决了，果然还是事件类型的问题
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/115353272/1ee73e9f-f317-48ec-9702-0ae9a33c6462)
