### ISSUE TITLE
能不能加一个超级账户能一次’/任务‘执行全部账户的米游社任务

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#238]

**Comment by Ljzd-PRO** [comment]
加上了。配置完管理员以后，用 `/任务 *`、`/签到 *` 就可以为所有用户执行，也可以为特定的用户执行。

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.4.4

**Comment by beiji-O-o** [comment]
> 加上了。配置完管理员以后，用 `/任务 *`、`/签到 *` 就可以为所有用户执行，也可以为特定的用户执行。
> 
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.4.4

好的！谢谢😁
