### ISSUE TITLE
每日实训提醒时间BUG

### ISSUE THREAD

**Issue by paxtonyu** [Ljzd-PRO/nonebot-plugin-mystool#243]
### 插件安装方式:  
`nb plugin install nonebot-plugin-mystool`

### BUG描述
会在每日凌晨4:16发布一条每日实训未完成的提醒
![Z DIYX %EABWDX6{{ G`QDQ](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/f9a882f8-a487-4a57-afac-e50ac7517769)

另有一个不知算不算bug, log里提示原神便签可能被验证码阻拦, 但使用  ''/原神便签''  命令可以正常获取原神便签
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/b24aa0f6-01fa-429a-8fb6-140a7ac82399)

**Comment by paxtonyu** [comment]
### 信息补充
应该是此段代码偶有判定失效的情况
```python
if not starrail_notice.current_train_score \
                            and _conf.preference.notice_time:  # 注意此处添加notice_time是为了防止每日首次推送通知在4:00后一段时间
```
不定时会出现这两个提醒, 我也搞不清楚了, 它不是每小时都触发, 不知道该咋改呜呜呜
![FK I3E7L{@)8EIEG5JQS2IK](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/a35354a5-ed06-4fe4-a5ef-befb64ea725f) ![QKYANPS}}{LUPYX G1NE 73](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/6c4ecac8-7252-4b67-ac52-4563ef376d4c)

**Comment by Ljzd-PRO** [comment]
应该是没打满所以进行了提醒吧，不过正常的话应该是通知一次，下次如果还是没有满就不通知。
我也不太了解星铁😂 可以问问 @Joseandluue

**Comment by dontdot** [comment]
> ### 信息补充
> 应该是此段代码偶有判定失效的情况
> ```python
> if not starrail_notice.current_train_score \
>                             and _conf.preference.notice_time:  # 注意此处添加notice_time是为了防止每日首次推送通知在4:00后一段时间
> ```
> 不定时会出现这两个提醒, 我也搞不清楚了, 它不是每小时都触发, 不知道该咋改呜呜呜
> ![FK I3E7L{@)8EIEG5JQS2IK](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/a35354a5-ed06-4fe4-a5ef-befb64ea725f) ![QKYANPS}}{LUPYX G1NE 73](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/6c4ecac8-7252-4b67-ac52-4563ef376d4c)
> 

每日实训是会通知两遍，第一遍在设置签到时间的1小时后，这是因为把每日实训通知逻辑改成`未完成才通知`导致的，不然按照原来的逻辑每日实训全部完成才通知明显不符合期望，你想让他每小时通知你一遍可以把_conf.preference.notice_time删掉

**Comment by dontdot** [comment]
> ### 部署时间: 2024-01-06
> 
> ### 插件安装方式:  
> `nb plugin install nonebot-plugin-mystool`
> 
> ### BUG描述
> 会在每日凌晨4:16发布一条每日实训未完成的提醒
> ![Z DIYX %EABWDX6{{ G`QDQ](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/f9a882f8-a487-4a57-afac-e50ac7517769)
> 
> 另有一个不知算不算bug, log里提示原神便签可能被验证码阻拦, 但使用  ''/原神便签''  命令可以正常获取原神便签
> ![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/b24aa0f6-01fa-429a-8fb6-140a7ac82399)

你这个4点发送通知是明显_conf.preference.notice_time没参与进行判断，就是帖子2楼发出来的那行代码，没有更多的信息没法判断出为什么_conf.preference.notice_time会失效。我自己也在用，目前并没有出现这个情况

**Comment by paxtonyu** [comment]
> > ### 部署时间: 2024-01-06
> > ### 插件安装方式:
> > `nb plugin install nonebot-plugin-mystool`
> > ### BUG描述
> > 会在每日凌晨4:16发布一条每日实训未完成的提醒
> > ![Z DIYX %EABWDX6{{ G`QDQ](https://private-user-images.githubusercontent.com/57837479/294741427-f9a882f8-a487-4a57-afac-e50ac7517769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE0MjctZjlhODgyZjgtYTQ4Ny00YTU3LWFmYWMtZTUwYWM3NTE3NzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Zjk3MzU1MGM2OGEyYmEyZWQxZDUzZjFlN2FmYjc3NDhlMjE0NTAwZDY4OTgwOWRmMjE3Y2RhMTg4ZDQ0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jK1rnEyanKMMirfYqqtV9UhxNLyszmADC8CMGMWBqM)
> > 另有一个不知算不算bug, log里提示原神便签可能被验证码阻拦, 但使用  ''/原神便签''  命令可以正常获取原神便签
> > ![image](https://private-user-images.githubusercontent.com/57837479/294741578-b24aa0f6-01fa-429a-8fb6-140a7ac82399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE1NzgtYjI0YWEwZjYtMDFmYS00MjlhLThmYjYtMTQwYTdhYzgyMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMDVhN2U0MzBkNmExNjU4NGMzOWM5OTgyNTRjNzA3YzUwNWU0Mzg3NmE1OTJjYTI3OTcxNzI2ZGU3ZDZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DjUSTmYAj3GO2xDXDy09yjjxs7xHBJIyfeLUyEjbjXE)
> 
> 你这个4点发送通知是明显_conf.preference.notice_time没参与进行判断，就是帖子2楼发出来的那行代码，没有更多的信息没法判断出为什么_conf.preference.notice_time会失效。我自己也在用，目前并没有出现这个情况

谢谢大佬解惑, 这个4点的通知是用脚手架部署的, 后边我又重新用源码部署了就没有4点的通知了, 只是还有点弄不明白为啥同样的判断逻辑, 为啥8:23的通知里没有模拟宇宙积分未打满的提醒.

**Comment by dontdot** [comment]
> > > ### 部署时间: 2024-01-06
> > > ### 插件安装方式:
> > > `nb plugin install nonebot-plugin-mystool`
> > > ### BUG描述
> > > 会在每日凌晨4:16发布一条每日实训未完成的提醒
> > > ![Z DIYX %EABWDX6{{ G`QDQ](https://private-user-images.githubusercontent.com/57837479/294741427-f9a882f8-a487-4a57-afac-e50ac7517769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE0MjctZjlhODgyZjgtYTQ4Ny00YTU3LWFmYWMtZTUwYWM3NTE3NzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Zjk3MzU1MGM2OGEyYmEyZWQxZDUzZjFlN2FmYjc3NDhlMjE0NTAwZDY4OTgwOWRmMjE3Y2RhMTg4ZDQ0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jK1rnEyanKMMirfYqqtV9UhxNLyszmADC8CMGMWBqM)
> > > 另有一个不知算不算bug, log里提示原神便签可能被验证码阻拦, 但使用  ''/原神便签''  命令可以正常获取原神便签
> > > ![image](https://private-user-images.githubusercontent.com/57837479/294741578-b24aa0f6-01fa-429a-8fb6-140a7ac82399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE1NzgtYjI0YWEwZjYtMDFmYS00MjlhLThmYjYtMTQwYTdhYzgyMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMDVhN2U0MzBkNmExNjU4NGMzOWM5OTgyNTRjNzA3YzUwNWU0Mzg3NmE1OTJjYTI3OTcxNzI2ZGU3ZDZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DjUSTmYAj3GO2xDXDy09yjjxs7xHBJIyfeLUyEjbjXE)
> > 
> > 你这个4点发送通知是明显_conf.preference.notice_time没参与进行判断，就是帖子2楼发出来的那行代码，没有更多的信息没法判断出为什么_conf.preference.notice_time会失效。我自己也在用，目前并没有出现这个情况
> 
> 谢谢大佬解惑, 这个4点的通知是用脚手架部署的, 后边我又重新用源码部署了就没有4点的通知了, 只是还有点弄不明白为啥同样的判断逻辑, 为啥8:23的通知里没有模拟宇宙积分未打满的提醒.

因为模拟宇宙是每周任务，他在周一进行一次通知后就储存了已经通知过的信息，所以后面就没再提醒了，这个确实不妥，后面我再优化提交个pr改善吧，期望是每日通知一次？

**Comment by paxtonyu** [comment]
> > > > ### 部署时间: 2024-01-06
> > > > ### 插件安装方式:
> > > > `nb plugin install nonebot-plugin-mystool`
> > > > ### BUG描述
> > > > 会在每日凌晨4:16发布一条每日实训未完成的提醒
> > > > ![Z DIYX %EABWDX6{{ G`QDQ](https://private-user-images.githubusercontent.com/57837479/294741427-f9a882f8-a487-4a57-afac-e50ac7517769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE0MjctZjlhODgyZjgtYTQ4Ny00YTU3LWFmYWMtZTUwYWM3NTE3NzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Zjk3MzU1MGM2OGEyYmEyZWQxZDUzZjFlN2FmYjc3NDhlMjE0NTAwZDY4OTgwOWRmMjE3Y2RhMTg4ZDQ0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jK1rnEyanKMMirfYqqtV9UhxNLyszmADC8CMGMWBqM)
> > > > 另有一个不知算不算bug, log里提示原神便签可能被验证码阻拦, 但使用  ''/原神便签''  命令可以正常获取原神便签
> > > > ![image](https://private-user-images.githubusercontent.com/57837479/294741578-b24aa0f6-01fa-429a-8fb6-140a7ac82399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE1NzgtYjI0YWEwZjYtMDFmYS00MjlhLThmYjYtMTQwYTdhYzgyMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMDVhN2U0MzBkNmExNjU4NGMzOWM5OTgyNTRjNzA3YzUwNWU0Mzg3NmE1OTJjYTI3OTcxNzI2ZGU3ZDZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DjUSTmYAj3GO2xDXDy09yjjxs7xHBJIyfeLUyEjbjXE)
> > > 
> > > 
> > > 你这个4点发送通知是明显_conf.preference.notice_time没参与进行判断，就是帖子2楼发出来的那行代码，没有更多的信息没法判断出为什么_conf.preference.notice_time会失效。我自己也在用，目前并没有出现这个情况
> > 
> > 
> > 谢谢大佬解惑, 这个4点的通知是用脚手架部署的, 后边我又重新用源码部署了就没有4点的通知了, 只是还有点弄不明白为啥同样的判断逻辑, 为啥8:23的通知里没有模拟宇宙积分未打满的提醒.
> 
> 因为模拟宇宙是每周任务，他在周一进行一次通知后就储存了已经通知过的信息，所以后面就没再提醒了，这个确实不妥，后面我再优化提交个pr改善吧，期望是每日通知一次？

了解了, 谢谢大佬. 通知的话, 每日委托我觉得可以弄一个自定义提醒时间, 比如晚上10点发现你还没做每日再推送每日委托未完成通知, 模拟宇宙同理可以设置为周六了发现你还没打完模拟宇宙, 这时候再通知, 感觉这样可以有效减少无用推送

**Comment by dontdot** [comment]
> > > > > ### 部署时间: 2024-01-06
> > > > > ### 插件安装方式:
> > > > > `nb plugin install nonebot-plugin-mystool`
> > > > > ### BUG描述
> > > > > 会在每日凌晨4:16发布一条每日实训未完成的提醒
> > > > > ![Z DIYX %EABWDX6{{ G`QDQ](https://private-user-images.githubusercontent.com/57837479/294741427-f9a882f8-a487-4a57-afac-e50ac7517769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE0MjctZjlhODgyZjgtYTQ4Ny00YTU3LWFmYWMtZTUwYWM3NTE3NzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Zjk3MzU1MGM2OGEyYmEyZWQxZDUzZjFlN2FmYjc3NDhlMjE0NTAwZDY4OTgwOWRmMjE3Y2RhMTg4ZDQ0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jK1rnEyanKMMirfYqqtV9UhxNLyszmADC8CMGMWBqM)
> > > > > 另有一个不知算不算bug, log里提示原神便签可能被验证码阻拦, 但使用  ''/原神便签''  命令可以正常获取原神便签
> > > > > ![image](https://private-user-images.githubusercontent.com/57837479/294741578-b24aa0f6-01fa-429a-8fb6-140a7ac82399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODMwOTYsIm5iZiI6MTcwNDc4Mjc5NiwicGF0aCI6Ii81NzgzNzQ3OS8yOTQ3NDE1NzgtYjI0YWEwZjYtMDFmYS00MjlhLThmYjYtMTQwYTdhYzgyMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMDVhN2U0MzBkNmExNjU4NGMzOWM5OTgyNTRjNzA3YzUwNWU0Mzg3NmE1OTJjYTI3OTcxNzI2ZGU3ZDZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DjUSTmYAj3GO2xDXDy09yjjxs7xHBJIyfeLUyEjbjXE)
> > > > 
> > > > 
> > > > 你这个4点发送通知是明显_conf.preference.notice_time没参与进行判断，就是帖子2楼发出来的那行代码，没有更多的信息没法判断出为什么_conf.preference.notice_time会失效。我自己也在用，目前并没有出现这个情况
> > > 
> > > 
> > > 谢谢大佬解惑, 这个4点的通知是用脚手架部署的, 后边我又重新用源码部署了就没有4点的通知了, 只是还有点弄不明白为啥同样的判断逻辑, 为啥8:23的通知里没有模拟宇宙积分未打满的提醒.
> > 
> > 因为模拟宇宙是每周任务，他在周一进行一次通知后就储存了已经通知过的信息，所以后面就没再提醒了，这个确实不妥，后面我再优化提交个pr改善吧，期望是每日通知一次？
> 
> 了解了, 谢谢大佬. 通知的话, 每日委托我觉得可以弄一个自定义提醒时间, 比如晚上10点发现你还没做每日再推送每日委托未完成通知, 模拟宇宙同理可以设置为周六了发现你还没打完模拟宇宙, 这时候再通知, 感觉这样可以有效减少无用推送

有考虑过，这个跟便笺检查的间隔时间相关，但是我想每日实训这里的功能跟溢出提醒的意义是有部分重叠，并且不确定每个使用脚本的人都需要，所以就不改了，按照原版每天到溢出提醒就结束了
