### ISSUE TITLE
似乎不能直接使用2.0版本,而是需要从1.0+迁移？

### ISSUE THREAD

**Issue by StarCode000** [Ljzd-PRO/nonebot-plugin-mystool#250]
如题,我尝试了直接安装v2.0,但是一直无法创建data文件夹,换了1.4.4版本就完全没问题
保留1.4.4版本创建的data文件夹,然后迁移到2.0.0版本也不会出问题,但是把data文件夹删了就寄了

**Comment by StarCode000** [comment]
![Picture_2024-01-29_18-39-39](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/59649631/ba7134aa-bef3-4abf-8b1d-23c4a3d94b11)
用的是Windows server 2012,但是win11上同样报错说找不到配置文件,而且也没有主动创建目录

**Comment by Ljzd-PRO** [comment]
确实不会主动创建data目录
