### ISSUE TITLE
ImportError: cannot import name "Logger" from "loguru"

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#251]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/26947787-8bdc-49e6-85a1-7c34e54aefb7)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/2c49b05d-3842-48c6-861a-51c798adcd26)

**Comment by Ljzd-PRO** [comment]
是哪个版本呢

**Comment by beiji-O-o** [comment]
> 2.0.1
> 
> > 是哪个版本呢

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/860ceccd-8ac0-429b-af36-0fd2e7baccf0)


> 是哪个版本呢

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/b25b5804-9e74-4699-bf96-cc238743a9bb)

**Comment by beiji-O-o** [comment]
> 是哪个版本呢

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/4b749bd6-1696-4229-8df0-3dfb2f1128df)

**Comment by Ljzd-PRO** [comment]
好像是分支合并的时候搞错了😂 好多更改都没合进去

**Comment by beiji-O-o** [comment]
> 好像是分支合并的时候搞错了😂 好多更改都没合进去

😂好吧

**Comment by Ljzd-PRO** [comment]
新的 v2.1.0 应该修复了

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v2.1.0
