### ISSUE TITLE
为什么提示请登陆。

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#252]
![6eee5bd0c239544259fcd07a79c5227](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/77bde7b6-e230-46f2-a116-facfa1490625)

**Comment by Ljzd-PRO** [comment]
日志有异常吗

**Comment by beiji-O-o** [comment]
> 日志有异常吗

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/84fe0b7b-8a4e-453d-94b5-7cb240f0cbd0)

**Comment by Ljzd-PRO** [comment]
上面那些是每日任务自动推送的吗？

**Comment by beiji-O-o** [comment]
> 上面那些是每日任务自动推送的吗？

不是
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/152a6c10-41b2-48ff-be73-fb1269a827d9)

**Comment by Ljzd-PRO** [comment]
v2版本的配置文件和数据文件v1用不了。如果之前一直用的是v1的话，升级到v2的时候插件数据文件有备份，会在后面加个.bak，想再用的话去掉.bak就可以

**Comment by Ljzd-PRO** [comment]
可以看一下`data/nonebot-plugin-mystool`目录，v1的话用的是`plugin_data.json`文件，v2是`dataV2.json`、`configV2.json`

**Comment by beiji-O-o** [comment]
> 可以看一下`data/nonebot-plugin-mystool`目录，v1的话用的是`plugin_data.json`文件，v2是`dataV2.json`、`configV2.json`

好了可以了 谢谢，configV2.json是默认使用旧的、dataV2.json是默认使用新的😂
