### ISSUE TITLE
崩铁更新后获取实时便笺失败

### ISSUE THREAD

**Issue by paxtonyu** [Ljzd-PRO/nonebot-plugin-mystool#256]
### 今天上午10点开始崩铁的便签不行了
- 是不是因为崩铁大版本更新api换了呢?
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/3e81bf85-c62e-490b-94ae-3314fa53bcfe)

**Comment by Ljzd-PRO** [comment]
有服务器返回的原始内容的日志输出吗？

**Comment by paxtonyu** [comment]
> 有服务器返回的原始内容的日志输出吗？

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/5e88f7dc-692a-4b4b-9ce6-4b08eef099e8)

但神奇的是今天中午一点开始又好了, 现在又可以正常获取铁道便签了, 有点难绷, 我把issue关了吧

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/57837479/38ec18b4-4140-47be-a322-c780ac4854f8)

**Comment by paxtonyu** [comment]
已解决
