### ISSUE TITLE
商品图片生成失败

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#257]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/d35547de-b339-4339-ad75-9826e366d662)
![b36ea928f8f1dcaf6124724bd5d4269](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/b33cc645-7aba-4f11-bcb8-66f40ebaede1)

**Comment by Ljzd-PRO** [comment]
目前商品图片生成确实有点问题

**Comment by Ljzd-PRO** [comment]
有点奇怪，这好像是生成了商品图片但是发出来的是空的？可以检查一下 `data/nonebot-plugin-mystool` 目录下有没有商品图片。hk4e 是原神的号码。

**Comment by Ljzd-PRO** [comment]
试了一下是可以正常生成并发送。部分分区没有可能是因为可兑换的商品不是限时的

**Comment by beiji-O-o** [comment]
我这都是机器人回复的都是空白的> 试了一下是可以正常生成并发送。部分分区没有可能是因为可兑换的商品不是限时的

**Comment by beiji-O-o** [comment]
> 试了一下是可以正常生成并发送。部分分区没有可能是因为可兑换的商品不是限时的

我这机器人回复都是空白的

**Comment by beiji-O-o** [comment]
> 号码。

有这个，后台生成的图片是没问题的，我下载下来也是新的，就是机器人发出来是空白的。

**Comment by Ljzd-PRO** [comment]
看起来和 #293 一个情况
