### ISSUE TITLE
OneBotV11 私信发送失败

### ISSUE THREAD

**Issue by dontdot** [Ljzd-PRO/nonebot-plugin-mystool#260]
现在不能直接发消息到qq私聊吗？不是qq频道的那个私信

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/f74dcb58-8a70-46eb-b504-6d00d034d703)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/d3ef4de9-bfaa-4962-a6cb-3669cd6c8d06)

**Comment by dontdot** [comment]
我填的是qq聊天用的qq号，结果匹配到了频道而不是qq聊天
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/3773ebd30444e1e14231a04be123b2d8affa09b0/src/nonebot_plugin_mystool/utils/common.py#L360-L366
这里下面我加个`logger.info (f"bot:{bots}")`
日志返回
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/a3a4187d-2437-43bb-a8ab-7b9cdb0b0706)

**Comment by Ljzd-PRO** [comment]
可能是369这行判断错了

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/0ea58355f6a6d6198e024bcdad00eaa89fcc60cd/src/nonebot_plugin_mystool/utils/common.py#L368-L383

**Comment by dontdot** [comment]
> 我填的是qq聊天用的qq号，结果匹配到了频道而不是qq聊天
> 
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/3773ebd30444e1e14231a04be123b2d8affa09b0/src/nonebot_plugin_mystool/utils/common.py#L360-L366
> 
> 
> 这里下面我加个`logger.info (f"bot:{bots}")`
> 日志返回
> ![image](https://private-user-images.githubusercontent.com/55482264/307515123-a3a4187d-2437-43bb-a8ab-7b9cdb0b0706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTkzMTQsIm5iZiI6MTcwODkxOTAxNCwicGF0aCI6Ii81NTQ4MjI2NC8zMDc1MTUxMjMtYTNhNDE4N2QtMjQzNy00M2JiLWE4YWItN2I5Y2RiMGIwNzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzNDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NDkwMmE5NzU2NDUzOGNkMGI4YzE0ZGNhNmY3NDY2YzE1NzQ1MzU3MDZjM2QwZDYzYzhjY2JhN2ZjMWZmNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cQKE94b57KBl87Tj0WM2ryLUEbgD8WaGoKeybJS-CYI)

我想问下这里日志返回的`bot:dict_values([Bot(type='OneBot V11', self_id='3643397381')])`是不是用`Bot(type='OneBot V11'`里的`Bot`进行判断？

**Comment by Ljzd-PRO** [comment]
对，试一下改成
```python3
if isinstance(use, OneBotV11Bot):
```
onebotv11继承了nonebot的`Bot`类

**Comment by dontdot** [comment]
改的369这行
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/479e829c-1976-4caf-be7e-b97727a6536d)

**Comment by Joseandluue** [comment]
改的369这行
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/d0b20b71-055c-42b3-b3ef-c35451d6ec6c)

**Comment by Ljzd-PRO** [comment]
确实有问题，应该要对`bots`进行判断，而不是对`use`
