### ISSUE TITLE
搭配ComWeChatBotClient使用后遇到的问题[私信发送失败]

### ISSUE THREAD

**Issue by frg666** [Ljzd-PRO/nonebot-plugin-mystool#264]
```python
    if isinstance(use, (OneBotV11Bot, QQGuildBot)):
        bots = [use]
    elif isinstance(use, (OneBotV11Adapter, QQGuildAdapter)):
        bots = use.bots.values()
    elif isinstance(use, OneBotV12Adapter):
        bots = use.bots.values()
    elif isinstance(use, OneBotV12Bot):
        bots = [use]
    else:
        bots = nonebot.get_bots().values()
    logger.info(f"bot:{bots}")
    # 获取 PlatformTarget 对象
    if isinstance(use, (OneBotV11Bot, OneBotV11Adapter)):
        target = TargetQQPrivate(user_id=user_id_int)
        logger.info(f"{plugin_config.preference.log_head}向用户 {user_id} 发送 QQ 聊天私信 user_id: {user_id_int}")
    elif isinstance(use, (OneBotV12Bot, OneBotV12Adapter)):
        target = TargetOB12Unknow(platform="wechat", detail_type="private", user_id=user_id)
        logger.info(f"{plugin_config.preference.log_head}向用户 {user_id} 发送 微信 聊天私信 user_id: {user_id_int}")
    else:
        if guild_id is None:
            if user := PluginDataManager.plugin_data.users.get(user_id):
                if not (guild_id := user.qq_guild.get(user_id)):
                    logger.error(f"{plugin_config.preference.log_head}用户 {user_id} 数据中没有任何频道ID")
                    return False, None
            else:
                logger.error(f"{plugin_config.preference.log_head}用户数据中不存在用户 {user_id}，无法获取频道ID")
                return False, None
        target = TargetQQGuildDirect(recipient_id=user_id_int, source_guild_id=guild_id)
        logger.info(f"{plugin_config.preference.log_head}向用户 {user_id} 发送 QQ 频道私信"
                    f" recipient_id: {user_id_int}, source_guild_id: {guild_id}")
```

请教一下，是我改的有问题吗？推送消息的时候一直匹配到QQ频道那块

**Comment by Ljzd-PRO** [comment]
和 #260 应该是一样的问题

**Comment by frg666** [comment]
> 和 #260 应该是一样的问题

好的，看完之后就明白了，我现在把判断全注释了，指定成了
```python
target = TargetOB12Unknow(platform="wechat", detail_type="private", user_id=user_id)
``` 
能用

**Comment by dontdot** [comment]
> > 和 #260 应该是一样的问题
> 
> 好的，看完之后就明白了，我现在把判断全注释了，指定成了
> 
> ```python
> target = TargetOB12Unknow(platform="wechat", detail_type="private", user_id=user_id)
> ```
> 
> 能用

用wechat不会被封账号吗，我用obv11的ntchat被封过一次

**Comment by frg666** [comment]
> > > 和 #260 应该是一样的问题
> > 
> > 
> > 好的，看完之后就明白了，我现在把判断全注释了，指定成了
> > ```python
> > target = TargetOB12Unknow(platform="wechat", detail_type="private", user_id=user_id)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 能用
> 
> 用wechat不会被封账号吗，我用obv11的ntchat被封过一次

不知道，我没有

**Comment by frg666** [comment]
> > > 和 #260 应该是一样的问题
> > 
> > 
> > 好的，看完之后就明白了，我现在把判断全注释了，指定成了
> > ```python
> > target = TargetOB12Unknow(platform="wechat", detail_type="private", user_id=user_id)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 能用
> 
> 用wechat不会被封账号吗，我用obv11的ntchat被封过一次

好，被封了（

**Comment by frg666** [comment]
> > > 和 [#260](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/260) 应该是一样的问题
> > 
> > 
> > 好的，看完之后就明白了，我现在把判断全注释了，指定成了
> > target = TargetOB12Unknow(platform="wechat", detail_type="private", user_id=user_id)
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 能用
> 
> 用wechat不会被封账号吗，我用obv11的ntchat被封过一次

很久没用了，但是当时没有出现封号的问题，被封经过排查是因为使用了xposed模块导致的
