### ISSUE TITLE
能否把签到单独分离出来一个单独的文件

### ISSUE THREAD

**Issue by hggg666** [Ljzd-PRO/nonebot-plugin-mystool#265]
如题，把签到功能分离出来，只需要展示本次签到结果即可，因为目前在用的另外一个签到工具（ https://github.com/Womsxd/MihoyoBBSTools ）不能获取此种签到奖励
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/73808774/4c6549cd-b796-45b1-bb5a-5b489cc69466)

**Comment by Ljzd-PRO** [comment]
使用 `/签到` 命令就会执行这种游戏签到，米游社讨论区签到是在 `/任务` 里。
不需要执行米游币任务的话，可以通过 `/账号设置` 命令关闭每日自动执行的米游币任务计划

**Comment by hggg666** [comment]
啊不是，我的意思是能否把这个签到功能分离成一个单独的py文件，我想自己改下脚本读我自己的ck在我的脚本面板上定时跑（装qq机器人这种太麻烦了也不能自动签到）

**Comment by linbeyoung** [comment]
> 啊不是，我的意思是能否把这个签到功能分离成一个单独的py文件，我想自己改下脚本读我自己的ck在我的脚本面板上定时跑（装qq机器人这种太麻烦了也不能自动签到）

+ 1

**Comment by Ljzd-PRO** [comment]
> 啊不是，我的意思是能否把这个签到功能分离成一个单独的py文件，我想自己改下脚本读我自己的ck在我的脚本面板上定时跑（装qq机器人这种太麻烦了也不能自动签到）

拆分出来的话可能有点麻烦，因为还带有机器人命令还有配置参数之类的。不过可以自己试一下拆分出来，~~核心代码是在这里~~

**Comment by Ljzd-PRO** [comment]
主要是在这个文件里：
`src/nonebot_plugin_mystool/api/game_sign_api.py`

https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/stable/src/nonebot_plugin_mystool/api/game_sign_api.py

**Comment by hggg666** [comment]
是我猪鼻了，配置文件里有配置的，不过那个面板签到还是失败了，提示如图，不知道大佬你这边是否会出现这种报错 
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/73808774/a5cc2b9f-62be-45ba-b619-a33848e3c4f6)

**Comment by Ljzd-PRO** [comment]
> 是我猪鼻了，配置文件里有配置的，不过那个面板签到还是失败了，提示如图，不知道大佬你这边是否会出现这种报错
> ![image](https://private-user-images.githubusercontent.com/73808774/312394341-a5cc2b9f-62be-45ba-b619-a33848e3c4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTEyMzYsIm5iZiI6MTcxMDM1MDkzNiwicGF0aCI6Ii83MzgwODc3NC8zMTIzOTQzNDEtYTVjYzJiOWYtNjJiZS00NWJhLWI2MTktYTMzODQ4ZTNjNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE3Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNmI1ZjAwZGFmMzY2YjEzMDA3MzY2ZWI3ZDA3YmQ1N2IwNjhmNGM1ZjI4NGJiNzhhZDFmMDkzOTdiMzk4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQRJSRMNz_SYeIFWV133sh4dqUkRnDfIEUiS4EmgUxY)

我们插件的话刚才我试了一下是可以签的，游戏签到和讨论区签到都可以。不过偶尔会遇到人机验证，需要配置打码平台，或者就手动签。Cookie失效的话，Cookie你是怎么获取的？

**Comment by hggg666** [comment]
> > 是我猪鼻了，配置文件里有配置的，不过那个面板签到还是失败了，提示如图，不知道大佬你这边是否会出现这种报错
> > ![image](https://private-user-images.githubusercontent.com/73808774/312394341-a5cc2b9f-62be-45ba-b619-a33848e3c4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTEyMzYsIm5iZiI6MTcxMDM1MDkzNiwicGF0aCI6Ii83MzgwODc3NC8zMTIzOTQzNDEtYTVjYzJiOWYtNjJiZS00NWJhLWI2MTktYTMzODQ4ZTNjNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE3Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNmI1ZjAwZGFmMzY2YjEzMDA3MzY2ZWI3ZDA3YmQ1N2IwNjhmNGM1ZjI4NGJiNzhhZDFmMDkzOTdiMzk4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQRJSRMNz_SYeIFWV133sh4dqUkRnDfIEUiS4EmgUxY)
> 
> 我们插件的话刚才我试了一下是可以签的，游戏签到和讨论区签到都可以。不过偶尔会遇到人机验证，需要配置打码平台，或者就手动签。Cookie失效的话，Cookie你是怎么获取的？

有点难绷，讨论区签到可以，游戏签到不行，可能是太久之前抓的ck不行了，我周末再试下抓个新ck试试（另外讨论区签到其实也会遇到人机验证，我最近接了打码平台可以通过验证）
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/73808774/36523d64-edb2-453a-a93c-f2301fc7cc11)
