### ISSUE TITLE
跪求真寻移植版

### ISSUE THREAD

**Issue by ayakasuki** [Ljzd-PRO/nonebot-plugin-mystool#27]
真寻也是基于nonebot的机器人来着

**Comment by Ljzd-PRO** [comment]
可以试一下能不能用，应该是兼容的

**Comment by ayakasuki** [comment]
不行欸 加载成功 但是后面报错'str' object has no attribute 'get' 
![image](https://user-images.githubusercontent.com/20859971/190608329-686008ae-722c-41b9-884a-7d3a9627ce79.png)

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/190617135-7750e2f4-d4f6-4293-9244-1e2e041a08f3.png)
简单适配了下插件头 好像就可以了 就是帮助那里还是metadata还是报错——

**Comment by Ljzd-PRO** [comment]
这里导致的：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/604e773e4441e0a4dda5c436dfd7b9a04cec1e98/src/nonebot_plugin_mystool/__init__.py#L62
https://v2.nonebot.dev/docs/api/plugin/plugin#PluginMetadata

**Comment by ayakasuki** [comment]
对了另外一个问题 最近米游社签到+任务也好像换API了 无法执行，其他作者的插件也试过
![image](https://user-images.githubusercontent.com/20859971/190618943-cbcd78fa-1a71-4c84-ae27-84b895d97f96.png)

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/190619169-a444b722-9f7d-42b5-a355-90dc9a928af2.png)

噢噢 不好意思任务完成了

**Comment by Everything0519** [comment]
> 对了另外一个问题 最近米游社签到+任务也好像换API了 无法执行，其他作者的插件也试过 ![image](https://user-images.githubusercontent.com/20859971/190618943-cbcd78fa-1a71-4c84-ae27-84b895d97f96.png)

签到失败的话 可以看下log具体是什么原因

**Comment by ayakasuki** [comment]
好像是验证码问题



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月18日 08:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Ljzd-PRO/nonebot-plugin-mystool] 跪求真寻移植版 (Issue #27) |

对了另外一个问题 最近米游社签到+任务也好像换API了 无法执行，其他作者的插件也试过

签到失败的话 可以看下log具体是什么原因

**Comment by Ljzd-PRO** [comment]
> 好像是验证码问题

可以发一下具体的日志信息

**Comment by ayakasuki** [comment]
> 那里还是metadata还是报错—

是 弹验证码了

**Comment by ayakasuki** [comment]
已fork并适配[真寻版](https://github.com/ayakasuki/nonebot-plugin-mystool)
