### ISSUE TITLE
每日自动任务私聊用户签到信息不显示

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#270]
每日自动任务只收到米游币任务完成消息，未收到签到消息。从日志看机器人发送了签到私聊但是用户却没收到消息。
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/f4fc1d9f-b61d-4ba9-9ee6-fae5a9b4cf83)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/970fa2e5-7b4a-47e9-a14b-e20692a85bc4)
运行环境：
debian12 x86
python3.11
gocqhttp1.2.0
mystool2.2.0

**Comment by Ljzd-PRO** [comment]
手动执行 `/签到` 命令呢，我这边 QQ 频道的话是可以收到

**Comment by dontdot** [comment]
mystool-dev-v2.2.0，commit是到最新的`0dee8f3669bd6bab3961f42083bfd2a6a1ff90f7`
我也开始了，手动没问题，自动就不行
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/0dee8f3669bd6bab3961f42083bfd2a6a1ff90f7/src/nonebot_plugin_mystool/command/plan.py#L315-L316
尝试删除` + onebot_img_msg`，自动检查成功发送，手动也没问题
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/f3270d41-d5b6-4a9f-8c3f-994860e88ce3)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/ccc18091-b8ff-4f84-b1f1-53c7e62310a5)

**Comment by Sakamakiiizayoi** [comment]
> mystool-dev-v2.2.0，commit是到最新的`0dee8f3669bd6bab3961f42083bfd2a6a1ff90f7` 我也开始了，手动没问题，自动就不行
> 
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/0dee8f3669bd6bab3961f42083bfd2a6a1ff90f7/src/nonebot_plugin_mystool/command/plan.py#L315-L316
> 
> 
> 尝试删除` + onebot_img_msg`，自动检查成功发送，手动也没问题
> ![image](https://private-user-images.githubusercontent.com/55482264/313363746-f3270d41-d5b6-4a9f-8c3f-994860e88ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTg0MTIsIm5iZiI6MTcxMDU1ODExMiwicGF0aCI6Ii81NTQ4MjI2NC8zMTMzNjM3NDYtZjMyNzBkNDEtZDViNi00YTlmLThjM2YtOTk0ODYwZTg4Y2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAzMDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYjQyOWQ0ODJhYTY2NGNkMzY2OWM0Y2Q5NWNlMzljNTI3ZGM3MTFhYTk1YmU5OWY1OTZiMDI4Nzg3OWU2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x24FyKSAkd70Vn-1kWl6qZBTIc-oF6F-I7cxELHr-j8)
> ![image](https://private-user-images.githubusercontent.com/55482264/313363768-ccc18091-b8ff-4f84-b1f1-53c7e62310a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTg0MTIsIm5iZiI6MTcxMDU1ODExMiwicGF0aCI6Ii81NTQ4MjI2NC8zMTMzNjM3NjgtY2NjMTgwOTEtYjhmZi00Zjg0LWIxZjEtNTNjN2U2MjMxMGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAzMDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzkyYmQzMjA2NGViNGI0Zjk5YzkyYjhhZWI0YzcwZDU3YTA5NDM3YmVkNjJmZTZkNjY4NmMzYmMzMTdiODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.11tCpVXCcanukkxQozHYnQsvTQLnV0WPXUatoAzSzN4)

删除了 + onebot_img_msg 自动任务签到消息还是没有诶，不过我不是dev版本，这个有关系吗？

**Comment by Sakamakiiizayoi** [comment]
> 手动执行 `/签到` 命令呢，我这边 QQ 频道的话是可以收到

手动执行是没问题的，还有就是建议每日任务先游戏签到再做米游币任务，先游戏签到打码成功后米游币任务签到大概率是不会再遇到验证码，这样可以减少一次打码，我之前几个月都是这么用的

**Comment by dontdot** [comment]
可以的话打包你安装的mystool给我吗，我去试试看什么原因
先签到后米游币你可以去plan中定时触发每日任务那段的调换下上下位置就行

**Comment by Sakamakiiizayoi** [comment]
> 可以的话打包你安装的mystool给我吗，我去试试看什么原因 先签到后米游币你可以去plan中定时触发每日任务那段的调换下上下位置就行

交换位置我知道，我建议正式代码也这么干。打包怎么发给你呢

**Comment by Sakamakiiizayoi** [comment]
> 可以的话打包你安装的mystool给我吗，我去试试看什么原因 先签到后米游币你可以去plan中定时触发每日任务那段的调换下上下位置就行

我安装的就是2.2.0的版本未经修改的 使用nb指令安装

**Comment by dontdot** [comment]
直接上传文件到这个issue

**Comment by Sakamakiiizayoi** [comment]
[nonebot_plugin_mystool.zip](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/files/14622279/nonebot_plugin_mystool.zip)

**Comment by dontdot** [comment]
> [nonebot_plugin_mystool.zip](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/files/14622279/nonebot_plugin_mystool.zip)

你删错地方了，应该删掉323行的` + onebot_img_msg`的，而不是把312行的删了。312行可以不用删，这是手动签到的

**Comment by Sakamakiiizayoi** [comment]
> > [nonebot_plugin_mystool.zip](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/files/14622279/nonebot_plugin_mystool.zip)
> 
> 你删错地方了，应该删掉323行的` + onebot_img_msg`的，而不是把312行的删了。312行可以不用删，这是手动签到的

是你说错地方了吧，这埚我可不背![0033C5B9](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/18918bba-1209-427c-adc2-7318c460d90e)
我删掉了，明天试试

**Comment by dontdot** [comment]
> > > [nonebot_plugin_mystool.zip](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/files/14622279/nonebot_plugin_mystool.zip)
> > 
> > 
> > 你删错地方了，应该删掉323行的` + onebot_img_msg`的，而不是把312行的删了。312行可以不用删，这是手动签到的
> 
> 是你说错地方了吧，这埚我可不背![0033C5B9](https://private-user-images.githubusercontent.com/67581432/313372603-18918bba-1209-427c-adc2-7318c460d90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NjE4MDYsIm5iZiI6MTcxMDU2MTUwNiwicGF0aCI6Ii82NzU4MTQzMi8zMTMzNzI2MDMtMTg5MThiYmEtMTIwOS00MjdjLWFkYzItNzMxOGM0NjBkOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAzNTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NTAyMTZhODFhZTQyZGNhZWEzZWFjYmQxNzM2ODRjZDA5OTJkZmIzZDYwMjc2ZmNiMzkzOTI2NGEyMjk5YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8FZEkamsSRS6sNrWtCV5ohR-_tZci9hcd5UEPY3zizc) 我删掉了，明天试试

你把plan_time成当前时间的几分钟后重启下机器人试下就行了，应该就是删错地方了

**Comment by Sakamakiiizayoi** [comment]
额 对哦，可以重复签到来着，我思维僵化了

**Comment by Sakamakiiizayoi** [comment]
可以收到签到消息了，就是少了物品图片，难不成是现在风控主动私聊不能发图片了嘛

**Comment by dontdot** [comment]
> 可以收到签到消息了，就是少了物品图片，难不成是现在风控主动私聊不能发图片了嘛

不是，手动签能发图不是吗，可能是saa的私聊有问题，不能文字+图片一起发，又或者是ljzd传入格式有问题，我记得把消息传入里面后经过了text()，不清楚是不是这里的问题

**Comment by Sakamakiiizayoi** [comment]
> > 可以收到签到消息了，就是少了物品图片，难不成是现在风控主动私聊不能发图片了嘛
> 
> 不是，手动签能发图不是吗，可能是saa的私聊有问题，不能文字+图片一起发

有可能，以前1.4的时候没有saa用着就正常

**Comment by dontdot** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/57d2fc93-70f8-4727-a348-ad8a447b3cfd)
这是成功接收到的，有调用api的日志
————————————————————
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/9c797632-1164-4670-91b0-5468d03e8558)
这是没接收信息的日志

**Comment by Ljzd-PRO** [comment]
应该是因为图片消息是用Adapter QQ构建的，但发送却用的是SAA发送。现在改成了用SAA构建图片消息，然后和文本消息做加法，可以试试有没有效果

**Comment by dontdot** [comment]
可以收到了
