### ISSUE TITLE
登录命令等候命令结束的时间过短

### ISSUE THREAD

**Issue by ayakasuki** [Ljzd-PRO/nonebot-plugin-mystool#28]
登录验证码真正获取下一个等待输入的时候，命令却已经结束了，不清楚是nonebot版会不会出现，真寻版会这样
![image](https://user-images.githubusercontent.com/20859971/191175936-595c33c8-3b46-4d21-b13d-1895e7cf4609.png)

**Comment by ayakasuki** [comment]
就特别是验证码不是有60s嘛 要获取两次 第二次还没等到验证码再次获取时间 在输入的时候发现命令已经结束了，要重新打登录命令

**Comment by Everything0519** [comment]
这是你自己机器人配置的问题。在nonebot中，可以配置超时时间，默认是120秒，所以一般不会出现问题。你可以自己查看一下你的真寻机器人配置

**Comment by ayakasuki** [comment]
> 这是你自己机器人配置的问题。在nonebot中，可以配置超时时间，默认是120秒，所以一般不会出现问题。你可以自己查看一下你的真寻机器人配置

问了一下说是去nb的config改

**Comment by ayakasuki** [comment]
但是不对劲的是 并没有120s就退出了，真寻那边的作者说他们是没有干预管理这个命令退出来着

**Comment by Everything0519** [comment]
可以参考一下nonebot相关配置
https://v2.nonebot.dev/docs/tutorial/configuration
正常来说 会话超时时间是120秒 不会有问题的
你启动机器人时，log会输出机器人相关配置，你可以检查一下超时时间

**Comment by ayakasuki** [comment]
> 可以参考一下nonebot相关配置 https://v2.nonebot.dev/docs/tutorial/configuration 正常来说 会话超时时间是120秒 不会有问题的 你启动机器人时，log会输出机器人相关配置，你可以检查一下超时时间

![GVCQCQCPL6CLF42(B~D%_}B](https://user-images.githubusercontent.com/20859971/191202580-d01b53ee-b440-4264-b705-74402b88c27d.png)
大佬 nonebot是改这里嘛 我改这里试试看

**Comment by Everything0519** [comment]
bot.py同目录下的.env文件里加上这句就行 nonebot版是这样

**Comment by ayakasuki** [comment]
好的 我试一下在env加一下

> bot.py同目录下的.env文件里加上这句就行 nonebot版是这样

**Comment by ayakasuki** [comment]
![6`5{} ~3YNZ{0JGM9~Q`LO3](https://user-images.githubusercontent.com/20859971/191204402-2e06c755-e61c-468e-a5bd-5f7c53d17f99.png)
抱歉 我忘记是在env这里面有个30s了 佛了 谢谢大佬提醒
