### ISSUE TITLE
关于人机验证如何对接图鉴打码平台

### ISSUE THREAD

**Issue by wang4386** [Ljzd-PRO/nonebot-plugin-mystool#281]
图鉴打码平台文档地址http://www.ttshitu.com/docs/index.html?spm=null
识别九宫格验证码返回对应图片对应的九宫格数字
123
456
789
比如需要点选的图片是246则返回246数字，使用的无感学习进行测试米游社的验证码
![Screenshot_2024-04-05-11-28-54-038_com mihoyo hyp](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/53611531/6c7df99f-4839-4713-9676-c84f2d05094e)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/53611531/cdf1ae01-69aa-4fd8-a5fd-5367f328259e)
希望可以考虑增加该平台的对接文档

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Configuration-Preference#geetest_url

可以参考一下。不过要专门能接极验的平台才行。如果API用法不太一样的话，可能得自己加个中间层

**Comment by wang4386** [comment]
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Configuration-Preference#geetest_url
> 
> 可以参考一下。不过要专门能接极验的平台才行。如果API用法不太一样的话，可能得自己加个中间层

文档写的太简略了，看不懂，希望项目可以适配我上面提到的图鉴平台，然后我们只需在.env中配置图鉴平台信息即可对接，最好

**Comment by dontdot** [comment]
geetest_url就是接极验平台给出的url，geetest_params填入平台使用文档中必填的参
图鉴平台只是给出你该点第几张图是吗，要让bot怎么获取九宫图的图片和模拟点击都是一个大问题

**Comment by skelfu** [comment]
看起来这个平台并不是专门验证geetest的，需要部署的话得自己解决geetest的gt，challenge和这个平台的对接问题，用geetest参数生成验证码图片，通过这个平台的api获取验证结果，模拟通过验证码获取validate数据

**Comment by Sakamakiiizayoi** [comment]
我之前用的套套图像打码平台，中间层后端我也写了你可以看看https://github.com/Sakamakiiizayoi/ttocr_auto
不过最近这个平台改版了，最低充值30 有点离谱。现在改用了人人打码平台，还不错，后端我发在ttocr_auto的rr分支

**Comment by Clulu1499** [comment]
> 我之前用的套套图像打码平台，中间层后端我也写了你可以看看 https://github.com/Sakamakiiizayoi/ttocr_auto 不过最近这个平台改版了，最低充值30 有点离谱。现在改用了人人打码平台，还不错，后端我发在ttocr_auto的rr分支

大佬请问我按照你的格式填好了，后端服务appkey填好了也是在运行的，但是机器人重启后报了下面的错，可以看看是什么原因吗
![1](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/72173120/3d6a8c13-665e-4318-a385-8793431afc80)
![4](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/72173120/3212c552-1485-434d-920d-a3f753e22b7b)
![2](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/72173120/10fb60a3-58a4-4a6c-9369-dcb1ea345564)
![3](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/72173120/2fa395a2-d946-4a28-a3e3-02e932028470)

**Comment by Sakamakiiizayoi** [comment]
你这配置文件在哪改的，我看你配置文件的json格式都不对，漏逗号引号。机器人的配置文件路径data/nonebot-plugin-mystool/configV2.json

**Comment by Clulu1499** [comment]
> 你这配置文件在哪改的，我看你配置文件的json格式都不对，漏逗号引号。机器人的配置文件路径data/nonebot-plugin-mystool/configV2.json

感谢大佬指点！——原来我一直修改的配置文件目录不对，一直改的\.venv\Lib\site-packages\nonebot_plugin_mystool\model\config.py
