### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Fahaxikiii** [Ljzd-PRO/nonebot-plugin-mystool#286]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/93320886/fbd0f5ae-6075-4ba9-aa64-f6c8c91f8d12)

**Comment by shaw213** [comment]
初步判断，可能是这里报错了
```
cookies.stoken = list(filter(
    lambda x: x["name"] == "stoken", api_result.data["list"]))[0]["token"]
cookies.ltoken = list(filter(
    lambda x: x["name"] == "ltoken", api_result.data["list"]))[0]["token"]
return GetCookieStatus(success=True), cookies
```
现在上面代码中的api_result.data不包含stoken了

**Comment by 1714775263** [comment]
> 初步判断，可能是这里报错了
> 
> ```
> cookies.stoken = list(filter(
>     lambda x: x["name"] == "stoken", api_result.data["list"]))[0]["token"]
> cookies.ltoken = list(filter(
>     lambda x: x["name"] == "ltoken", api_result.data["list"]))[0]["token"]
> return GetCookieStatus(success=True), cookies
> ```
> 
> 现在上面代码中的api_result.data不包含stoken了

获取不到stoken能够解决吗

**Comment by Ljzd-PRO** [comment]
API改了的话可能就比较麻烦了，得找其他有stoken的API

**Comment by 1714775263** [comment]
> API改了的话可能就比较麻烦了，得找其他有stoken的API

有个办法可以用米游社扫码登录（GameToken）这个应该可以把

**Comment by Ljzd-PRO** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/issues/46

> > API改了的话可能就比较麻烦了，得找其他有stoken的API
> 
> 有个办法可以用米游社扫码登录（GameToken）这个应该可以把

这个不知道是否需要用户有注册游戏账号

**Comment by Fahaxikiii** [comment]
> https://github.com/UIGF-org/mihoyo-api-collect/issues/46
> 
> > > API改了的话可能就比较麻烦了，得找其他有stoken的API
> > 
> > 有个办法可以用米游社扫码登录（GameToken）这个应该可以把
> 
> 这个不知道是否需要用户有注册游戏账号

应该是不需要的

**Comment by Ljzd-PRO** [comment]
现在已经改成用扫码的方式登录了，但是我QQ频道发送二维码图片失败，没法继续测试

**Comment by Ljzd-PRO** [comment]
> 现在已经改成用扫码的方式登录了，但是我QQ频道发送二维码图片失败，没法继续测试

新增内容在dev分支
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/tree/dev

**Comment by Fahaxikiii** [comment]
> 现在已经改成用扫码的方式登录了，但是我QQ频道发送二维码图片失败，没法继续测试

大佬厉害，我是在QQ聊天里面使用的

**Comment by Graduallyhui** [comment]
> > 现在已经改成用扫码的方式登录了，但是我QQ频道发送二维码图片失败，没法继续测试
> 
> 新增内容在dev分支 https://github.com/Ljzd-PRO/nonebot-plugin-mystool/tree/dev

大佬你好，我使用了dev分支，使用登录时，没有发送二维码图片报错了
![){TZ~MUG1LE)}`J4 FW}~B3](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/124028234/4e1f0c06-7cf8-4421-94bb-2198b26b404c)

**Comment by Ljzd-PRO** [comment]
> > > 现在已经改成用扫码的方式登录了，但是我QQ频道发送二维码图片失败，没法继续测试
> > 
> > 
> > 新增内容在dev分支 https://github.com/Ljzd-PRO/nonebot-plugin-mystool/tree/dev
> 
> 大佬你好，我使用了dev分支，使用登录时，没有发送二维码图片报错了 ![){TZ~MUG1LE)}`J4 FW}~B3](https://private-user-images.githubusercontent.com/124028234/327504935-4e1f0c06-7cf8-4421-94bb-2198b26b404c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzAzMDEsIm5iZiI6MTcxNDY3MDAwMSwicGF0aCI6Ii8xMjQwMjgyMzQvMzI3NTA0OTM1LTRlMWYwYzA2LTdjZjgtNDQyMS05NGJiLTIxOThiMjZiNDA0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNzEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDliMWZkMmMzZTJlZDY3NjM4ZDgxYWViNjI0OTZmMDAyOTA2MmQzNTJjMjUwZDA2ODdlOWQxNmUxMmMxMjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xHP-khGHzszX4JoPqbhluOAy9RKxUqyhMOjUiFWK_NI)

现在没问题了，但得到的 stoken 实际上是 v2 的

**Comment by Ljzd-PRO** [comment]
```json
"token": {
  "token_type": 1,
  "token": "v2_xxxx-xxxx-xxxx_xxxx==xxxx="
}
```

通过 GameToken 获取 STokenV1 的API (`https://api-takumi.mihoyo.com/account/ma-cn-session/app/getTokenByGameToken`)，得到的是V2的，还是不行。

**Comment by Ljzd-PRO** [comment]
> "token": {
>   "token_type": 1,
>   "token": "v2_xxxx-xxxx-xxxx_xxxx==xxxx="
> }
> 通过 GameToken 获取 STokenV1 的API (`https://api-takumi.mihoyo.com/account/ma-cn-session/app/getTokenByGameToken`)，得到的是V2的，还是不行。

并且似乎是因为只有stokenV2，缺少mid，连 ltoken 和 cookie_token 也无法获取

**Comment by Fahaxikiii** [comment]
> > "token": {
> > "token_type": 1,
> > "token": "v2_xxxx-xxxx-xxxx_xxxx==xxxx="
> > }
> > 通过 GameToken 获取 STokenV1 的API (`https://api-takumi.mihoyo.com/account/ma-cn-session/app/getTokenByGameToken`)，得到的是V2的，还是不行。
> 
> 并且似乎是因为只有stokenV2，缺少mid，连 ltoken 和 cookie_token 也无法获取

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/93320886/443196d9-b04e-4461-bf23-47a5983ce293)
生成二维码报错。但是我试了一下是可以将stoken_v1，stoken_v2，ltoken，stoken全部设置为stoken_v2是可以正常游戏签到和米游社任务的。https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken?stoken=&mid=可以获取到uid和cookie_token。但是login_ticket和mid不知道如何获取

**Comment by Fahaxikiii** [comment]
> > "token": {
> > "token_type": 1,
> > "token": "v2_xxxx-xxxx-xxxx_xxxx==xxxx="
> > }
> > 通过 GameToken 获取 STokenV1 的API (`https://api-takumi.mihoyo.com/account/ma-cn-session/app/getTokenByGameToken`)，得到的是V2的，还是不行。
> 
> 并且似乎是因为只有stokenV2，缺少mid，连 ltoken 和 cookie_token 也无法获取

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/93320886/737ac86e-850f-4464-b499-91a63219fccc)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/93320886/c56d590d-9df4-4ad1-8efc-168535ed87e5)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/93320886/e225039b-ca0d-48f5-be4b-429462fb7b8e)

**Comment by Ljzd-PRO** [comment]
> ![image](https://private-user-images.githubusercontent.com/93320886/327544278-737ac86e-850f-4464-b499-91a63219fccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjEwODgsIm5iZiI6MTcxNDgyMDc4OCwicGF0aCI6Ii85MzMyMDg4Ni8zMjc1NDQyNzgtNzM3YWM4NmUtODUwZi00NDY0LWI0OTktOTFhNjMyMTlmY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MzQ2Yzk3ZTc1YTAxYmEwMGQ5NjczNmRmZDI0ZWY3NWZlZTkzYmZkOTc3ODMwNGRhYTQ3MGYwNDhmMmYwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NEAs8OQkzONlrq3Y8fDNZs_m2XeOwgoil40VxKZdWd4) ![image](https://private-user-images.githubusercontent.com/93320886/327544355-c56d590d-9df4-4ad1-8efc-168535ed87e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjEwODgsIm5iZiI6MTcxNDgyMDc4OCwicGF0aCI6Ii85MzMyMDg4Ni8zMjc1NDQzNTUtYzU2ZDU5MGQtOWRmNC00YWQxLThlZmMtMTY4NTM1ZWQ4N2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNDIzNjQyYzBhMDZhNjk0YmI1NzEwZjJkZDU5MTBjMTMyZTVjYzUwNDgyYmM2YTgwZDEzYzdkZjA2ZjM0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dwGOIvy9Jn8mGXNaboL4Dj33qhl1F5BGdUBiUij4mt8) ![image](https://private-user-images.githubusercontent.com/93320886/327544420-e225039b-ca0d-48f5-be4b-429462fb7b8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjEwODgsIm5iZiI6MTcxNDgyMDc4OCwicGF0aCI6Ii85MzMyMDg4Ni8zMjc1NDQ0MjAtZTIyNTAzOWItY2EwZC00OGY1LWJlNGItNDI5NDYyZmI3YjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NjIxYjJhM2NiMjJiYjk4Y2IyOWZmODUzMzRjM2M2YzM3M2VlOGMzNjgyMzg0ZGE1NWRhZTdkNjdmYzdmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YqChBrz2AqlU0hZBmb1zAEl3IyvfFSCp51sIuVt6EbQ)

看上去是还需要`login_ticket`和`cookie_token`?

**Comment by Fahaxikiii** [comment]
> > ![image](https://private-user-images.githubusercontent.com/93320886/327544278-737ac86e-850f-4464-b499-91a63219fccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjEwODgsIm5iZiI6MTcxNDgyMDc4OCwicGF0aCI6Ii85MzMyMDg4Ni8zMjc1NDQyNzgtNzM3YWM4NmUtODUwZi00NDY0LWI0OTktOTFhNjMyMTlmY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MzQ2Yzk3ZTc1YTAxYmEwMGQ5NjczNmRmZDI0ZWY3NWZlZTkzYmZkOTc3ODMwNGRhYTQ3MGYwNDhmMmYwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NEAs8OQkzONlrq3Y8fDNZs_m2XeOwgoil40VxKZdWd4) ![image](https://private-user-images.githubusercontent.com/93320886/327544355-c56d590d-9df4-4ad1-8efc-168535ed87e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjEwODgsIm5iZiI6MTcxNDgyMDc4OCwicGF0aCI6Ii85MzMyMDg4Ni8zMjc1NDQzNTUtYzU2ZDU5MGQtOWRmNC00YWQxLThlZmMtMTY4NTM1ZWQ4N2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNDIzNjQyYzBhMDZhNjk0YmI1NzEwZjJkZDU5MTBjMTMyZTVjYzUwNDgyYmM2YTgwZDEzYzdkZjA2ZjM0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dwGOIvy9Jn8mGXNaboL4Dj33qhl1F5BGdUBiUij4mt8) ![image](https://private-user-images.githubusercontent.com/93320886/327544420-e225039b-ca0d-48f5-be4b-429462fb7b8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjEwODgsIm5iZiI6MTcxNDgyMDc4OCwicGF0aCI6Ii85MzMyMDg4Ni8zMjc1NDQ0MjAtZTIyNTAzOWItY2EwZC00OGY1LWJlNGItNDI5NDYyZmI3YjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NjIxYjJhM2NiMjJiYjk4Y2IyOWZmODUzMzRjM2M2YzM3M2VlOGMzNjgyMzg0ZGE1NWRhZTdkNjdmYzdmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YqChBrz2AqlU0hZBmb1zAEl3IyvfFSCp51sIuVt6EbQ)
> 
> 看上去是还需要`login_ticket`和`cookie_token`?

这我没有去试，感觉应该是不需要的吧

**Comment by Ljzd-PRO** [comment]
现在可以用扫码的方式登录了。不需要stokenV1，其他的cookie也都可以获取到。不过之前短信验证码登录也是可以的，应该可以提供两种登录方式

**Comment by Graduallyhui** [comment]
> 现在可以用扫码的方式登录了。不需要stokenV1，其他的cookie也都可以获取到。不过之前短信验证码登录也是可以的，应该可以提供两种登录方式

大佬你好，在qq使用时还是不能用扫码登录，好像还是上次的报错
![@K)E$SXW0F$BU `GTCHD@US](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/124028234/24cbd483-2394-453d-8dd3-e069a5756ba9)

**Comment by Ljzd-PRO** [comment]
> > 现在可以用扫码的方式登录了。不需要stokenV1，其他的cookie也都可以获取到。不过之前短信验证码登录也是可以的，应该可以提供两种登录方式
> 
> 大佬你好，在qq使用时还是不能用扫码登录，好像还是上次的报错 ![@K)E$SXW0F$BU `GTCHD@US](https://private-user-images.githubusercontent.com/124028234/327947831-24cbd483-2394-453d-8dd3-e069a5756ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjYwNjgsIm5iZiI6MTcxNDgyNTc2OCwicGF0aCI6Ii8xMjQwMjgyMzQvMzI3OTQ3ODMxLTI0Y2JkNDgzLTIzOTQtNDUzZC04ZGQzLWUwNjlhNTc1NmJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMjI5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzRjY2RiMzFhZDBiZTAzOWNjZmNmZmFmMDRiODcwYjY1NjI4Y2IwOTRkNzIyYjhhMDNhODI4MDY3ZTZiZWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4qiXB4nQ4bt477MWYLtmRBSz5kcuBoKW3tfTM4irHxE)

看上去是图片发送失败了，可能还要改改

**Comment by Fahaxikiii** [comment]
> > > 现在可以用扫码的方式登录了。不需要stokenV1，其他的cookie也都可以获取到。不过之前短信验证码登录也是可以的，应该可以提供两种登录方式
> > 
> > 大佬你好，在qq使用时还是不能用扫码登录，好像还是上次的报错 ![@K)E$SXW0F$BU `GTCHD@US](https://private-user-images.githubusercontent.com/124028234/327947831-24cbd483-2394-453d-8dd3-e069a5756ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjYwNjgsIm5iZiI6MTcxNDgyNTc2OCwicGF0aCI6Ii8xMjQwMjgyMzQvMzI3OTQ3ODMxLTI0Y2JkNDgzLTIzOTQtNDUzZC04ZGQzLWUwNjlhNTc1NmJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMjI5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzRjY2RiMzFhZDBiZTAzOWNjZmNmZmFmMDRiODcwYjY1NjI4Y2IwOTRkNzIyYjhhMDNhODI4MDY3ZTZiZWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4qiXB4nQ4bt477MWYLtmRBSz5kcuBoKW3tfTM4irHxE)
> 
> 看上去是图片发送失败了，可能还要改改

可以正常扫码登录并且完成签到了，大佬NB😍
