### ISSUE TITLE
wb兑换如何使用

### ISSUE THREAD

**Issue by TyxTang** [Ljzd-PRO/nonebot-plugin-mystool#287]
在dev版本中看到了大佬推送了wb兑换码和签到的pr
想问问params如何获取

**Comment by Ljzd-PRO** [comment]
@Joseandluue

**Comment by dontdot** [comment]
https://github.com/arcturus-script/weibo
社区上很多之类的抓包，你搜超话 签到的关键词，wb_params只能从android上抓取

**Comment by TyxTang** [comment]
> https://github.com/arcturus-script/weibo 社区上很多之类的抓包，你搜超话 签到的关键词，wb_params只能从android上抓取

了解，去试试感谢
