### ISSUE TITLE
增加兑换计划失败

### ISSUE THREAD

**Issue by scopion** [Ljzd-PRO/nonebot-plugin-mystool#29]
![image](https://user-images.githubusercontent.com/27413591/191443829-d0b9d235-430a-4416-8832-eac6dd690140.png)

**Comment by Everything0519** [comment]
请参考#26
当前版本兑换时若没有配置地址会有该问题，开发版中已修复。要么调用/地址 先配置地址再兑换原石这种虚拟物品，要么你可以去dev开发版中，复制exchangeplan.py代码来覆盖。
