### ISSUE TITLE
登录二维码无法正常显示

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#293]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/b2f50ba4-4106-494f-80fb-2eb1c7183a78)
后台没有报错

**Comment by Ljzd-PRO** [comment]
有点奇怪，完全为空的消息，也没有文字的气泡。#286 有人QQ聊天试过是没问题。

**Comment by Ljzd-PRO** [comment]
该不会是QQ客户端的问题

**Comment by beiji-O-o** [comment]
> 该不会是QQ客户端的问题

电脑可以，移动端的设备不行

**Comment by Ljzd-PRO** [comment]
> > 该不会是QQ客户端的问题
> 
> 电脑可以，移动端的设备不行

那应该和程序没什么关系
