### ISSUE TITLE
这个是什么报错，/任务*后卡在某个账号了

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#294]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/53fcd307-8e75-4e3f-8964-058a2da8d9b7)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/5b92e9ee-74b0-4af7-a6e1-659e262f4f4b)

**Comment by beiji-O-o** [comment]
现在更新最新版本后不会卡住了，能正常下一个，但是后台有报错
<img width="1071" alt="image" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/de7cbdaa-843f-4bd4-87a1-ae05e23eb093">

**Comment by beiji-O-o** [comment]
之前更新后没问题了，今天突然又会这样了...

**Comment by beiji-O-o** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/2c3d833e-6e90-40a4-9bd7-1ccc39f3f6e0)

**Comment by beiji-O-o** [comment]
> ![image](https://private-user-images.githubusercontent.com/100279019/339724345-2c3d833e-6e90-40a4-9bd7-1ccc39f3f6e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTkzMDAsIm5iZiI6MTcxODM1OTAwMCwicGF0aCI6Ii8xMDAyNzkwMTkvMzM5NzI0MzQ1LTJjM2Q4MzNlLTZlOTAtNDBhNC05YmQ3LTFjY2MzOWYzZjZlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwOTU2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTQ5OWRlMTc0YTJiNTdiMTgzY2VkZDI3ZDMxNmYxM2Q5ZDNkZDU1YTBkNzkwMjMwZjZjNGM2YmFiZTA1MGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ZzJyHW0szHomRmR8b_qVHgzmKq-b7kpqHGYm4TPU54)

![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/100279019/70a48283-3725-4dee-88c1-493760768f47)

**Comment by Ljzd-PRO** [comment]
应该已经在2.7.0版本修复
