### ISSUE TITLE
大佬能看看这是啥问题嘛/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by sugar1777** [Ljzd-PRO/nonebot-plugin-mystool#30]
![image](https://user-images.githubusercontent.com/77088070/192140220-cefdc93d-c1c0-4f93-a761-c4ce4c4c3318.png)

**Comment by Everything0519** [comment]
可能是获取商品失败了 你尝试重启一下机器人呢

**Comment by Everything0519** [comment]
你是换的什么商品呢 商品的id可以发一下 我试试看

**Comment by sugar1777** [comment]
商品已经兑换完了，估计找不到了吧，上次兑换的商品是这两个
-- 商品 【原神】原石*120                
- 商品ID：2022082312197  

- -- 商品 【原神】原石*60                
- 商品ID：2022082312478                
- 商品价格：1800 米游币

**Comment by sugar1777** [comment]
还有你那机器人得提前在米友社设置好地址，没设置号机器人啥也不会说，你能不能加个提醒，就是别人发 /兑换 的时候如果没有设置地址qq发消息提醒，你这个只能在后台看到消息

**Comment by Everything0519** [comment]
> 还有你那机器人得提前在米友社设置好地址，没设置号机器人啥也不会说，你能不能加个提醒，就是别人发 /兑换 的时候如果没有设置地址qq发消息提醒，你这个只能在后台看到消息

这个bug已经解决了 在开发版里面 你可以在dev分支辅助exchangeplan.py代码来覆盖 现在准备完成其他功能一起发布

**Comment by Everything0519** [comment]
请参考#26 #29

**Comment by sugar1777** [comment]
> > 还有你那机器人得提前在米友社设置好地址，没设置号机器人啥也不会说，你能不能加个提醒，就是别人发 /兑换 的时候如果没有设置地址qq发消息提醒，你这个只能在后台看到消息
> 
> 这个bug已经解决了 在开发版里面 你可以在dev分支辅助exchangeplan.py代码来覆盖 现在准备完成其他功能一起发布

哈哈哈，没注意，好的好的

**Comment by sugar1777** [comment]
我这个错误会不会是兑换计划执行成功或者失败后没删除这个计划，我上次好像在兑换日期之后还看见这个计划，时间改了一下，但是商品已经不在米友社了

**Comment by Everything0519** [comment]
不好意思看错问题了 你的意思是米游社得先配置好地址是吧 我们代码有有这部分的反馈 就是没有配置地址会提醒 可以的话你把log这部分给我看下

**Comment by Everything0519** [comment]
> 我这个错误会不会是兑换计划执行成功或者失败后没删除这个计划，我上次好像在兑换日期之后还看见这个计划，时间改了一下，但是商品已经不在米友社了

那应该是这样的 不在的话确实会报错 我到时候改一下逻辑就行
