### ISSUE TITLE
求助 微博签到params参数如何获取

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#306]
如题 浏览器上cookie sub subp可以找到，浏览器端的超话签到请求里好像也没有s,gsid,aid,from的参数，该如何获取s,gsid,aid,from参数

**Comment by dontdot** [comment]
用手机抓包

**Comment by Sakamakiiizayoi** [comment]
研究了一下手机抓包，据说安卓7更新了软件安全策略，app的https包抓不了。试了一下导入伪造ca确实不行，这咋整，难道需要root权限吗

**Comment by Sakamakiiizayoi** [comment]
难道说是app只认系统分区根证书，不认用户手动导入的根证书吗

**Comment by dontdot** [comment]
> 研究了一下手机抓包，据说安卓7更新了软件安全策略，app的https包抓不了。试了一下导入伪造ca确实不行，这咋整，难道需要root权限吗

是，但是可以使用模拟器解root抓包

**Comment by Sakamakiiizayoi** [comment]
模拟器！ 可以我试试

**Comment by Sakamakiiizayoi** [comment]
成了，但是wb签到好像有问题，不知道是不是重复签到的原因
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/d087fb23-1492-419f-a885-50c68c9425dd)
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/6609c1ac-c7bf-45fa-b991-e456394f24f4)

**Comment by dontdot** [comment]
偶尔会出现获取不到超话列表的情况，你再试一次就行了
