### ISSUE TITLE
增加群聊支持

### ISSUE THREAD

**Issue by Xiao-yux** [Ljzd-PRO/nonebot-plugin-mystool#31]
这个插件只能私聊吗？
![image](https://user-images.githubusercontent.com/79674967/192808983-4a1f7aad-960b-4f11-8b57-18fdfc46a10b.png)
我想在群里使用一些功能
比如签到什么的
绑定还是私聊完成

**Comment by Everything0519** [comment]
现在大部分功能都只支持私聊完成 除了帮助命令
暂时还没有修改其他功能群聊实现的想法..主要是不安全
比如说地址获取之类的
如果你想实现的话 可以自己修改一下事件类型就行

**Comment by Xiao-yux** [comment]
- 我就是想要个签到，给别人看的

**Comment by Xiao-yux** [comment]
自己试试改吧（不会pythin）

**Comment by Everything0519** [comment]
那我帮你改吧 别急

**Comment by Ljzd-PRO** [comment]
已发布预览版：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v0.2.2-beta.1

**Comment by Ljzd-PRO** [comment]
已更新 v0.2.2：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v0.2.2
