### ISSUE TITLE
微博签到一直显示找不到超话列表

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#318]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/300b44c6-072a-47a1-bdd4-ef55ce7e43c2)
手动签到后可以正常获取到兑换码
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/c89dc6d4-8338-48c6-bd05-d0fc1d80e9dc)

**Comment by Sakamakiiizayoi** [comment]
用的是dev分支的代码

**Comment by dontdot** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/9195197c89ac1b71b1547a8898dcd15d31fa5a62/src/nonebot_plugin_mystool/api/weibo.py#L211
输出一下响应内容

**Comment by Sakamakiiizayoi** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/b68fa944-d694-46fa-85a2-1889a518eb53)

是我参数设置错误吗，我设置两次了

**Comment by Sakamakiiizayoi** [comment]
{
                    "name": "izayoi",
                    "cookie": "SUB=_2A2XXXXXXXXXXXXXXXXXXXXXXXXXXXVo_s3rrDV6PUJbitANLUXAkWtNSze4hWs5SxSjRM39-abWnrnYXOXwhi1Y;SUBP=0033WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxgg5NHD95Qf1hMf1hMfS02cWs4Dqcj6i--ci-2fi-27i--ci-2fi-27i--Xi-iFiKyWi--fi-2Xi-24i--ciKLWi-zXi--fi-8siKyhi--fiK.RiKLF",
                    "params": "s=7bXXXX79;gsid=_2A25LdVXXXXXXXXXXXXXXXXXXXXXXXXXXXXXpNSze4hSvayE9uxPQTKnWHgWFz_ntXlKEu;aid=01AxMxj0pfEvxXXXXXXXXXXXXXXXXXd-x9uYPNrI76YV4U.;from=10XXXXXX0"
                }
参数是这样的

**Comment by dontdot** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/505b184af0a52c765abb73a14811a520eaf2e0e2/src/nonebot_plugin_mystool/api/weibo.py#L236-L242
你把c也设置一下，好像当初我测了没带c也能签所以没放在必填里

**Comment by Sakamakiiizayoi** [comment]
好 我试试

**Comment by Sakamakiiizayoi** [comment]
成了
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/66034284-5218-4153-87ad-06691b67b341)
