### ISSUE TITLE
大佬，我需要帮忙，关于米游社任务的

### ISSUE THREAD

**Issue by NOWorEVER** [Ljzd-PRO/nonebot-plugin-mystool#319]
我把米游社的任务都迁移到快捷指令了。但是这边一直没办法完成分享任务。怀疑是salt的问题，但是我用你源码的几个salt都没办法转移出和抓包一样匹配的值。能帮我一下吗

**Comment by Ljzd-PRO** [comment]
和对应的App版本可能有关系

**Comment by NOWorEVER** [comment]
好的

**Comment by Ljzd-PRO** [comment]
可以参考这个：https://github.com/UIGF-org/mihoyo-api-collect/blob/main/other/authentication.md

**Comment by NOWorEVER** [comment]
> 可以参考这个：https://github.com/UIGF-org/mihoyo-api-collect/blob/main/other/authentication.md

太感谢了😘😘😘
