### ISSUE TITLE
欢迎语在哪里修改

### ISSUE THREAD

**Issue by xiaotianYQR** [Ljzd-PRO/nonebot-plugin-mystool#322]
想修改一下加好友后的欢迎语请问从哪里改？

**Comment by Ljzd-PRO** [comment]
在这里：
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b8377d240de800642fe4b85b74a9e92c1016c43a/src/nonebot_plugin_mystool/command/user_check.py#L49-L50

**Comment by xiaotianYQR** [comment]
> 在这里：
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b8377d240de800642fe4b85b74a9e92c1016c43a/src/nonebot_plugin_mystool/command/user_check.py#L49-L50

ok谢
