### ISSUE TITLE
找不到bot.py是咋回事

### ISSUE THREAD

**Issue by Jsmxing** [Ljzd-PRO/nonebot-plugin-mystool#34]

**Comment by Jsmxing** [comment]
![Screenshot_2022-11-09-15-36-53-162_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/46810706/200767911-49774260-a650-42f2-9dbd-6f5342edfe2d.jpg)

**Comment by Ljzd-PRO** [comment]
要先创建机器人项目，参考官方文档：https://v2.nonebot.dev/docs/tutorial/create-project

**Comment by Ljzd-PRO** [comment]
> 要先创建机器人项目，参考官方文档：https://v2.nonebot.dev/docs/tutorial/create-project

使用
```
nb create
```
进行创建
