### ISSUE TITLE
更新2.6.0后出现了三个问题

### ISSUE THREAD

**Issue by RMo233** [Ljzd-PRO/nonebot-plugin-mystool#342]
刚刚使用nb plugin update nonebot-plugin-mystool指令升级了插件，升级后机器人无法正常运行，问题与 #303 一致，是exchange_plan的报错。后来不知道怎么删除相关字段，于是将dataV2.json文件删除，重新扫码登录mys账号。
![QQ截图20240715004452](https://github.com/user-attachments/assets/acbf5a9b-f762-408f-b9c1-9a454c8c91a2)

然后设置兑换计划，出现了与 #341 同样的报错信息。
![360截图20240715003542717](https://github.com/user-attachments/assets/5ce8458f-ce2c-489d-9df7-3e604f25bc59)

最后是设置体力阈值的提醒，发现设置输入两次机器人才会回复，会以第二次设置的为准。
![QQ截图20240715003827](https://github.com/user-attachments/assets/7e7ad257-f2e2-42b4-8605-149c064841d4)

**Comment by dontdot** [comment]
[体力阈值修复](https://github.com/Joseandluue/nonebot-plugin-mystool/commit/a18a6701b4296b2e5c24eede7c9c36c476f444c4)
