### ISSUE TITLE
validata报错

### ISSUE THREAD

**Issue by beiji-O-o** [Ljzd-PRO/nonebot-plugin-mystool#348]
![image](https://github.com/user-attachments/assets/b8cd7fdb-a164-489a-8c60-5fe0487b972f)

**Comment by dontdot** [comment]
ttocr的平台不适配，在[ #309 ](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/309#issuecomment-2161977310)讨论过了解决方法了

**Comment by beiji-O-o** [comment]
> ttocr的平台不适配，在[ #309 ](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/309#issuecomment-2161977310)讨论过了解决方法了
> 
> 
我已经注释了那段代码了，注释前和注释后2个不同的报错

**Comment by dontdot** [comment]
你贴下get_validate函数的代码块出来

**Comment by beiji-O-o** [comment]
> 你贴下get_validate函数的代码块出来

![image](https://github.com/user-attachments/assets/4cb7f101-fd23-4119-bb3a-1a8f42196fb5)

**Comment by dontdot** [comment]
下面的那一段也要，上面超链接里贴的代码你有没有改？
什么都不改的使用方法：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/347#issuecomment-2245855174

**Comment by beiji-O-o** [comment]
> 下面的那一段也要，上面超链接里贴的代码你有没有改？ 什么都不改的使用方法：[#347 (comment)](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/347#issuecomment-2245855174)

用了什么都不用改的方法，把256.257都取消注释了
![image](https://github.com/user-attachments/assets/3684e2b5-bf12-4714-bd22-b52dd480d6c6)

**Comment by dontdot** [comment]
继续注释，ttocr不使用params的

**Comment by beiji-O-o** [comment]
> 继续注释，ttocr不使用params的

![image](https://github.com/user-attachments/assets/2de19c59-65ff-4f80-a702-c34d39020b1f)

**Comment by dontdot** [comment]
代码块和config.json里的geetest_json贴一下

**Comment by beiji-O-o** [comment]
> 代码块和config.json里的geetest_json贴一下

![image](https://github.com/user-attachments/assets/03d869d9-21f0-48f5-88a6-6f0f4fa690e0)

**Comment by dontdot** [comment]
get_validate函数的代码块呢

**Comment by beiji-O-o** [comment]
> 代码块和config.json里的geetest_json贴一下

![image](https://github.com/user-attachments/assets/03d869d9-21f0-48f5-88a6-6f0f4fa690e0)


> get_validate

在哪里

**Comment by dontdot** [comment]
![image](https://github.com/user-attachments/assets/63579a94-fbc4-4165-8b4e-7572e03d38bd)

**Comment by beiji-O-o** [comment]
> ![image](https://private-user-images.githubusercontent.com/55482264/351965761-63579a94-fbc4-4165-8b4e-7572e03d38bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODI2MjUsIm5iZiI6MTcyMTg4MjMyNSwicGF0aCI6Ii81NTQ4MjI2NC8zNTE5NjU3NjEtNjM1NzlhOTQtZmJjNC00MTY1LThiNGUtNzU3MmUwM2QzOGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA0Mzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NTMzODViMzQ2YzU2OGZjM2Y1NTJmNDgzNjYzNWYxYWVhMDkyOWQ5OThiMmE0NTBkOTVmMzMxYTU1YjlhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.odnrbRdWpYAa1uepzYdE2Wwp8EWw34LtZVvoJbn__PA)

![image](https://github.com/user-attachments/assets/c7ec67bc-1218-49eb-abc5-fc9b7961195d)

**Comment by beiji-O-o** [comment]
rrtoc的怎么搞啊，我买了rrtoc的了。

**Comment by beiji-O-o** [comment]
rrocr的是不是能直接用啊

**Comment by dontdot** [comment]
是

**Comment by beiji-O-o** [comment]
> 是

<img width="299" alt="image" src="https://github.com/user-attachments/assets/f670a095-5397-4e35-b1bf-2c56b4be77c6">
rr的这样弄嘛，256.257取消注释？

**Comment by dontdot** [comment]
嗯

**Comment by beiji-O-o** [comment]
> 嗯

![image](https://github.com/user-attachments/assets/f8690380-1cc3-48cb-849a-12a156af7182)

**Comment by dontdot** [comment]
appkey等参数填进params里

**Comment by beiji-O-o** [comment]
> appkey等参数填进params里

<img width="289" alt="image" src="https://github.com/user-attachments/assets/41827aff-10b8-4454-b086-b21c812f5c98">

**Comment by dontdot** [comment]
成功没
![image](https://github.com/user-attachments/assets/940c092c-60c5-4253-867d-500bfaf477c3)
这样才对

**Comment by beiji-O-o** [comment]
> 成功没
> 
> ![image](https://github.com/user-attachments/assets/940c092c-60c5-4253-867d-500bfaf477c3)
> 
> 这样才对

好了，但是rrcor又登不上去了，后面好像续费不了了

**Comment by beiji-O-o** [comment]
rrcor中午能打开续费，现在又上不去了……
