### ISSUE TITLE
安装机器人一直报错

### ISSUE THREAD

**Issue by qq57240** [Ljzd-PRO/nonebot-plugin-mystool#35]
`(nb_venv) jiajia@cloudserver:~/mystool$ nb plugin install nonebot_plugin_mystool
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: nonebot-plugin-mystool in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (0.1.5)
Requirement already satisfied: Pillow>=9.1.1 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot-plugin-mystool) (9.3.0)
Requirement already satisfied: nonebot_adapter_onebot<3.0.0,>=2.1.3 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot-plugin-mystool) (2.1.5)
Requirement already satisfied: ntplib<0.5.0,>=0.4.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot-plugin-mystool) (0.4.0)
Requirement already satisfied: httpx>=0.22.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot-plugin-mystool) (0.23.0)
Requirement already satisfied: tenacity>=2.28.1 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot-plugin-mystool) (8.1.0)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot-plugin-mystool) (2.28.1)
Requirement already satisfied: nonebot_plugin_apscheduler<0.2.0,>=0.1.4 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot-plugin-mystool) (0.1.4)
Requirement already satisfied: httpcore<0.16.0,>=0.15.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from httpx>=0.22.0->nonebot-plugin-mystool) (0.15.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from httpx>=0.22.0->nonebot-plugin-mystool) (1.5.0)
Requirement already satisfied: certifi in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from httpx>=0.22.0->nonebot-plugin-mystool) (2022.9.24)
Requirement already satisfied: sniffio in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from httpx>=0.22.0->nonebot-plugin-mystool) (1.3.0)
Requirement already satisfied: nonebot2<3.0.0,>=2.0.0-beta.3 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (2.0.0rc1)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (1.0.4)
Requirement already satisfied: apscheduler<4.0.0,>=3.7.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot_plugin_apscheduler<0.2.0,>=0.1.4->nonebot-plugin-mystool) (3.9.1.post1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.28.1->nonebot-plugin-mystool) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.28.1->nonebot-plugin-mystool) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.28.1->nonebot-plugin-mystool) (2.1.1)
Requirement already satisfied: pytz in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler<0.2.0,>=0.1.4->nonebot-plugin-mystool) (2022.6)
Requirement already satisfied: six>=1.4.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler<0.2.0,>=0.1.4->nonebot-plugin-mystool) (1.16.0)
Requirement already satisfied: setuptools>=0.7 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler<0.2.0,>=0.1.4->nonebot-plugin-mystool) (65.5.1)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler<0.2.0,>=0.1.4->nonebot-plugin-mystool) (4.2)
Requirement already satisfied: anyio==3.* in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from httpcore<0.16.0,>=0.15.0->httpx>=0.22.0->nonebot-plugin-mystool) (3.6.2)
Requirement already satisfied: h11<0.13,>=0.11 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from httpcore<0.16.0,>=0.15.0->httpx>=0.22.0->nonebot-plugin-mystool) (0.12.0)
Requirement already satisfied: uvicorn[standard]<0.19.0,>=0.18.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.18.3)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.6.0)
Requirement already satisfied: tomlkit<1.0.0,>=0.10.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.10.2)
Requirement already satisfied: pydantic[dotenv]<1.10.0,>=1.9.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (1.9.2)
Requirement already satisfied: fastapi<0.80.0,>=0.79.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.79.1)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (2.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=3.10.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (4.4.0)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (1.8.1)
Requirement already satisfied: starlette==0.19.1 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from fastapi<0.80.0,>=0.79.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.19.1)
Requirement already satisfied: python-dotenv>=0.10.4 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from pydantic[dotenv]<1.10.0,>=1.9.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.21.0)
Requirement already satisfied: pytz-deprecation-shim in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler<0.2.0,>=0.1.4->nonebot-plugin-mystool) (0.1.0.post0)
Requirement already satisfied: click>=7.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from uvicorn[standard]<0.19.0,>=0.18.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (8.1.3)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from uvicorn[standard]<0.19.0,>=0.18.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.17.0)
Requirement already satisfied: pyyaml>=5.1 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from uvicorn[standard]<0.19.0,>=0.18.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (6.0)
Requirement already satisfied: websockets>=10.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from uvicorn[standard]<0.19.0,>=0.18.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (10.4)
Requirement already satisfied: watchfiles>=0.13 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from uvicorn[standard]<0.19.0,>=0.18.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.18.1)
Requirement already satisfied: httptools>=0.4.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from uvicorn[standard]<0.19.0,>=0.18.0->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (0.5.0)
Requirement already satisfied: multidict>=4.0 in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from yarl<2.0.0,>=1.7.2->nonebot2<3.0.0,>=2.0.0-beta.3->nonebot_adapter_onebot<3.0.0,>=2.1.3->nonebot-plugin-mystool) (6.0.2)
Requirement already satisfied: tzdata in /home/jiajia/.virtualenvs/nb_venv/lib/python3.10/site-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler<0.2.0,>=0.1.4->nonebot-plugin-mystool) (2022.6)
RuntimeError('Config file /home/jiajia/mystool/pyproject.toml does not exist!')`
提示缺少pyproject.toml这个文件

**Comment by zero9931** [comment]
同样的问题，请问你解决了吗

**Comment by Ljzd-PRO** [comment]
似乎是因为没有创建机器人项目，机器人项目目录下会有一个 `pyproject.toml`
https://v2.nonebot.dev/docs/tutorial/create-project

**Comment by Ljzd-PRO** [comment]
> 似乎是因为没有创建机器人项目，机器人项目目录下会有一个 `pyproject.toml`
> https://v2.nonebot.dev/docs/tutorial/create-project

使用
```
nb create
```
进行创建
