### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by haoeixc** [Ljzd-PRO/nonebot-plugin-mystool#357]
佬，stable，dev和那个两种登录的分支都试了登录失败，是不是牢米又改api了
![捕获45678](https://github.com/user-attachments/assets/a5304be0-c2f1-483e-a97c-f0dca62023e0)
![捕获34543](https://github.com/user-attachments/assets/b1758d31-49a3-4df5-8516-e0a679839cd8)
![捕7676获](https://github.com/user-attachments/assets/f2bfc6da-0dbb-47ed-9275-ef9ad0fc108b)

**Comment by Ljzd-PRO** [comment]
第一个登录方式获取stoken V1的确实已经改了，第二个也就是目前的扫码登录方式，二维码确实有超时吗？

**Comment by haoeixc** [comment]
> 第一个登录方式获取stoken V1的确实已经改了，第二个也就是目前的扫码登录方式，二维码确实有超时吗？

二维码过期，获取扫描状态超时。
![Screenshot_2024-08-10-16-05-49-400_com.tencent.mobileqq.png](https://github.com/user-attachments/assets/0a788ae8-7376-4e8a-80c8-de4ad8bb8370)

**Comment by haoeixc** [comment]
> 第一个登录方式获取stoken V1的确实已经改了，第二个也就是目前的扫码登录方式，二维码确实有超时吗？

补充了await，虽然没超时但是还是二维码过期，登录失败

![Image](https://github.com/user-attachments/assets/5d6497c4-8fbb-4394-acfa-7992b8def27b)

**Comment by tym2008** [comment]
我也有遇到类似的问题，可能是扫码获取token时app_id的问题，可以试试在src/nonebot_plugin_mystool/api/common.py中扫码登录获取二维码以及检查二维码是否扫描的部分把app_id改为”2“尝试，我改为”2“后可以正常登录

**Comment by haoeixc** [comment]
> 我也有遇到类似的问题，可能是扫码获取token时app_id的问题，可以试试在src/nonebot_plugin_mystool/api/common.py中扫码登录获取二维码以及检查二维码是否扫描的部分把app_id改为”2“尝试，我改为”2“后可以正常登录

具体是哪几行，我改了几个还是登不上去

**Comment by tym2008** [comment]
![image](https://github.com/user-attachments/assets/a56ce8a6-3ebf-472c-a120-8747ec736eeb)
![image](https://github.com/user-attachments/assets/03185f66-58cb-48d1-bd01-30b2c884f783)
我是这样改的

**Comment by tym2008** [comment]
> > 我也有遇到类似的问题，可能是扫码获取token时app_id的问题，可以试试在src/nonebot_plugin_mystool/api/common.py中扫码登录获取二维码以及检查二维码是否扫描的部分把app_id改为”2“尝试，我改为”2“后可以正常登录
> 
> 具体是哪几行，我改了几个还是登不上去

改了之后扫码显示的是未定的扫码登录

**Comment by haoeixc** [comment]
> > > 我也有遇到类似的问题，可能是扫码获取token时app_id的问题，可以试试在src/nonebot_plugin_mystool/api/common.py中扫码登录获取二维码以及检查二维码是否扫描的部分把app_id改为”2“尝试，我改为”2“后可以正常登录
> > 
> > 
> > 具体是哪几行，我改了几个还是登不上去
> 
> 改了之后扫码显示的是未定的扫码登录

nb大佬可以了

**Comment by wang4386** [comment]
> 我也有遇到类似的问题，可能是扫码获取token时app_id的问题，可以试试在src/nonebot_plugin_mystool/api/common.py中扫码登录获取二维码以及检查二维码是否扫描的部分把app_id改为”2“尝试，我改为”2“后可以正常登录

我是直接通过nb install安装的插件，插件文件地址不知道在哪里，可以告知一下吗？

**Comment by haoeixc** [comment]
> > 我也有遇到类似的问题，可能是扫码获取token时app_id的问题，可以试试在src/nonebot_plugin_mystool/api/common.py中扫码登录获取二维码以及检查二维码是否扫描的部分把app_id改为”2“尝试，我改为”2“后可以正常登录
> 
> 我是直接通过nb install安装的插件，插件文件地址不知道在哪里，可以告知一下吗？

如果你在虚拟环境下安装的一般都在项目目录的.venv\Lib\site-packages\nonebot_plugin_mystool目录下，他的src/nonebot_plugin_mystool/api/common.py貌似是直接源码放插件项目目录直接用的，而且卸载插件的时候也会提醒你删除的目录，那个提醒删除的目录也是这个插件的目录

**Comment by wang4386** [comment]
> > > 我也有遇到类似的问题，可能是扫码获取token时app_id的问题，可以试试在src/nonebot_plugin_mystool/api/common.py中扫码登录获取二维码以及检查二维码是否扫描的部分把app_id改为”2“尝试，我改为”2“后可以正常登录
> > 
> > 我是直接通过nb install安装的插件，插件文件地址不知道在哪里，可以告知一下吗？
> 
> 如果你在虚拟环境下安装的一般都在项目目录的.venv\Lib\site-packages\nonebot_plugin_mystool目录下，他的src/nonebot_plugin_mystool/api/common.py貌似是直接源码放插件项目目录直接用的，而且卸载插件的时候也会提醒你删除的目录，那个提醒删除的目录也是这个插件的目录

解决了，感谢

**Comment by dontdot** [comment]
app_id直接在config.json中的`game_token_app_id`修改
![image](https://github.com/user-attachments/assets/66f0dfbf-f31c-40f1-867c-3bf6705f3313)
目前只有`2`可用，其余皆报错`{"data":null,"message":"请求失败，当前设备或网络环境存在风险","retcode":-3503}`

**Comment by tym2008** [comment]
> app_id直接在config.json中的`game_token_app_id`修改 ![image](https://private-user-images.githubusercontent.com/55482264/358837283-66f0dfbf-f31c-40f1-867c-3bf6705f3313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTgzMzgsIm5iZiI6MTcyMzg5ODAzOCwicGF0aCI6Ii81NTQ4MjI2NC8zNTg4MzcyODMtNjZmMGRmYmYtZjMxYy00MGYxLTg2N2MtM2JmNjcwNWYzMzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEyMzM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYTk2ZTEzYmIxNGU2YTAxN2Q1NGRhMTg4NjkzMTI0ZjM3M2UzNTYzOTQ2OGJmODExOWEyOTg0NWQ1ZDc0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wv8jjYqxhWzOXpl3PC9nmT6dpttF__bsDkifFbDNvaw) 目前只有`2`可用，其余皆报错`{"data":null,"message":"请求失败，当前设备或网络环境存在风险","retcode":-3503}`

才发现配置文件里面有😂
我是在改littlepaimon的登录代码的时候发现的问题，然后就翻了下源码，改了发现能用了
不过我有个问题，既然配置文件有，async def后面定义tuple的时候为啥写了个app_id:1进去（py小白不是很看得懂），是要定义变量顺手写的吗

**Comment by dontdot** [comment]
设置的一个默认值，当调用没传入app_id是可以用默认值，不然会出错

**Comment by tym2008** [comment]
> 设置的一个默认值，当调用没传入app_id是可以用默认值，不然会出错

我就说为啥改了上面的那个值没用😂原来是默认值
