### ISSUE TITLE
崩铁签到稳定失败

### ISSUE THREAD

**Issue by ocetars** [Ljzd-PRO/nonebot-plugin-mystool#358]
![PixPin_2024-08-11_23-24-47](https://github.com/user-attachments/assets/02095be8-8bbc-4b34-8393-f4e72920616c)
![PixPin_2024-08-11_23-21-37](https://github.com/user-attachments/assets/4a470f90-818b-4e4d-ae2d-e1925e3a68c5)
日志如上
另外， #357 该问题也同样出现

**Comment by dontdot** [comment]
其他游戏能过验证就崩铁不行吗，用的是哪家打码的

**Comment by dontdot** [comment]
问题是没有`validate`的数据，你可以打印出`geetest_data`看看返回了什么信息
我记得debug日志有`geetest_data`的信息，你可以去打开mystool.log查看一下

**Comment by Ocetars** [comment]
找到log了（图一），另外今天早上执行的自动签到又成功签到了崩铁（图二），但是昨晚确实试了手动签到七八次都是同样的不通过报错内容。您看这个问题是打码平台的锅嘛？
![PixPin_2024-08-12_12-52-40](https://github.com/user-attachments/assets/ba65d1b8-bc0d-4045-ba4a-ac3947a5d42a)
![早上自动签到](https://github.com/user-attachments/assets/d0ea1184-4d77-4abc-9638-fadafad95cb3)

**Comment by ocetars** [comment]
> 问题是没有`validate`的数据，你可以打印出`geetest_data`看看返回了什么信息 我记得debug日志有`geetest_data`的信息，你可以去打开mystool.log查看一下

找到log了（图一），另外今天早上执行的自动签到又成功签到了崩铁（图二）同时也有少部分签到未通过，但是昨晚确实试了手动签到七八次都是同样的不通过报错内容。您看这个问题是打码平台的锅嘛？
![PixPin_2024-08-12_12-52-40](https://github.com/user-attachments/assets/ba65d1b8-bc0d-4045-ba4a-ac3947a5d42a)
![早上自动签到](https://github.com/user-attachments/assets/d0ea1184-4d77-4abc-9638-fadafad95cb3)

**Comment by dontdot** [comment]
你查下平台关于错误码503的说明，是不是跟challenge过期什么相关，我看返回的信息是这样的
**
![image](https://github.com/user-attachments/assets/28ded862-f4a6-4dc3-8ca3-70c30ee8edc3)
**

**Comment by ocetars** [comment]
> 你查下平台关于错误码503的说明，是不是跟challenge过期什么相关，我看返回的信息是这样的 ** ![image](https://private-user-images.githubusercontent.com/55482264/356945330-28ded862-f4a6-4dc3-8ca3-70c30ee8edc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjE1MjMsIm5iZiI6MTcyMzQ2MTIyMywicGF0aCI6Ii81NTQ4MjI2NC8zNTY5NDUzMzAtMjhkZWQ4NjItZjRhNi00ZGMzLThjYTMtNzBjMzBlZThlZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDExMTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlY2FhMmQxNzhmMDNlNmMwZmYwNWY4YTE0Zjc1MWJlMmY3NDlkYmZmZDU4Y2JmOWJhMDE4MmVjZjI1YzdmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.klQNa8flJ3VKdI8NRWnQHbHvDpaG3bdGL8UlMiGnFYA) **

我这个平台太简陋了，什么说明都没有，请问可以推荐一个您用的过码平台吗？

**Comment by ocetars** [comment]
如果不方便公开的话也许可以劳烦您发到我的邮箱？ocetars@gmail.com

**Comment by dontdot** [comment]
可以用其他issue里别人提到的ttocr，[适配方式](https://github.com/dontdot/nonebot-plugin-mystool/blob/help/tt.md)

**Comment by ocetars** [comment]
> 可以用其他issue里别人提到的ttocr，[适配方式](https://github.com/dontdot/nonebot-plugin-mystool/blob/help/tt.md)

好的。感谢
