### ISSUE TITLE
手动全体签到和手动指定用户签到报错

### ISSUE THREAD

**Issue by ocetars** [Ljzd-PRO/nonebot-plugin-mystool#364]
已设置admin_list，手动发送`#签到`功能正常，自动签到任务运行正常。
`#签到+QQ号` `#签到*` `#任务+QQ号` `#任务*`均出现同样的报错
![PixPin_2024-08-25_13-40-01](https://github.com/user-attachments/assets/465cc5ca-ef4a-4ab3-a0c3-7695d5d88427)
![PixPin_2024-08-25_13-40-31](https://github.com/user-attachments/assets/87e4ac05-e523-486f-b5d2-252a607915b3)

**Comment by dontdot** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b813782c07273d34d8742494176cae2eb6672e57/src/nonebot_plugin_mystool/command/plan.py#L78
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b813782c07273d34d8742494176cae2eb6672e57/src/nonebot_plugin_mystool/command/plan.py#L66
先手动把await去删除吧，*和+QQ号这种我不怎么用到，所以当时改我没太留意

**Comment by llllin2333** [comment]
删除了这两行还是无法执行的说
