### ISSUE TITLE
签到跟米游币任务报错，RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by chen8665272** [Ljzd-PRO/nonebot-plugin-mystool#39]
![)RSYVSWWI7 NLE`@K1WT(DJ](https://user-images.githubusercontent.com/60909156/206637148-5187b52a-5686-49cd-bfac-bfc5c8988d0e.png)
其他功能正常，但签到跟米游币任务报错。请问大佬如何解决？

**Comment by Everything0519** [comment]
这个问题的话其实有点棘手.. 你用的好像不是nonebot而是其他机器人框架对吧？
如果只对递归超过最大次数的话
`import sys
sys.setrecursionlimit(3000)  # 将默认的递归深度修改为3000`
你可以在执行文件 应该是你的bot.py中加入这段来解决
但是我担心的就是这是一个死循环 递归深度增加也没有效果 你可以加入这段话先试试看

**Comment by chen8665272** [comment]
> 这个问题的话其实有点棘手..你用的好像不是nonebot而是其他机器人框架对吧？ 如果只对递归超过最大次数的话 你可以在执行文件 应该是你的 bot.py 中加入这段来解决 但是我担心的就是这是一个死循环 递归深度增加也没有效果 你可以加入这段话先试试看`import sys sys.setrecursionlimit(3000) # 将默认的递归深度修改为3000`

是的，是用nodejs的机器人用插件套了个nonebot，加了这段话后还是没效果

**Comment by Everything0519** [comment]
可不可以调试一下看下这个exception具体是啥呀 就是在循环调用超过3000次之前

**Comment by chen8665272** [comment]
> 可不可以调试一下看下这个exception具体是啥呀 就是在循环调用超过3000次之前

![OT7R7I1%9BKE_C@MRRH} )1](https://user-images.githubusercontent.com/60909156/206838982-d4f55d3d-1543-41ed-8e91-f309bd5719cd.png)

**Comment by Everything0519** [comment]
试试143-147行改成
```
 await bot.send_private_msg(user_id=qq,message=msg + img)
```
如果还是不行 试试看改成
```
 await bot.send_private_msg(user_id=qq,message=msg)
```

**Comment by chen8665272** [comment]
> 试试143-147行改成
> 
> ```
>  await bot.send_private_msg(user_id=qq,message=msg + img)
> ```
> 
> 如果还是不行 试试看改成
> 
> ```
>  await bot.send_private_msg(user_id=qq,message=msg)
> ```

大佬是不是nonebot_plugin_mystool里的timing.py文件对吧

**Comment by Everything0519** [comment]
是的

**Comment by chen8665272** [comment]
![BF0}HO2O@955Z8V5013K 6E](https://user-images.githubusercontent.com/60909156/206840090-90fb7b0c-2919-42d0-adeb-c4b5aa7c9177.png)
这一段吗？

**Comment by chen8665272** [comment]
![$OPVII%W@{83U1}XC%B{O@A](https://user-images.githubusercontent.com/60909156/206840197-c66463f5-7e69-47c7-bad9-0956ef855a01.png)
这一段吗？

**Comment by Everything0519** [comment]
不是的 是在perform_game_sign()函数里面 这是签到函数 
把这一段改成我说的那些
```
await bot.send_msg(
                            message_type="private",
                            user_id=qq,
                            message=message
                        )
```

然后你调用一下/签到 命令 看看是否正常

**Comment by chen8665272** [comment]
![RTG)W_ P3@A}BYS24LWZZ@Y](https://user-images.githubusercontent.com/60909156/206842287-b770d799-a9a2-4b40-9a52-4f83924a586f.png)
大佬，还是老样子

**Comment by Everything0519** [comment]
改成后一种情况也不行吗 不要img

**Comment by chen8665272** [comment]
是的

**Comment by Everything0519** [comment]
你调用其他命令 比如说/商品 原神  让他发送原神的商品图片 可以正常执行吗

**Comment by chen8665272** [comment]
![K HE8YAG1~%GD)VS D_ `G1](https://user-images.githubusercontent.com/60909156/206842440-a9dd7999-fe57-4e4a-89e4-111b36ce9222.png)
可以正常执行

**Comment by Everything0519** [comment]
其实是签到成功了 就是消息没有正常推送
可以给我个联系方式吗 我看看能不能远程调试一下

**Comment by chen8665272** [comment]
可以，QQ:1102273556

**Comment by Cloud-Lj** [comment]
大佬，调试完能求个结果吗

**Comment by chen8665272** [comment]
> 大佬，调试完能求个结果吗

大佬还在研究

**Comment by chen8665272** [comment]
初步判断是bot.py原因，其他插件也会报错，此问题关闭。
