### ISSUE TITLE
nonebot2.0.0rc1版本不适配

### ISSUE THREAD

**Issue by pixiver** [Ljzd-PRO/nonebot-plugin-mystool#42]
rc1版本删除了export插件导致无法使用。有没有办法在rc1版本里面装上export插件？

**Comment by Ljzd-PRO** [comment]
更新 `nonebot_plugin_apscheduler ` 至最新即可

**Comment by pixiver** [comment]
> 更新 `nonebot_plugin_apscheduler ` 至最新即可

多谢，解决了

**Comment by pixiver** [comment]
大佬，还是不行，我用poetry run nb plugin install nonebot_plugin_mystool安装的时候会自动安装apscheduler0.1.4.。然后我卸载apscheduler0.1.4装上0.2.0版本后就出问题，连接不上。

**Comment by pixiver** [comment]
找到原因，是和原神的一个机器人插件冲突了。
