### ISSUE TITLE
命令前缀

### ISSUE THREAD

**Issue by kongxiangyi88** [Ljzd-PRO/nonebot-plugin-mystool#54]
大佬你好，这个可不可以做一个在env文件一句话就可以设置插件命令前缀的功能，因为命令与别的插件冲突，刚接触这个，改源代码对我来说十分困难。

**Comment by Everything0519** [comment]
请修改config.py 第108行的command_start变量 推荐修改为`command_start = 'mt '`
这样的话 命令呼出就需要带mt开头了 例如调用帮助命令 就需要 /mt 帮助 才可以呼出

**Comment by kongxiangyi88** [comment]
报歉，还不太了解，这个config.py文件在哪里。

**Comment by Ljzd-PRO** [comment]
> 报歉，还不太了解，这个config.py文件在哪里。

属于源码的一部分，在python目录下的 `site-packages` 目录。
完整路径可以用下面的命令查看：
```
pip show nonebot-plugin-mystool
```
`config.py` 每个配置项的说明都有写在注释里，也可以参考文档：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Configuration-Config

**Comment by kongxiangyi88** [comment]
好的，已经解决了，谢谢大佬。
