### ISSUE TITLE
Failed to import "nonebot_plugin_mystool" (@get driver().on startup SyntaxError: invalid syntax)

### ISSUE THREAD

**Issue by bangbanbab** [Ljzd-PRO/nonebot-plugin-mystool#56]
![image](https://user-images.githubusercontent.com/87685982/212824048-f9a7c378-93e2-424e-992a-af1ed688ac4e.png)

**Comment by Ljzd-PRO** [comment]
试试看python3.9、python3.10，python3.8已经是最低支持的了
