### ISSUE TITLE
入群欢迎

### ISSUE THREAD

**Issue by kongxiangyi88** [Ljzd-PRO/nonebot-plugin-mystool#58]
当bot为管理员时，当有入群申请时就会发送欢迎消息，而不是同意后入群再发，希望改进下，群内一个指令就可以设置是否开启，默认关闭，如果可以的话可以加个自定义欢迎。🙏🏻

**Comment by Ljzd-PRO** [comment]
新版本取消了进群发送消息，加好友发送消息的可以在配置中关闭：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Configuration-Config#add_friend_welcome

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v0.2.3

**Comment by kongxiangyi88** [comment]
没仔细看，麻烦了
