### ISSUE TITLE
原神商品时间对不上

### ISSUE THREAD

**Issue by qsm-mz-hn** [Ljzd-PRO/nonebot-plugin-mystool#59]
系统时间与网络时间的误差为 -0.04 秒，但商品时间全都是11：00，一个也对不上，想问下是怎么回事？

**Comment by Ljzd-PRO** [comment]
商品兑换时间是米游社标的时间，实际兑换的时间会根据误差进行调整，误差一点点没关系。

**Comment by typenoob** [comment]
实际兑换时间是19：00，差8个小时大概率是时区问题，显示的是utc时间？

**Comment by Ljzd-PRO** [comment]
米游社App里显示的是几点

**Comment by Ljzd-PRO** [comment]
应该默认是UTC

**Comment by Ljzd-PRO** [comment]
不过我用的时候时间没有错。可能如果在别的地区或者系统设置的时区不同的话就会。

**Comment by typenoob** [comment]
> 不过我用的时候时间没有错。可能如果在别的地区或者系统设置的时区不同的话就会。

对的，我用的是亚马逊云的机子，应该和系统设置的时区有关

**Comment by qsm-mz-hn** [comment]
> > 不过我用的时候时间没有错。可能如果在别的地区或者系统设置的时区不同的话就会。
> 
> 对的，我用的是亚马逊云的机子，应该和系统设置的时区有关

我现在是UTC+08:00，难道是时区问题吗？

**Comment by ayakasuki** [comment]
可能是机器人时间不对，在env文件加入这段
`APSCHEDULER_CONFIG={"apscheduler.timezone": "Asia/Shanghai"}`
