### ISSUE TITLE
导出cookie功能能否添加一个

### ISSUE THREAD

**Issue by GuGuNiu** [Ljzd-PRO/nonebot-plugin-mystool#61]
感谢您提供多功能的插件，能否加入导出cookie的功能呢，您的插件采用验证码登录可以获取login_ticket= 的数据，这将简化获取难度。

**Comment by BBQ-Sheep** [comment]
> 感谢您提供多功能的插件，能否加入导出cookie的功能呢，您的插件采用验证码登录可以获取login_ticket= 的数据，这将简化获取难度。

**Comment by Ljzd-PRO** [comment]
是的，之后还会加入导入和导出cookie的功能
