### ISSUE TITLE
签到失败问题咨询

### ISSUE THREAD

**Issue by shelter132** [Ljzd-PRO/nonebot-plugin-mystool#64]
遇到了签到失败的问题，但是启动时无报错，发送签到命令后日志中提示
![image](https://user-images.githubusercontent.com/99066443/215941598-befb0c20-e4ef-4815-a5f9-5f101ad866a4.png)
虽然在已解决的issues（https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/60）中查找到相似问题，但并未查找到具体解决方案

**Comment by Ljzd-PRO** [comment]
目前原神签到是没法成功，你的这个账号是刚登陆绑定以后就失败的吗？

**Comment by shelter132** [comment]
是的，签到命令没有成功过，使用任务命令的话会显示签到成功但实际并没有签到

**Comment by Ljzd-PRO** [comment]
> 是的，签到命令没有成功过，使用任务命令的话会显示签到成功但实际并没有签到

/任务 执行的签到是米游社讨论区签到，可得到米游币，不是游戏签到。

原神游戏签到失败返回的信息和DS salt错误时返回的内容一样，所以判定成了salt无效，但同样的salt崩坏三却可以正常执行。之前参考其他签到脚本的项目，也用的是一样的salt

**Comment by shelter132** [comment]
所以目前由于原神API问题，签到功能无法使用并且暂时没有解决方案是吗？

**Comment by Ljzd-PRO** [comment]
是的，似乎没有找到解决方法

**Comment by Ljzd-PRO** [comment]
#32 有新的解决方案了，可以尝试。
