### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by xueqi5201314** [Ljzd-PRO/nonebot-plugin-mystool#69]
![image](https://user-images.githubusercontent.com/108047693/223436633-19ca67a6-4f37-4c0c-a20a-f5b9a25e497b.png)

**Comment by Ljzd-PRO** [comment]
还有更多信息吗？

**Comment by Ljzd-PRO** [comment]
今天我倒是遇到了无法启动的问题，但那是启动时执行操作失败导致的，插件能够成功导入。

**Comment by xueqi5201314** [comment]
![image](https://user-images.githubusercontent.com/108047693/223929429-7821d5a6-99e3-425e-82bb-c15a24d88800.png)
![image](https://user-images.githubusercontent.com/108047693/223929503-f014f89e-5368-47af-acff-cde92c41f8cd.png)

**Comment by xueqi5201314** [comment]
插件时基于云崽的py-plugin

**Comment by Ljzd-PRO** [comment]
尝试使用python3.9以及以上的版本。
这里看上去是
```
@get_driver().on_startup
```
被认为有语法问题，可能是python3.8不支持这样使用。

**Comment by Taokyla** [comment]
建议手动给他改成
```
driver = get_driver()

@driver.on_startup
async def set_game_list():
    pass
````

**Comment by xueqi5201314** [comment]
已经没有用这个插件了，感谢帮助
