### ISSUE TITLE
兑换结束后发出命令/商品和米游社后，回复请稍等图片正在加载中，程序运行停止后台退出

### ISSUE THREAD

**Issue by Fins03** [Ljzd-PRO/nonebot-plugin-mystool#71]

**Comment by Ljzd-PRO** [comment]
看一下日志文件，在nonebot2目录下的 `data/nonebot-plugin-mystool` 里，日志文件格式是 .log。

**Comment by Fins03** [comment]
我看了下log 03-23 07:17:13 [INFO] nonebot_plugin_mystool | 商品列表图片生成 - 正在生成图片...
03-23 07:17:15 [INFO] nonebot_plugin_mystool | 商品列表图片生成 - 已生成图片...
03-23 07:17:18 [INFO] nonebot_plugin_mystool | 商品列表图片生成 - 正在生成图片...
后面就停止

不过我后面退出全部后台重新试的情况下图片成功生成了，可能是不同的程序之间冲突
程序没有问题，我把issue关了，谢谢

**Comment by Fins03** [comment]
对了对了，那个程序是nenobot2插件里，查询原神前瞻直播兑换码的，这个启动你的程序就会一直很奇怪，后面我改了命令以为不会冲突了，没想到

**Comment by Ljzd-PRO** [comment]
> 对了对了，那个程序是nenobot2插件里，查询原神前瞻直播兑换码的，这个启动你的程序就会一直很奇怪，后面我改了命令以为不会冲突了，没想到

hmm会遇到哪些问题呢

**Comment by Fins03** [comment]
> > 对了对了，那个程序是nenobot2插件里，查询原神前瞻直播兑换码的，这个启动你的程序就会一直很奇怪，后面我改了命令以为不会冲突了，没想到
> 
> hmm会遇到哪些问题呢

您的输入有误，请重新输入

具体用法：
兑换 + <商品ID> ➢ 新增兑换计划
兑换 - <商品ID> ➢ 删除兑换计划
商品 ➢ 查看米游社商品

后面无论发什么命令就只会重复发这句话

**Comment by Ljzd-PRO** [comment]
> > > 对了对了，那个程序是nenobot2插件里，查询原神前瞻直播兑换码的，这个启动你的程序就会一直很奇怪，后面我改了命令以为不会冲突了，没想到
> > 
> > 
> > hmm会遇到哪些问题呢
> 
> 您的输入有误，请重新输入
> 
> 具体用法： 兑换 + <商品ID> ➢ 新增兑换计划 兑换 - <商品ID> ➢ 删除兑换计划 商品 ➢ 查看米游社商品
> 
> 后面无论发什么命令就只会重复发这句话

有聊天记录的截图吗，就是使用了哪个命令导致的

**Comment by Fins03** [comment]
命令是/兑换码，我记得很清楚，然后程序就没法回复其他命令了

**Comment by Fins03** [comment]
> 命令是/兑换码，我记得很清楚，然后程序就没法回复其他命令了

不过等一会后程序会恢复正常，也不影响使用，麻烦大佬了，谢谢

**Comment by Ljzd-PRO** [comment]
那应该是命令识别方面还要改改，“兑换码”以“兑换”开头，但应当是只有“兑换”和别的几个指定的词才能触发

**Comment by Ljzd-PRO** [comment]
对于命令冲突，例如 /商品A 也会被识别为 /商品 ，而“A”为其中的参数，由于不知道什么原因在源码中并没有找到nonebot的 [CommandWhitespace](https://v2.nonebot.dev/docs/advanced/dependency#commandwhitespace)，没法使用，其他命令暂时没有解决方案。
