### ISSUE TITLE
全局配置修改后不生效

### ISSUE THREAD

**Issue by Rorschachina** [Ljzd-PRO/nonebot-plugin-mystool#72]
按照文档的要求，我修改了data/nonebot-plugin-mystool/pluginConfig.json中的配置信息，具体更改项为：
"COMMAND_START": "mt ",
"SIGN_TIME": "02:30"

我是安装在docker容器中的，插件我是装在了LittlePaimon下面的。
重启过服务了也没生效，容器也重启过了，也不行。

**Comment by soha12** [comment]
我也有这个问题
