### ISSUE TITLE
程序在生成第四个商品图片的时候很慢，很多时候会卡住，没办法生成

### ISSUE THREAD

**Issue by qwqq1** [Ljzd-PRO/nonebot-plugin-mystool#76]

**Comment by Fins03** [comment]
登录后签到之前是成功的，我也不知道是环境的原因是不是，后面自动签到总是没有启动，报错[DEBUG] nonebot_plugin_mystool | Traceback (most recent call last):   File "/root/my/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/mybMission.py", line 241, in get_posts     async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), reraise=True,   File "/root/my/.venv/lib/python3.9/site-packages/tenacity/_asyncio.py", line 71, in __anext__     do = self.iter(retry_state=self._retry_state)   File "/root/my/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter     raise retry_exc.reraise()   File "/root/my/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise     raise self.last_attempt.result()   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result     return self.__get_result()   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result     raise self._exception   File "/root/my/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/mybMission.py", line 246, in get_posts     res = await self.client.get(URL_GET_POST.format(GAME_ID[game].gids), headers=headers, KeyError: 'bbs'

我怀疑是我Python不对，但是之前用的也是这个python，却可以签到

**Comment by Ljzd-PRO** [comment]
日志文件里有更多信息吗

**Comment by qwqq1** [comment]
日志里没有问题，就是生成很慢，第四第五的时候，有时候几乎大半天过去了，还没生成，直接就结束了
![捕获](https://user-images.githubusercontent.com/105484987/230063290-9f717129-9708-4ce1-8cfc-4c7e80a7bcb2.PNG)

**Comment by qwqq1** [comment]
我再试下，等会再发

**Comment by qwqq1** [comment]
![bg](https://user-images.githubusercontent.com/105484987/230067814-d4f997f1-bb65-470e-8216-621c5a2b6bd2.PNG)

**Comment by qwqq1** [comment]
过去了20分钟，还是没有生成图片，也没有回复

**Comment by qwqq1** [comment]
![捕获11](https://user-images.githubusercontent.com/105484987/230068513-ec184f91-6b47-4c15-b4e9-55fa10d020c9.PNG)
这个是输出的

**Comment by qwqq1** [comment]
![捕获](https://user-images.githubusercontent.com/105484987/230096648-1a79272e-f7dc-4f57-a596-61cb53607567.PNG)
一个小时后成功生成

**Comment by Ljzd-PRO** [comment]
#102 #105 增加了多进程生成商品图片，可能会好一些
