### ISSUE TITLE
真寻适配版

### ISSUE THREAD

**Issue by NathanSummer** [Ljzd-PRO/nonebot-plugin-mystool#77]
这样报错咋办
![image](https://user-images.githubusercontent.com/88868171/229974086-cb7a918b-aa20-4fa6-a96d-712d69612256.png)

**Comment by Ljzd-PRO** [comment]
依赖文件需要更新，Python版本的范围应该设置在`>=3.9,<4.0`
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b137f663de662d9435a17ee4f2f843dd4d4e42e2/pyproject.toml#L26

**Comment by NathanSummer** [comment]
> 依赖文件需要更新，Python版本的范围应该设置在`>=3.9,<4.0`
> 
> https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b137f663de662d9435a17ee4f2f843dd4d4e42e2/pyproject.toml#L26

十分感谢！/鞠躬

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/229978342-bfcb21fa-fcf8-4299-ab87-9b54645f3cc7.png)
![image](https://user-images.githubusercontent.com/88868171/229978411-c8c22a8d-c99b-47b8-bd96-a433ddc89071.png)
这种情况重试一下就可以了吧？

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/229982668-14600de6-2340-45dd-8600-8b21b0e4cd52.png)
这咋办呀
