### ISSUE TITLE
大别野频道米游社任务执行失败

### ISSUE THREAD

**Issue by Fins03** [Ljzd-PRO/nonebot-plugin-mystool#78]
登录后签到之前是成功的，我也不知道是环境的原因是不是，后面自动签到总是没有启动，报错[DEBUG] nonebot_plugin_mystool | Traceback (most recent call last):   File "/root/my/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/mybMission.py", line 241, in get_posts     async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), reraise=True,   File "/root/my/.venv/lib/python3.9/site-packages/tenacity/_asyncio.py", line 71, in __anext__     do = self.iter(retry_state=self._retry_state)   File "/root/my/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter     raise retry_exc.reraise()   File "/root/my/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise     raise self.last_attempt.result()   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result     return self.__get_result()   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result     raise self._exception   File "/root/my/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/mybMission.py", line 246, in get_posts     res = await self.client.get(URL_GET_POST.format(GAME_ID[game].gids), headers=headers, KeyError: 'bbs'

我怀疑是我Python不对，但是之前用的也是这个python，却可以签到

**Comment by Ljzd-PRO** [comment]
有更改执行米游社任务的所在频道吗？比如在原神频道下完成任务，或者在崩坏3频道。这里好像是选了大别野频道

**Comment by Ljzd-PRO** [comment]
大别野 频道缺少执行米游社任务所需要的`GameID`，但是设置的菜单却有这个选项，所以运行的时候找不到对应的`GameID`就出错了
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b137f663de662d9435a17ee4f2f843dd4d4e42e2/src/nonebot_plugin_mystool/mybMission.py#L94-L101

**Comment by Ljzd-PRO** [comment]
可以先在`data/userdata.json`数据文件里任务执行频道`missionGame`里删除大别野(`bbs`)

**Comment by Fins03** [comment]
好的，谢谢

**Comment by Fins03** [comment]
那我关闭问题了，谢谢

**Comment by Fins03** [comment]
我可以提个建议吗，就是在自动签到下面弄个随机数，这样同个账号就不会一直在同个时间签到了，会减少账号的风控，最近被风控了，改了密码后甚至连验证码都不发给我了

**Comment by Ljzd-PRO** [comment]
可以的

**Comment by Ljzd-PRO** [comment]
> 那我关闭问题了，谢谢

还没有修复，可以等修复了再关闭。
