### ISSUE TITLE
更新到0.2.5后插件指令会被naturel_gpt插件响应

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#81]
我从0.2.4更新到0.2.5后插件的指令（比如/登录  /兑换 /帮助...）会被gpt机器人捕获 旧版本不会有这种情况 请问改怎么解决呢 我是nb机器人新手 请多多指教

**Comment by Ljzd-PRO** [comment]
可以举例一下吗？聊天记录。可能是0.2.5删除了命令的优先度设置

**Comment by Sakamakiiizayoi** [comment]
![image](https://user-images.githubusercontent.com/67581432/233909124-e8c68da2-7469-49c8-9b41-9ead6a6bc195.png)
旧版本米游社插件使用指令时不会造成chatgpt插件的响应 新版本就会同时响应

**Comment by Ljzd-PRO** [comment]
应该是这次删去了优先级的设置导致的

**Comment by ayakasuki** [comment]
是因为删了block，我添加回block=true就OK了

**Comment by Sakamakiiizayoi** [comment]
![image](https://user-images.githubusercontent.com/67581432/235032365-e4207490-7041-49ca-872a-8beaa0de42c8.png)
更新了0.2.7后还是会这样 请问是哪里设置有问题吗

**Comment by Ljzd-PRO** [comment]
看了一下，还有几个命令没有改，可以试一下 /便笺 是否正常

**Comment by Sakamakiiizayoi** [comment]
对的 便笺是正常的 其他指令还是有问题

**Comment by Sakamakiiizayoi** [comment]
/帮助和/设置 这两个指令还是会被naturel_gpt捕获 是naturel_gpt的问题吗 其他指令都没问题了

**Comment by ayakasuki** [comment]
> /帮助和/设置 这两个指令还是会被naturel_gpt捕获 是naturel_gpt的问题吗 其他指令都没问题了

我估计是你的naturel_gpt的priority比mystool高的问题

**Comment by Sakamakiiizayoi** [comment]
那这个priority可以调吗 请问在那里设置呢

**Comment by Ljzd-PRO** [comment]
https://v2.nonebot.dev/docs/advanced/matcher#响应优先级

https://v2.nonebot.dev/docs/advanced/matcher#阻断

可能我们需要设置相应优先级为0，因为优先级越小越先被触发，然后被 `block=True` 阻断，不传递给下一个响应器。

如果命令冲突，则可以设置 [COMMAND_START](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Configuration-Config#command_start)

**Comment by Ljzd-PRO** [comment]
查了一下naturel_gpt默认优先级是比较大的
https://github.com/KroMiose/nonebot_plugin_naturel_gpt/blob/b7774d05ed5f83e4f29c344c942b02c48c97ff81/nonebot_plugin_naturel_gpt/config.py#L242

主要问题还是有命令漏了改 `block=True` 😂
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/b50d913af78cb56f391b92273a6f78756d8b8034/src/nonebot_plugin_mystool/help.py#L14-L15
