### ISSUE TITLE
请问一下兑换商品的指令是啥？？

### ISSUE THREAD

**Issue by 63248797** [Ljzd-PRO/nonebot-plugin-mystool#82]
兑换 1234
兑换+1234
兑换1234

试了都说错误，是什么问题啊

**Comment by 63248797** [comment]
具体用法：
#兑换 + <商品ID> ➢ 新增兑换计划
#兑换 - <商品ID> ➢ 删除兑换计划
#商品 ➢ 查看米游社商品

#兑换 + <商品1234>，也不对啊，属实搞蒙了

**Comment by Ljzd-PRO** [comment]
`/兑换.+ 1234`这样，使用NoneBot分隔符，默认有`.`分隔符。
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki/Information-Exchange

**Comment by Ljzd-PRO** [comment]
显示的帮助信息有关于分隔符的信息吗？可能帮助信息没改全
