### ISSUE TITLE
支持星穹铁道自动委派

### ISSUE THREAD

**Issue by King-hsw** [Ljzd-PRO/nonebot-plugin-mystool#94]
能不能支持铁道的自动委派功能呀，20小时的时间有时候会到半夜，不方便收取

**Comment by Ljzd-PRO** [comment]
如果是和游戏内部有关的话，可能不好搞，而且不知道会不会对账号有风险。目前都是用的米游社API。可能可以实现自动通知委派完成，如果米游社有相关API的话
